Repository espressif/arduino-esp32, pull requests merged in 2021-12, with the labels that each got.

#6018 [Docs] Update on the Windows install procedures
  docs/source/installing.rst
Labels: Type: Documentation

#5987 Delete .travis.yml file.
  .github/scripts/check-cmakelists.sh
  .github/scripts/on-push.sh
  .travis.yml
Labels: Type: CLI & Testing

#5986 Correct the execute bit of some files.
  .github/scripts/on-pages.sh
  cores/esp32/esp32-hal-i2c-slave.c
  cores/esp32/esp32-hal-i2c-slave.h
  cores/esp32/libb64/AUTHORS
  cores/esp32/libb64/LICENSE
  cores/esp32/libb64/cdecode.c
  cores/esp32/libb64/cdecode.h
  cores/esp32/libb64/cencode.c
  cores/esp32/libb64/cencode.h
  package.json
Labels: Type: CLI & Testing

#5984 Update Boards.txt
  boards.txt
Labels: Type: Bug :bug:

#5983 Prevent self hosted jobs to run on forks.
  .github/workflows/test_selfhosted_runner.yml
Labels: Type: CLI & Testing

#5894 [DOCS] Writing a new Arduino documentation about GPIO
  docs/source/_static/gpio_output.png
  docs/source/_static/gpio_pullup.png
  docs/source/api/gpio.rst
Labels: Type: Documentation

#5999 Adding Issue and Feature template
  .github/ISSUE_TEMPLATE/Feature-request.yml
  .github/ISSUE_TEMPLATE/Issue-report.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: Type: Documentation

#6031 [Fix] Added the Win32 not supported notice/warning
  docs/source/installing.rst
Labels: Type: Documentation

#6036 [Docs] Added USB documentation
  docs/source/api/usb.rst
  docs/source/api/usb_cdc.rst
  docs/source/api/usb_msc.rst
  docs/source/libraries.rst
Labels: Type: Documentation

#6049 [Examples] README revision to include missing and remove old entries
  libraries/README.md
Labels: Type: Documentation

#6005 add GPIO defines for C3
  cores/esp32/esp32-hal-gpio.c
Labels: Status: Test needed
