Repository espressif/arduino-esp32, pull requests merged in 2022-02, with the labels that each got.

#6213 Docs cleanup and version updated to 2.0.2
  docs/ISSUE_TEMPLATE.md
  docs/source/api/i2c.rst
  docs/source/boards/boards.rst
  docs/source/boards/generic.rst
  docs/source/common/datasheet.inc
  docs/source/conf.py
  docs/source/getting_started.rst
  docs/source/index.rst
  docs/source/libraries.rst
  docs/source/tutorials/io_mux.rst
Labels: Type: Documentation

#6215 Bootloader is at 0x0000 for S3
  tools/platformio-build-esp32s3.py
Labels: Chip: ESP32-S3

#6194 Touch Sensor IDF Refactoring
  cores/esp32/esp32-hal-touch.c
  cores/esp32/esp32-hal-touch.h
  libraries/ESP32/examples/Touch/TouchButton/.skip.esp32c3
  libraries/ESP32/examples/Touch/TouchButton/.skip.esp32s2
  libraries/ESP32/examples/Touch/TouchButton/.skip.esp32s3
  libraries/ESP32/examples/Touch/TouchButton/TouchButton.ino
  libraries/ESP32/examples/Touch/TouchButtonV2/.skip.esp32
  libraries/ESP32/examples/Touch/TouchButtonV2/.skip.esp32c3
  libraries/ESP32/examples/Touch/TouchButtonV2/TouchButtonV2.ino
Labels: Area: Peripherals API

#6203 Add Github action for uploading arduino-esp32 component.
  .github/workflows/upload-idf-component.yml
  idf_component.yml
Labels: Type: CI & Testing

#6226 Added dual antenna for WiFi (based on the ESP32-WROOM-DA module)
  libraries/WiFi/src/WiFiGeneric.cpp
  libraries/WiFi/src/WiFiGeneric.h
Labels: Area: BT&Wifi

#6292 Installing.rst_update
  docs/source/installing.rst
Labels: Type: Documentation

#6294 Fixes softAPConfig() return
  libraries/WiFi/src/WiFiAP.cpp
Labels: Area: BT&Wifi

#6285 Adds BLE examples to ESP32-C3 CI cycle
  libraries/BLE/examples/BLE_Beacon_Scanner/.skip.esp32c3
  libraries/BLE/examples/BLE_EddystoneTLM_Beacon/.skip.esp32c3
  libraries/BLE/examples/BLE_EddystoneURL_Beacon/.skip.esp32c3
  libraries/BLE/examples/BLE_client/.skip.esp32c3
  libraries/BLE/examples/BLE_iBeacon/.skip.esp32c3
  libraries/BLE/examples/BLE_notify/.skip.esp32c3
  libraries/BLE/examples/BLE_scan/.skip.esp32c3
  libraries/BLE/examples/BLE_server/.skip.esp32c3
  libraries/BLE/examples/BLE_server_multiconnect/.skip.esp32c3
  libraries/BLE/examples/BLE_uart/.skip.esp32c3
  libraries/BLE/examples/BLE_write/.skip.esp32c3
Labels: Chip: ESP32-C3, Type: CI & Testing

#6284 Added documentation for the Arduino IDE tools menu
  docs/source/_static/usb_msc_drive.png
  docs/source/getting_started.rst
  docs/source/guides/guides.rst
  docs/source/guides/tools_menu.rst
  docs/source/index.rst
  docs/source/tutorials/tutorials.rst
Labels: Type: Documentation

#6282 ADC esp32s2 attenuation fix for DAC pins
  cores/esp32/esp32-hal-adc.c
Labels: Area: Peripherals API

#6272 Fixes UART pin setting + adds CTS/RTS HW Flow Control
  cores/esp32/HardwareSerial.cpp
  cores/esp32/HardwareSerial.h
  cores/esp32/esp32-hal-uart.c
  cores/esp32/esp32-hal-uart.h
Labels: Type: Feature request, Area: Peripherals API

#6299 Update doc: Arduino as IDF component; fixes #5833
  docs/source/esp-idf_component.rst
Labels: Type: Documentation

#6301 Added ADC API doc + simple example
  docs/requirements.txt
  docs/source/api/adc.rst
  docs/source/conf.py
  libraries/ESP32/examples/AnalogRead/AnalogRead.ino
Labels: Type: Documentation

#6321 [Docs] Added more details about embedded FLASH and PSRAM on ESP32-S3.
  docs/source/guides/tools_menu.rst
Labels: Type: Documentation

#6330 LEDC & SigmaDelta documentation
  docs/source/api/ledc.rst
  docs/source/api/sigmadelta.rst
Labels: Type: Documentation

#6335 [Docs] Timer API documentation
  cores/esp32/esp32-hal-timer.h
  docs/source/api/timer.rst
Labels: Type: Documentation

#6337 [Docs] DAC API documentation
  docs/source/api/dac.rst
Labels: Type: Documentation

#5540 Added more details about PlatformIO
  docs/source/_static/logo_arduino.png
  docs/source/_static/logo_pio.png
  docs/source/getting_started.rst
  docs/source/installing.rst
Labels: Type: Documentation

#6359 FIX - wifiBegin works every 2nd time when connecting to same AP
  libraries/WiFi/src/WiFiGeneric.cpp
Labels: Area: BT&Wifi

#6357 WiFi DA: Added Dual Antenna to the docs and example created
  docs/source/api/wifi.rst
  libraries/WiFi/examples/WiFiScanDualAntenna/README.md
  libraries/WiFi/examples/WiFiScanDualAntenna/WiFiScanDualAntenna.ino
Labels: Type: Documentation
