Repository espressif/arduino-esp32, pull requests merged in 2022-04, with the labels that each got.

#6527 PHY8720(A) init timout failures: need to revert "GPIO refactoring (#6259)"
  cores/esp32/esp32-hal-gpio.h
  libraries/Ethernet/src/ETH.cpp
Labels: Area: Peripherals API

#6569 BUGFIX: FS read + speed improvements for SD
  libraries/FS/src/FS.cpp
  libraries/FS/src/FS.h
  libraries/FS/src/FSImpl.h
  libraries/FS/src/vfs_api.cpp
  libraries/FS/src/vfs_api.h
Labels: Area: Performance, Area: Libraries, Priority: High :mount_fuji:

#6531 workflows/publish.yml: Run the workflow on success and failure only.
  .github/scripts/sketch_utils.sh
  .github/workflows/hil.yml
  .github/workflows/publish.yml
Labels: hil_test

#6617 LittleFS Platformio example update
  libraries/LittleFS/examples/LITTLEFS_PlatformIO/platformio.ini
Labels: IDE: PlaformIO, Type: Example

#6609 Touch change to init only selected GPIO.
  cores/esp32/esp32-hal-touch.c
Labels: Area: Peripherals API

#6380 Allow BluetoothSerial::connect() with specified channel and more options
  libraries/BluetoothSerial/examples/DiscoverConnect/.skip.esp32c3
  libraries/BluetoothSerial/examples/DiscoverConnect/.skip.esp32s2
  libraries/BluetoothSerial/examples/DiscoverConnect/.skip.esp32s3
  libraries/BluetoothSerial/examples/DiscoverConnect/DiscoverConnect.ino
  libraries/BluetoothSerial/src/BTAddress.cpp
  libraries/BluetoothSerial/src/BTAddress.h
  libraries/BluetoothSerial/src/BTAdvertisedDevice.h
  libraries/BluetoothSerial/src/BTAdvertisedDeviceSet.cpp
  libraries/BluetoothSerial/src/BluetoothSerial.cpp
  libraries/BluetoothSerial/src/BluetoothSerial.h
Labels: Status: Test needed, Area: BT&Wifi

#6537 Call i2c_set_timeout in i2cSetClock
  cores/esp32/esp32-hal-i2c.c
Labels: Area: Peripherals API

#5842 Add CI job which tries to build arduino-esp32 as a component
  .github/workflows/push.yml
Labels: Type: CI & Testing

#6629 [Docs] Actualize PlatformIO installation instructions
  docs/source/installing.rst
Labels: Type: Documentation, IDE: Arduino IDE

#6659 Fixes INADDR_NONE
  cores/esp32/IPAddress.cpp
  cores/esp32/IPAddress.h
  libraries/AsyncUDP/src/AsyncUDP.h
  libraries/WiFi/src/WiFiServer.h
  tools/sdk/esp32/include/wifi_provisioning/include/wifi_provisioning/wifi_config.h
  tools/sdk/esp32c3/include/wifi_provisioning/include/wifi_provisioning/wifi_config.h
  tools/sdk/esp32s2/include/wifi_provisioning/include/wifi_provisioning/wifi_config.h
  tools/sdk/esp32s3/include/wifi_provisioning/include/wifi_provisioning/wifi_config.h
Labels: Area: BT&Wifi
