Repository espressif/arduino-esp32, pull requests merged in 2022-05, with the labels that each got.

#6681 Properly handle ARDUINO_PARTITION define in PlatformIO
  tools/platformio-build-esp32.py
  tools/platformio-build-esp32c3.py
  tools/platformio-build-esp32s2.py
  tools/platformio-build-esp32s3.py
Labels: IDE: PlaformIO

#6688 Upload component to the registry on any tag
  .github/workflows/upload-idf-component.yml
Labels: Type: CI & Testing

#6707 Fixes DNS Server Memory Leak when deleted
  libraries/DNSServer/src/DNSServer.cpp
  libraries/DNSServer/src/DNSServer.h
Labels: Area: BT&Wifi

#6716 Fix TIMER timer_dev definition
  cores/esp32/esp32-hal-timer.c
Labels: Area: Peripherals API

#6695 Changed pinMode() default interrupt type DISABLED to previously set
  cores/esp32/esp32-hal-gpio.c
Labels: Area: Peripherals API

#6685 Adjustable Serial Event Task Stack Size And Priority
  Kconfig.projbuild
  cores/esp32/HardwareSerial.cpp
Labels: Area: Peripherals API

#6753 workflows/hil.yml: Don't run the scheduled HIL workflow on forks.
  .github/workflows/hil.yml
Labels: Type: CI & Testing

#6731 Adds DHCP Range Setup to APMode
  libraries/Ethernet/src/ETH.cpp
  libraries/WiFi/src/WiFiAP.cpp
  libraries/WiFi/src/WiFiAP.h
  libraries/WiFi/src/WiFiGeneric.cpp
  libraries/WiFi/src/WiFiSTA.cpp
Labels: Type: Feature request, Area: BT&Wifi

#6800 Update bootloaders with dont-append-digest
  tools/sdk/esp32/bin/bootloader_dio_40m.bin
  tools/sdk/esp32/bin/bootloader_dio_80m.bin
  tools/sdk/esp32/bin/bootloader_dout_40m.bin
  tools/sdk/esp32/bin/bootloader_dout_80m.bin
  tools/sdk/esp32/bin/bootloader_qio_40m.bin
  tools/sdk/esp32/bin/bootloader_qio_80m.bin
  tools/sdk/esp32/bin/bootloader_qout_40m.bin
  tools/sdk/esp32/bin/bootloader_qout_80m.bin
  tools/sdk/esp32c3/bin/bootloader_dio_40m.bin
  tools/sdk/esp32c3/bin/bootloader_dio_80m.bin
  tools/sdk/esp32c3/bin/bootloader_dout_40m.bin
  tools/sdk/esp32c3/bin/bootloader_dout_80m.bin
  tools/sdk/esp32c3/bin/bootloader_qio_40m.bin
  tools/sdk/esp32c3/bin/bootloader_qio_80m.bin
  tools/sdk/esp32c3/bin/bootloader_qout_40m.bin
  tools/sdk/esp32c3/bin/bootloader_qout_80m.bin
  tools/sdk/esp32s2/bin/bootloader_dio_40m.bin
  tools/sdk/esp32s2/bin/bootloader_dio_80m.bin
  tools/sdk/esp32s2/bin/bootloader_dout_40m.bin
  tools/sdk/esp32s2/bin/bootloader_dout_80m.bin
  tools/sdk/esp32s2/bin/bootloader_qio_40m.bin
  tools/sdk/esp32s2/bin/bootloader_qio_80m.bin
  tools/sdk/esp32s2/bin/bootloader_qout_40m.bin
  tools/sdk/esp32s2/bin/bootloader_qout_80m.bin
  tools/sdk/esp32s3/bin/bootloader_dio_80m.bin
  tools/sdk/esp32s3/bin/bootloader_opi_80m.bin
  tools/sdk/esp32s3/bin/bootloader_qio_120m.bin
  tools/sdk/esp32s3/bin/bootloader_qio_80m.bin
Labels: hil_test

#6812 adds verbose message for WPA3
  libraries/WiFi/src/WiFiGeneric.cpp
Labels: Area: BT&Wifi

#6671 Doc: WiFi library description: remove specific mention of wifi encryption.
  libraries/WiFi/library.properties
Labels: Type: Documentation

#6745 SD library: reduce stack size requirement by 4k by moving work buffer to heap
  libraries/SD/src/sd_diskio.cpp
Labels: Area: Libraries

#6763 Fix timerAttachInterrupt() and timerDetachInterrupt() in esp32-hal-timer.c
  cores/esp32/esp32-hal-timer.c
Labels: Area: Peripherals API, hil_test

#6771 workflows/upload-idf-component.yml: Fix the wildcard.
  .github/workflows/upload-idf-component.yml
Labels: Type: CI & Testing

#6798 Remove nonexisting folder from include path
  tools/platformio-build-esp32.py
  tools/platformio-build-esp32c3.py
  tools/platformio-build-esp32s2.py
  tools/platformio-build-esp32s3.py
Labels: IDE: PlaformIO

#6758 [DOCS] Added partition table tutorial
  docs/source/tutorials/partition_table.rst
  tools/partitions/bare_minimum_2MB.csv
Labels: Type: Documentation
