Repository espressif/arduino-esp32, pull requests merged in 2022-03, with the labels that each got.

#6367 FEATURE: Implemented new types of Wifi SmartConfig
  libraries/WiFi/src/WiFiSTA.cpp
  libraries/WiFi/src/WiFiSTA.h
Labels: Type: Feature request, Area: BT&Wifi

#6296 Fixes DHCP Server Lease Range for any AP Server Static IP Address
  libraries/WiFi/src/WiFiAP.cpp
  libraries/WiFi/src/WiFiGeneric.cpp
Labels: Area: BT&Wifi

#6313 Build (using arduino-builder) and run tests
  .github/scripts/on-push.sh
  .github/scripts/sketch_utils.sh
  .github/scripts/tests_build.sh
  .github/scripts/tests_run.sh
  .github/workflows/hil.yml
  .github/workflows/publish.yml
  .gitignore
  tests/.gitignore
  tests/hello_world/hello_world.ino
  tests/hello_world/test_hello_world.py
  tests/pytest.ini
  tests/requirements.txt
  tests/unity/test_unity.py
  tests/unity/unity.ino
Labels: hil_test

#6371 Fix ledc panic’ed when wrong setup of frequency and bit width
  cores/esp32/esp32-hal-ledc.c
  libraries/ESP32/examples/AnalogOut/LEDCSoftwareFade/LEDCSoftwareFade.ino
Labels: Type: Bug :bug:, Area: Peripherals API

#6392 Fixed the antenna GPIO argument on the DA example
  libraries/WiFi/examples/WiFiScanDualAntenna/WiFiScanDualAntenna.ino
Labels: Type: Bug :bug:

#6394 Allows setting only one pin (rx or tx) in the first begin()
  cores/esp32/HardwareSerial.cpp
Labels: Area: Peripherals API

#6402 Implemented tone and noTone; fixes #980
  CMakeLists.txt
  cores/esp32/Arduino.h
  cores/esp32/Tone.cpp
Labels: Type: Feature request

#6401 [Docs] Added/Updated Lib builder docs
  docs/source/lib_builder.rst
Labels: Type: Documentation

#6409 [Docs] Added the guideline for documentation
  docs/source/guides/docs_contributing.rst
Labels: Type: Documentation

#6383 Adds HardwareSerial::setTxBufferSize()
  cores/esp32/HardwareSerial.cpp
  cores/esp32/HardwareSerial.h
  cores/esp32/esp32-hal-uart.c
  cores/esp32/esp32-hal-uart.h
Labels: Type: To be implemented, Area: Peripherals API

#6413 Fixes USB CDC setRxBufferSize(), begin(), _onRX()
  cores/esp32/USBCDC.cpp
  cores/esp32/USBCDC.h
  docs/source/api/usb_cdc.rst
  libraries/USB/examples/CompositeDevice/CompositeDevice.ino
  libraries/USB/examples/USBSerial/USBSerial.ino
Labels: Type: Bug :bug:, Chip: ESP32-S2, Chip: ESP32-S3

#6455 Warns about SPP only available for ESP32
  libraries/BluetoothSerial/examples/SerialToSerialBT/SerialToSerialBT.ino
  libraries/BluetoothSerial/examples/SerialToSerialBTM/SerialToSerialBTM.ino
  libraries/BluetoothSerial/examples/SerialToSerialBT_SSP_pairing/SerialToSerialBT_SSP_pairing.ino
  libraries/BluetoothSerial/examples/bt_classic_device_discovery/bt_classic_device_discovery.ino
  libraries/BluetoothSerial/examples/bt_remove_paired_devices/bt_remove_paired_devices.ino
  libraries/README.md
Labels: Area: BT&Wifi, Type: Documentation

#6456 Edited VFSFileImpl::read to use both read/fread
  libraries/FS/src/vfs_api.cpp
Labels: Area: Performance, Area: Libraries

#6442 Add Preferences library API and tutorial documents
  docs/source/api/preferences.rst
  docs/source/tutorials/preferences.rst
Labels: Type: Documentation

#6397 Adds HardwareSerial::setRxTimeout()
  cores/esp32/HardwareSerial.cpp
  cores/esp32/HardwareSerial.h
Labels: Type: Feature request, Status: In Progress, Area: Peripherals API
