Repository espressif/arduino-esp32, pull requests merged in 2022-06, with the labels that each got.

#6825 [WiFiSTA] Remove duplicate setting of SSID and password.
  libraries/WiFi/src/WiFiSTA.cpp
Labels: Area: BT&Wifi

#6864 fixes BLE HID Battery Level Indicator
  libraries/BLE/src/BLEHIDDevice.cpp
Labels: Area: BT&Wifi

#6756 [DOCS] Added USB DFU and CDC tools guide
  docs/source/tutorials/cdc_dfu_flash.rst
  docs/source/tutorials/dfu.rst
  docs/source/tutorials/io_mux.rst
Labels: Type: Documentation, Status: Pending Merge

#6903 Fixes reading BLE Remote Descriptor
  libraries/BLE/src/BLERemoteDescriptor.cpp
Labels: Area: BT&Wifi

#6902 fixes BLE and WiFi Debug log messages
  libraries/BLE/src/BLEUtils.cpp
  libraries/BLE/src/GeneralUtils.cpp
Labels: Area: BT&Wifi, IDE: Arduino IDE

#6844 WireMaster example clarity
  libraries/Wire/examples/WireMaster/WireMaster.ino
Labels: Type: Example

#6919 Fixes BLE Server descriptor update
  libraries/BLE/src/BLE2902.cpp
  libraries/BLE/src/BLEDescriptor.cpp
  libraries/BLE/src/BLEDescriptor.h
Labels: Area: BT&Wifi

#6909 Doc: Add doc about minimum security for connection to AP
  docs/source/api/wifi.rst
  docs/source/troubleshooting.rst
  libraries/WiFi/src/WiFiSTA.cpp
Labels: Type: Documentation
