Repository espressif/arduino-esp32, pull requests merged in 2022-09, with the labels that each got.

#7200 Update PlatformIO build scripts
  tools/platformio-build.py
Labels: IDE: PlaformIO

#7199 itsy bitsy esp32 board working :)
  boards.txt
  variants/adafruit_itsybitsy_esp32/pins_arduino.h
  variants/adafruit_itsybitsy_esp32/variant.cpp
Labels: Type: 3rd party Boards

#7217 add TAMC Termod S3 board variant
  boards.txt
  variants/tamc_termod_s3/pins_arduino.h
  variants/tamc_termod_s3/variant.cpp
Labels: Type: 3rd party Boards

#7208 [NORA-W1] Fix SPI pin assignments to match Arduino pinout.
  variants/nora_w10/pins_arduino.h
Labels: Type: 3rd party Boards

#7161 Add default SPI pin definitions if not defined in pins_arduino.h
  variants/d32_pro/pins_arduino.h
  variants/metro_esp-32/pins_arduino.h
  variants/wt32-eth01/pins_arduino.h
Labels: Area: Libraries

#7221 Add new ULP example for ESP32
  libraries/ESP32/examples/DeepSleep/SmoothBlink_ULP_Code/.skip.esp32c3
  libraries/ESP32/examples/DeepSleep/SmoothBlink_ULP_Code/.skip.esp32s2
  libraries/ESP32/examples/DeepSleep/SmoothBlink_ULP_Code/.skip.esp32s3
  libraries/ESP32/examples/DeepSleep/SmoothBlink_ULP_Code/SmoothBlink_ULP_Code.ino
Labels: Type: Example

#7247 add boards WiFiduinoV2&WiFiduino32S3
  boards.txt
  variants/wifiduino32s3/pins_arduino.h
  variants/wifiduinov2/pins_arduino.h
Labels: Type: 3rd party Boards

#7193 Doc addition: How to compile libs with different debug level
  docs/source/faq.rst
  docs/source/guides/core_debug.rst
Labels: Type: Documentation

#7195 Update boards.rst
  docs/source/boards/boards.rst
Labels: Type: Documentation

#6930 Changes UART ISR to only trigger on RX FIFO Full and timeout
  cores/esp32/HardwareSerial.cpp
  cores/esp32/HardwareSerial.h
  cores/esp32/esp32-hal-uart.c
  cores/esp32/esp32-hal-uart.h
Labels: Area: Peripherals API, Peripheral: UART

#7277 Doc update: added note about global arduino component
  docs/source/esp-idf_component.rst
Labels: Type: Documentation

#7315 Add v2.0.5 into Issue Template
  .github/ISSUE_TEMPLATE/Issue-report.yml
Labels: Type: Documentation, Status: Pending Merge
