Repository espressif/arduino-esp32, pull requests merged in 2022-01, with the labels that each got.

#6103 BUGFIX - Sd check status
  libraries/SD/src/sd_diskio.cpp
Labels: Type: Bug :bug:

#6096 Versions and feature Request Template updates
  .github/ISSUE_TEMPLATE/Feature-request.yml
  .github/ISSUE_TEMPLATE/Issue-report.yml
Labels: Type: Documentation

#6132 ci: Miscellaneous improvements
  .github/scripts/install-arduino-core-esp32.sh
  .github/workflows/push.yml
Labels: Type: CI & Testing

#6202 Fixes UART1 and UART2 default pins for ESP32-S3
  cores/esp32/HardwareSerial.cpp
Labels: Chip: ESP32-S3

#6201 Fixes onReceive deadlock
  cores/esp32/esp32-hal-uart.c
Labels: Type: Bug :bug:

#6204 added explanatory comments to WebServer.h
  libraries/WebServer/src/WebServer.h
Labels: Status: Awaiting triage

#6191 Refactor the CI scripts
  .github/scripts/install-arduino-ide.sh
  .github/scripts/on-push.sh
  .github/scripts/sketch_utils.sh
  .github/workflows/push.yml
Labels: Type: CI & Testing
