Repository espressif/arduino-esp32, pull requests merged in 2023-10, with the labels that each got.

#8695 Update of "Arduino Style Guide" link on contributing.rst
  docs/source/contributing.rst
Labels: Type: Documentation, Status: Pending Merge

#8691 Fix BTAdvertisedDeviceSet::toString() method output
  libraries/BluetoothSerial/src/BTAdvertisedDeviceSet.cpp
Labels: Status: Pending Merge

#8659 Corrected pins_arduino.h for Lolin_s3
  variants/lolin_s3/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#8646 Add IOXESP32 board family and ATD1.47-S3 board
  boards.txt
  variants/atd147_s3/pins_arduino.h
  variants/ioxesp32/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#8639 Fix Markdown table format error in SD_MMC's documentation
  libraries/SD_MMC/README.md
Labels: Type: Documentation, Status: Pending Merge

#8640 Fix Mardown table format error in SD library
  libraries/SD/README.md
Labels: Status: Pending Merge

#8606 Documentation - Update supported IDEs and general improvements
  docs/source/installing.rst
  docs/source/ota_web_update.rst
Labels: Type: Documentation, Status: Pending Merge

#8630 HTTPClient - Fix case sensitiveness for header keys
  libraries/HTTPClient/src/HTTPClient.cpp
Labels: Status: Pending Merge

#8644 Fixes set pins return value in 2.0.13
  cores/esp32/esp32-hal-uart.c
Labels: Status: Pending Merge, Peripheral: UART

#8727 Update README.md to add new SoCs
  README.md
Labels: Status: Pending Merge

#8719 3.0.0 - UART Peripheral Manager + Detach UART pins on begin()/setPins()
  cores/esp32/HardwareSerial.cpp
  cores/esp32/HardwareSerial.h
  cores/esp32/chip-debug-report.cpp
  cores/esp32/esp32-hal-periman.h
  cores/esp32/esp32-hal-uart.c
  cores/esp32/esp32-hal-uart.h
Labels: Status: Pending Merge, Peripheral: UART

#8718 Serial reorganization code for RS-485 Mode, Flow Control Mode and Serial Mode
  cores/esp32/HardwareSerial.cpp
  cores/esp32/HardwareSerial.h
  cores/esp32/esp32-hal-uart.c
  cores/esp32/esp32-hal-uart.h
Labels: Status: Pending Merge, Peripheral: UART

#8715 Analog Continuous mode API
  cores/esp32/esp32-hal-adc.c
  cores/esp32/esp32-hal-adc.h
  docs/source/api/adc.rst
  libraries/ESP32/examples/AnalogReadContinuous/AnalogReadContinuous.ino
Labels: Area: Peripherals API, Status: Pending Merge

#8671 Fix memory leak and undefined behavour in Updater.cpp (UpdaterClass)
  libraries/Update/src/Updater.cpp
Labels: Area: Performance, Status: Pending Merge

#8441 Update of documentation link on readme.md for WifiClientSecure
  libraries/WiFiClientSecure/README.md
Labels: Type: Documentation, Status: Pending Merge

#8721 Add Arduino lib to arduino as IDF component
  docs/source/esp-idf_component.rst
  tools/add_lib.sh
Labels: Type: Documentation

#8744 Fixed bug for LilyGo T-display on boards.txt
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#8762 HardwareSerial::end(bool) review + Baud Rate detection review and example
  cores/esp32/HardwareSerial.cpp
  cores/esp32/esp32-hal-uart.c
  libraries/ESP32/examples/Serial/BaudRateDetect_Demo/BaudRateDetect_Demo.ino
Labels: Type: Example, Peripheral: UART

#8759 Fixes BLEScanResults to be used by reference
  libraries/BLE/examples/Beacon_Scanner/Beacon_Scanner.ino
  libraries/BLE/examples/Scan/Scan.ino
  libraries/BLE/src/BLEScan.cpp
  libraries/BLE/src/BLEScan.h
Labels: Area: BLE

#8716 [Docs] Add Migration guide + some API updates
  docs/source/api/ble.rst
  docs/source/api/ledc.rst
  docs/source/api/sigmadelta.rst
  docs/source/api/timer.rst
  docs/source/index.rst
  docs/source/migration_guides/2.x_to_3.0.rst
  docs/source/migration_guides/migration_guides.rst
Labels: Type: Documentation

#8714 [I2S][SR] Add new I2S library and Sound Recognition support
  .github/workflows/push.yml
  CMakeLists.txt
  libraries/ESP32/examples/I2S/HiFreq_ADC/.skip.esp32c3
  libraries/ESP32/examples/I2S/HiFreq_ADC/.skip.esp32c6
  libraries/ESP32/examples/I2S/HiFreq_ADC/.skip.esp32h2
  libraries/ESP32/examples/I2S/HiFreq_ADC/.skip.esp32s2
  libraries/ESP32/examples/I2S/HiFreq_ADC/.skip.esp32s3
  libraries/ESP32/examples/I2S/HiFreq_ADC/HiFreq_ADC.ino
  libraries/ESP_I2S/keywords.txt
  libraries/ESP_I2S/library.properties
  libraries/ESP_I2S/src/ESP_I2S.cpp
  libraries/ESP_I2S/src/ESP_I2S.h
  libraries/ESP_I2S/src/wav_header.h
  libraries/ESP_SR/examples/Basic/.skip.esp32
  libraries/ESP_SR/examples/Basic/.skip.esp32c3
  libraries/ESP_SR/examples/Basic/.skip.esp32c6
  libraries/ESP_SR/examples/Basic/.skip.esp32h2
  libraries/ESP_SR/examples/Basic/.skip.esp32s2
  libraries/ESP_SR/examples/Basic/Basic.ino
  libraries/ESP_SR/keywords.txt
  libraries/ESP_SR/library.properties
  libraries/ESP_SR/src/ESP_SR.cpp
  libraries/ESP_SR/src/ESP_SR.h
  libraries/ESP_SR/src/esp32-hal-sr.c
  libraries/ESP_SR/src/esp32-hal-sr.h
  libraries/ESP_SR/tools/gen_sr_commands.py
  libraries/I2S/examples/ADCPlotter/ADCPlotter.ino
  libraries/I2S/examples/FullDuplex/.skip.esp32h2
  libraries/I2S/examples/FullDuplex/FullDuplex.ino
  libraries/I2S/examples/InputSerialPlotter/.skip.esp32c3
  libraries/I2S/examples/InputSerialPlotter/.skip.esp32c6
  libraries/I2S/examples/InputSerialPlotter/.skip.esp32h2
  libraries/I2S/examples/InputSerialPlotter/InputSerialPlotter.ino
  libraries/I2S/examples/SimpleTone/.skip.esp32c3
  libraries/I2S/examples/SimpleTone/.skip.esp32c6
  libraries/I2S/examples/SimpleTone/.skip.esp32h2
  libraries/I2S/examples/SimpleTone/SimpleTone.ino
  libraries/I2S/keywords.txt
  libraries/I2S/library.properties
  libraries/I2S/src/I2S.cpp
  libraries/I2S/src/I2S.h
Labels: Area: Peripherals API

#8785 Removed YML file and changed the YAML file structure
  .readthedocs.yaml
  .readthedocs.yml
Labels: Type: Documentation

#8782 I2S fix missing perimanSetBusDeinit()
  cores/esp32/chip-debug-report.cpp
  cores/esp32/esp32-hal-periman.h
  libraries/ESP_I2S/src/ESP_I2S.cpp
Labels: Area: Peripherals API

#8794 [Docs] Fixed the RTD theme and core version
  docs/requirements.txt
  docs/source/conf.py
Labels: Type: Documentation

#8799 [Docs] Add ESP32C6 + ESP32H2
  docs/source/common/datasheet.inc
  docs/source/getting_started.rst
Labels: Type: Documentation

#8778 Add new uPesy boards as variant
  boards.txt
  variants/uPesy_edu_esp32/pins_arduino.h
  variants/uPesy_esp32c3_basic/pins_arduino.h
  variants/uPesy_esp32c3_mini/pins_arduino.h
  variants/uPesy_esp32s3_basic/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#8793 Add the DFRobot Beetle ESP32C6 and the DFRobot FireBeetle2 ESP32C6 as two development boards
  boards.txt
  variants/dfrobot_beetle_esp32c6/pins_arduino.h
  variants/dfrobot_firebeetle2_esp32c6/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#8660 Added entry for octal flash S3
  boards.txt
Labels: Status: Pending Merge

#8798 Serial as a #define
  cores/esp32/HWCDC.cpp
  cores/esp32/HWCDC.h
  cores/esp32/HardwareSerial.cpp
  cores/esp32/HardwareSerial.h
  cores/esp32/USBCDC.cpp
  cores/esp32/USBCDC.h
  libraries/ESP32/examples/Serial/Serial_STD_Func_OnReceive/Serial_STD_Func_OnReceive.ino
  libraries/USB/examples/CompositeDevice/CompositeDevice.ino
  libraries/USB/examples/ConsumerControl/ConsumerControl.ino
  libraries/USB/examples/CustomHIDDevice/CustomHIDDevice.ino
  libraries/USB/examples/FirmwareMSC/FirmwareMSC.ino
  libraries/USB/examples/Gamepad/Gamepad.ino
  libraries/USB/examples/HIDVendor/HIDVendor.ino
  libraries/USB/examples/Keyboard/KeyboardLogout/KeyboardLogout.ino
  libraries/USB/examples/Keyboard/KeyboardMessage/KeyboardMessage.ino
  libraries/USB/examples/Keyboard/KeyboardReprogram/KeyboardReprogram.ino
  libraries/USB/examples/Keyboard/KeyboardSerial/KeyboardSerial.ino
  libraries/USB/examples/KeyboardAndMouseControl/KeyboardAndMouseControl.ino
  libraries/USB/examples/Mouse/ButtonMouseControl/ButtonMouseControl.ino
  libraries/USB/examples/SystemControl/SystemControl.ino
  libraries/USB/examples/USBMSC/USBMSC.ino
  libraries/USB/examples/USBSerial/USBSerial.ino
  libraries/USB/examples/USBVendor/USBVendor.ino
Labels: Peripheral: UART

#8800 UART: Change default Serial1/2 pins and move definition to header
  cores/esp32/HardwareSerial.cpp
  cores/esp32/HardwareSerial.h
Labels: Peripheral: UART

#8805 Remove unsupported DOUT and QOUT options
  boards.txt
  tests/democfg/cfg.json
  tests/nvs/cfg.json
Labels: Type: Chip support, Type: CI & Testing, hil_test, Status: Pending Merge, Type: 3rd party Boards

#8806 BluetoothSerial: Fix SPP service mode
  libraries/BluetoothSerial/src/BluetoothSerial.cpp
Labels: Area: BT&Wifi

#8801 CI: Add UART test
  cores/esp32/esp32-hal-uart.c
  tests/uart/test_uart.py
  tests/uart/uart.ino
Labels: Type: CI & Testing, hil_test, Peripheral: UART

#8813 RMT: Fix RMT TX interrupt level
  cores/esp32/esp32-hal-rmt.c
Labels: Type: Bug :bug:, Area: Peripherals API, Status: Pending Merge
