Repository espressif/arduino-esp32, pull requests merged in 2023-05, with the labels that each got.

#8145 Add MFRC522 and WS2812FX library to External library testing
  .github/workflows/lib.json
Labels: Type: CI & Testing, lib_test

#8137 Fixes analogWrite
  cores/esp32/esp32-hal-ledc.c
Labels: Area: Peripherals API

#8146 External library test - Example change for WS2812FX lib
  .github/workflows/lib.json
Labels: Type: CI & Testing, lib_test

#8149 Fix CameraWebserver.ino CI Warning
  libraries/ESP32/examples/Camera/CameraWebServer/CameraWebServer.ino
Labels: Type: Example

#8114 CI - All boards test
  .github/scripts/find_all_boards.sh
  .github/workflows/allboards.yml
Labels: Type: CI & Testing

#8111 Add overloads to support __FlashStringHelper like ESP8266 has them.
  cores/esp32/WString.h
  libraries/ESPmDNS/src/ESPmDNS.cpp
  libraries/ESPmDNS/src/ESPmDNS.h
  libraries/WiFi/src/WiFiSTA.h
Labels: Priority: High :mount_fuji:, lib_test

#8180 DAC - Added missing deinit of previous bus
  cores/esp32/esp32-hal-dac.c
Labels: Area: Peripherals API

#8135 TIMER - add timer_started flag, fix timerEnd() + timer HW test
  cores/esp32/esp32-hal-timer.c
  tests/timer/timer.ino
Labels: Area: Peripherals API, hil_test

#8129 TOUCH - Peripheral manager implementation
  cores/esp32/esp32-hal-periman.h
  cores/esp32/esp32-hal-touch.c
Labels: Area: Peripherals API, hil_test

#8126 LEDC Refactoring - Peripheral manager implemented
  cores/esp32/Tone.cpp
  cores/esp32/esp32-hal-ledc.c
  cores/esp32/esp32-hal-ledc.h
  cores/esp32/esp32-hal.h
  docs/source/api/ledc.rst
  libraries/ESP32/examples/AnalogOut/LEDCSoftwareFade/LEDCSoftwareFade.ino
  libraries/ESP32/examples/AnalogOut/ledcFrequency/ledcFrequency.ino
  libraries/ESP32/examples/AnalogOut/ledcWrite_RGB/ledcWrite_RGB.ino
  libraries/ESP32/examples/Camera/CameraWebServer/app_httpd.cpp
  libraries/ESP32/examples/I2S/HiFreq_ADC/HiFreq_ADC.ino
Labels: Area: Peripherals API, Status: Review needed

#8182 HardwareSerial: fix begin() lock issue on error path
  cores/esp32/HardwareSerial.cpp
Labels: Peripheral: UART

#7994 [Arduino Core 3.0.0] RMT IDF5.1 Refactoring
  cores/esp32/esp32-hal-rgb-led.c
  cores/esp32/esp32-hal-rmt.c
  cores/esp32/esp32-hal-rmt.h
  libraries/ESP32/examples/RMT/RMTCallback/RMTCallback.ino
  libraries/ESP32/examples/RMT/RMTLoopback/RMTLoopback.ino
  libraries/ESP32/examples/RMT/RMTReadXJT/RMTReadXJT.ino
  libraries/ESP32/examples/RMT/RMTWriteNeoPixel/RMTWriteNeoPixel.ino
  libraries/ESP32/examples/RMT/RMT_CPUFreq_Test/RMT_CPUFreq_Test.ino
  libraries/ESP32/examples/RMT/RMT_LED_Blink/RMT_LED_Blink.ino
Labels: Area: Peripherals API

#8183 Update PlatformIO scripts for the upcoming 3.0 core
  .github/scripts/install-platformio-esp32.sh
  .github/workflows/push.yml
  tools/platformio-build.py
Labels: IDE: PlaformIO

#8264 LEDC - Memory fix
  cores/esp32/esp32-hal-ledc.c
Labels: Type: Bug :bug:, Area: Peripherals API

#8243 fixes ESP32-C3 WiFiProv and btInUse()
  cores/esp32/esp32-hal-bt.c
  cores/esp32/esp32-hal-misc.c
Labels: Area: BT&Wifi

#8195 I have added support for the DFRobot Romeo ESP32-S3 board.
  boards.txt
  libraries/ESP32/examples/Camera/CameraWebServer/CameraWebServer.ino
  libraries/ESP32/examples/Camera/CameraWebServer/camera_pins.h
  variants/dfrobot_romeo_esp32s3/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#8230 Add board: Adafruit MatrixPortal ESP32-S3
  boards.txt
  variants/adafruit_matrixportal_esp32s3/bootloader-tinyuf2.bin
  variants/adafruit_matrixportal_esp32s3/partitions-8MB-tinyuf2.csv
  variants/adafruit_matrixportal_esp32s3/pins_arduino.h
  variants/adafruit_matrixportal_esp32s3/tinyuf2.bin
Labels: Status: Pending Merge, Type: 3rd party Boards

#8257 Add board: Nebula S3
  boards.txt
  variants/Nebula_S3/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#8249 rainmaker: multiple device callbacks not getting registered
  libraries/RainMaker/src/RMakerDevice.cpp
  libraries/RainMaker/src/RMakerDevice.h
Labels: Area: Rainmaker

#8255 SPI - Peripheral manager implementation
  cores/esp32/esp32-hal-spi.c
  cores/esp32/esp32-hal-spi.h
  libraries/SPI/src/SPI.cpp
Labels: Area: Peripherals API

#8218 Update ledc.rst
  docs/source/api/ledc.rst
Labels: Type: Documentation, Status: Pending Merge

#8220 I2C - Peripheral manager implementation
  cores/esp32/esp32-hal-i2c-slave.c
  cores/esp32/esp32-hal-i2c.c
Labels: Area: Peripherals API
