Repository espressif/arduino-esp32, pull requests merged in 2023-09, with the labels that each got.

#8592 GPIO - make pin mode output_open_drain state readable
  cores/esp32/esp32-hal-gpio.h
Labels: Area: Peripherals API

#8594 [CI] Fix allboards.yml workflow to use selected branch
  .github/workflows/allboards.yml
Labels: Type: CI & Testing

#8608 lilygo-t-display : rename pins_arduino.h.txt to pins_arduino.h
  variants/lilygo_t_display/pins_arduino.h
Labels: Type: 3rd party Boards

#8634 removes delay(10) from HardwareSerial::end()
  cores/esp32/HardwareSerial.cpp
Labels: Peripheral: UART

#8276 M5CoreS3 board and partitions update
  boards.txt
  variants/m5stack_cores3/partitions_16MB_factory_4_apps.csv
  variants/m5stack_cores3/partitions_16MB_factory_6_apps.csv
Labels: Resolution: Awaiting response, Type: 3rd party Boards
