Repository espressif/arduino-esp32, pull requests merged in 2023-11, with the labels that each got.

#8812 PeriMan: Improve log messages
  cores/esp32/chip-debug-report.cpp
  cores/esp32/esp32-hal-periman.c
  cores/esp32/esp32-hal-periman.h
Labels: Area: Peripherals API

#8820 Fixes uart attach/detach
  cores/esp32/HardwareSerial.cpp
  cores/esp32/esp32-hal-uart.c
  cores/esp32/main.cpp
Labels: Type: Bug :bug:, Peripheral: UART

#8852 Fix of Readme
  README.md
Labels: Type: Documentation

#8842 Fixes Rainmaker to be a Managed Component
  CMakeLists.txt
  idf_component.yml
  libraries/RainMaker/src/RMakerQR.cpp
Labels: 3.0 migration

#8844 Zigbee protocol support
  boards.txt
  idf_component.yml
  platform.txt
  tools/partitions/zigbee.csv
  tools/partitions/zigbee_zczr.csv
Labels: Type: Feature request, Area: Libraries

#8845 Neopixel fix
  cores/esp32/esp32-hal-rgb-led.c
  libraries/ESP32/examples/RMT/RMTWriteNeoPixel/RMTWriteNeoPixel.ino
  libraries/ESP32/examples/RMT/RMT_CPUFreq_Test/RMT_CPUFreq_Test.ino
Labels: Area: Peripherals API, Status: Pending Merge

#8859 Increase BT SPP task priority
  libraries/BluetoothSerial/src/BluetoothSerial.cpp
Labels: Area: BT&Wifi

#8839 Update/upgrade OTAWebUpdater.ino example
  libraries/ArduinoOTA/examples/OTAWebUpdater/OTAWebUpdater.ino
  libraries/Update/examples/OTAWebUpdater/.skip.esp32h2
  libraries/Update/examples/OTAWebUpdater/OTAWebUpdater.ino
  libraries/Update/examples/OTAWebUpdater/html.h
Labels: Type: Example, Status: Review needed

#8868 Makes MP3 header files public for I2S code
  idf_component.yml
Labels: Status: Pending Merge

#8851 Update boards.rst
  docs/source/boards/boards.rst
Labels: Type: Documentation, Status: Pending Merge

#8814 Add new UM TinyC6 board and re-ordered UM boards in boards.txt file.
  boards.txt
  variants/um_tinyc6/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#8848 WiFiSTA - allow using DHCP again after disconnecting static IP
  libraries/WiFi/src/WiFiSTA.cpp
Labels: Area: BT&Wifi

#8866 Update warning note about PlatformIO related issues
  docs/source/installing.rst
Labels: Type: Documentation, IDE: PlaformIO

#8864 Add platform specific flash speed to magicFlashChipSpeed
  cores/esp32/Esp.cpp
Labels: 3.0 migration

#8886 Rename variants/heltec_wifi_kit_32_V3 to match entry in boards.txt.
  variants/heltec_wifi_kit_32_V3/pins_arduino.h
Labels: Status: Pending Merge

#8833 Added arduino uno backward compatibility pins
  variants/doitESPduino32/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#8840 Added troubleshooting doc for USB-CDC
  docs/source/troubleshooting.rst
Labels: Type: Documentation, Status: Review needed

#8881 Add ESP32-C2 support
  .github/workflows/push.yml
  boards.txt
  cores/esp32/Esp.cpp
  cores/esp32/HardwareSerial.h
  cores/esp32/esp32-hal-adc.c
  cores/esp32/esp32-hal-cpu.c
  cores/esp32/esp32-hal-i2c-slave.c
  cores/esp32/esp32-hal-matrix.c
  cores/esp32/esp32-hal-misc.c
  cores/esp32/esp32-hal-rgb-led.c
  cores/esp32/esp32-hal-spi.c
  cores/esp32/esp32-hal-spi.h
  idf_component.yml
  libraries/ESP32/examples/ResetReason/ResetReason.ino
  libraries/SPI/src/SPI.cpp
  platform.txt
  variants/esp32c2/pins_arduino.h
Labels: Type: Chip support, Status: Pending Merge

#8897 Update Adafruit boards
  boards.txt
  variants/adafruit_camera_esp32s3/partitions-4MB-1ota.csv
  variants/adafruit_feather_esp32s2/partitions-4MB-tinyuf2.csv
  variants/adafruit_feather_esp32s2_reversetft/partitions-4MB-tinyuf2.csv
  variants/adafruit_feather_esp32s2_tft/partitions-4MB-tinyuf2.csv
  variants/adafruit_feather_esp32s3/partitions-4MB-tinyuf2.csv
  variants/adafruit_feather_esp32s3_nopsram/partitions-8MB-tinyuf2.csv
  variants/adafruit_feather_esp32s3_reversetft/partitions-4MB-tinyuf2.csv
  variants/adafruit_feather_esp32s3_tft/partitions-4MB-tinyuf2.csv
  variants/adafruit_funhouse_esp32s2/partitions-4MB-tinyuf2.csv
  variants/adafruit_magtag29_esp32s2/partitions-4MB-tinyuf2.csv
  variants/adafruit_matrixportal_esp32s3/partitions-8MB-tinyuf2.csv
  variants/adafruit_metro_esp32s2/partitions-4MB-tinyuf2.csv
  variants/adafruit_metro_esp32s3/partitions-16MB-tinyuf2.csv
  variants/adafruit_qtpy_esp32s2/partitions-4MB-tinyuf2.csv
  variants/adafruit_qtpy_esp32s3_n4r2/partitions-4MB-tinyuf2.csv
  variants/adafruit_qtpy_esp32s3_nopsram/partitions-8MB-tinyuf2.csv
  variants/adafruit_qualia_s3_rgb666/partitions-16MB-tinyuf2.csv
Labels: Status: Pending Merge, Type: 3rd party Boards

#8889 Add support for ESP32-S3 PowerFeather
  boards.txt
  variants/esp32s3_powerfeather/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#8896 Adds support for missing Olimex boards
  boards.txt
  variants/esp32c3-devkit-lipo/pins_arduino.h
  variants/esp32c6-evb/pins_arduino.h
  variants/esp32s2-devkit-lipo-usb/pins_arduino.h
  variants/esp32s2-devkit-lipo/pins_arduino.h
  variants/esp32s3-devkit-lipo/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#8891 Add senseBox MCU-S2 with ESP32S2
  boards.txt
  variants/sensebox_mcu_esp32s2/bootloader-tinyuf2.bin
  variants/sensebox_mcu_esp32s2/partitions-4MB-tinyuf2.csv
  variants/sensebox_mcu_esp32s2/pins_arduino.h
  variants/sensebox_mcu_esp32s2/tinyuf2.bin
  variants/sensebox_mcu_esp32s2/variant.cpp
Labels: Status: Pending Merge, Type: 3rd party Boards

#8915 Added the Google Analytics ID in the configuration file
  docs/source/conf.py
Labels: Type: Documentation

#8888 Extend bus types and structure for Peripheral Manager
  cores/esp32/Arduino.h
  cores/esp32/HWCDC.cpp
  cores/esp32/chip-debug-report.cpp
  cores/esp32/esp32-hal-adc.c
  cores/esp32/esp32-hal-dac.c
  cores/esp32/esp32-hal-gpio.c
  cores/esp32/esp32-hal-i2c-slave.c
  cores/esp32/esp32-hal-i2c.c
  cores/esp32/esp32-hal-ledc.c
  cores/esp32/esp32-hal-periman.c
  cores/esp32/esp32-hal-periman.h
  cores/esp32/esp32-hal-rmt.c
  cores/esp32/esp32-hal-sigmadelta.c
  cores/esp32/esp32-hal-spi.c
  cores/esp32/esp32-hal-tinyusb.c
  cores/esp32/esp32-hal-touch.c
  cores/esp32/esp32-hal-uart.c
  cores/esp32/extra_attr.h
  libraries/ESP_I2S/src/ESP_I2S.cpp
  libraries/Ethernet/src/ETH.cpp
  libraries/SD/src/sd_diskio.cpp
  libraries/SD_MMC/src/SD_MMC.cpp
Labels: Status: Pending Merge

#8860 WiFiServer - deprecate available(), use accept() everywhere
  libraries/ESPmDNS/examples/mDNS_Web_Server/mDNS_Web_Server.ino
  libraries/WebServer/src/WebServer.cpp
  libraries/WiFi/examples/SimpleWiFiServer/SimpleWiFiServer.ino
  libraries/WiFi/examples/WiFiAccessPoint/WiFiAccessPoint.ino
  libraries/WiFi/examples/WiFiTelnetToSerial/WiFiTelnetToSerial.ino
  libraries/WiFi/src/WiFiServer.cpp
  libraries/WiFi/src/WiFiServer.h
Labels: Area: BT&Wifi, Status: Pending Merge

#7619 Added WiFi Bandwidth Setting Methods for AP and STA modes.
  libraries/WiFi/src/WiFiAP.cpp
  libraries/WiFi/src/WiFiAP.h
  libraries/WiFi/src/WiFiGeneric.cpp
  libraries/WiFi/src/WiFiSTA.cpp
  libraries/WiFi/src/WiFiSTA.h
Labels: Status: Review needed, Area: WiFi

#7807 Add missing function getSocketOption
  libraries/WiFi/src/WiFiClient.cpp
  libraries/WiFi/src/WiFiClient.h
Labels: Status: Review needed, Area: WiFi

#8127 Add lock in Wire.cpp to protect concurrent i2c transactions performed by different tasks
  libraries/Wire/src/Wire.cpp
  libraries/Wire/src/Wire.h
Labels: Status: Awaiting triage, Area: Peripherals API

#8927 Update RMT initialization code
  cores/esp32/esp32-hal-rmt.c
Labels: Status: Pending Merge

#8878 Add Arduino as Component examples
  idf_component.yml
  idf_component_examples/Hello_world/CMakeLists.txt
  idf_component_examples/Hello_world/README.md
  idf_component_examples/Hello_world/main/CMakeLists.txt
  idf_component_examples/Hello_world/main/idf_component.yml
  idf_component_examples/Hello_world/main/main.cpp
  idf_component_examples/Hello_world/sdkconfig.defaults
Labels: Type: Example, Status: Pending Merge, Area: Arduino as ESP-IDF component

#8622 Support relative paths in UNIX search PATH
  .github/scripts/on-push.sh
  platform.txt
Labels: Status: Pending Merge

#8618 Added example 'get mac address'
  libraries/ESP32/examples/MacAddress/GetMacAddress/GetMacAddress.ino
  libraries/README.md
Labels: Type: Example, Status: Pending Merge

#8051 Bluetooth-classic: release BLE memory when BT classic only is requested
  cores/esp32/esp32-hal-bt.c
  cores/esp32/esp32-hal-bt.h
  libraries/BluetoothSerial/src/BluetoothSerial.cpp
  libraries/BluetoothSerial/src/BluetoothSerial.h
Labels: Status: Pending Merge, Area: BLE

#8831 Absolute mouse support (was #6331)
  libraries/USB/src/USBHIDMouse.cpp
  libraries/USB/src/USBHIDMouse.h
  libraries/USB/src/tusb_hid_mouse.h
Labels: Status: Pending Merge

#8747 Added methods to remove service UUID from BLEAdvertising
  libraries/BLE/src/BLEAdvertising.cpp
  libraries/BLE/src/BLEAdvertising.h
Labels: Status: Review needed

#8936 Add support for I2S Slot Mask
  libraries/ESP_I2S/src/ESP_I2S.cpp
  libraries/ESP_I2S/src/ESP_I2S.h
Labels: Area: Peripherals API, Status: Pending Merge

#8937 Set M5Stack Core2 Flash Mode to QIO
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#8938 Support relative paths in UNIX search PATH
  platform.txt
Labels: Status: Pending Merge

#7629 feat: adding possibility to manually set MD5 checksum and authorization for HTTP update
  libraries/HTTPUpdate/src/HTTPUpdate.cpp
  libraries/HTTPUpdate/src/HTTPUpdate.h
Labels: Area: Libraries

#8010 Kernel panic when delete BLEClient object with descriptor characteristic
  libraries/BLE/src/BLERemoteCharacteristic.cpp
Labels: Status: Pending Merge, Area: BLE

#7687 Supporting ETag http headers on static files
  libraries/WebServer/examples/WebServer/.skip.esp32h2
  libraries/WebServer/examples/WebServer/README.md
  libraries/WebServer/examples/WebServer/WebServer.ino
  libraries/WebServer/examples/WebServer/builtinfiles.h
  libraries/WebServer/examples/WebServer/data/files.htm
  libraries/WebServer/examples/WebServer/data/index.htm
  libraries/WebServer/examples/WebServer/data/style.css
  libraries/WebServer/examples/WebServer/secrets.h
  libraries/WebServer/src/WebServer.cpp
  libraries/WebServer/src/WebServer.h
  libraries/WebServer/src/detail/RequestHandlersImpl.h
Labels: Area: Libraries, Type: Example, Status: Review needed

#6964 Make USBHIDKeyboard work at boot
  cores/esp32/esp32-hal-tinyusb.c
  cores/esp32/esp32-hal-tinyusb.h
  libraries/USB/src/USBHID.cpp
  libraries/USB/src/USBHID.h
  libraries/USB/src/USBHIDKeyboard.cpp
  libraries/USB/src/USBHIDKeyboard.h
Labels: Status: To be implemented, Status: Pending Merge
