Repository espressif/arduino-esp32, pull requests merged in 2024-10, with the labels that each got.

#10379 fix(HardwareSerial): fix pin remapping in begin() on master
  cores/esp32/HardwareSerial.cpp
Labels: Status: Pending Merge

#10390 fix(psram): Init PSRAM before app_main to fix mmu_map
  cores/esp32/esp32-hal-log.h
  cores/esp32/esp32-hal-misc.c
  cores/esp32/esp32-hal-psram.c
Labels: Status: Pending Merge

#10399 Fix WPS example config initialization
  libraries/WiFi/examples/WPS/WPS.ino
Labels: Status: Pending Merge

#10398 fix(hid): Fix OUTPUT report not received
  cores/esp32/esp32-hal-tinyusb.c
  libraries/USB/src/USBHID.cpp
Labels: Status: Pending Merge

#10265 feat(zigbee): Add Zigbee library
  CMakeLists.txt
  boards.txt
  libraries/ESP32/examples/Zigbee/Zigbee_Light_Bulb/Zigbee_Light_Bulb.ino
  libraries/ESP32/examples/Zigbee/Zigbee_Light_Bulb/ci.json
  libraries/ESP32/examples/Zigbee/Zigbee_Light_Switch/Zigbee_Light_Switch.ino
  libraries/ESP32/examples/Zigbee/Zigbee_Light_Switch/ci.json
  libraries/ESP32/examples/Zigbee/Zigbee_Temperature_Sensor/Zigbee_Temperature_Sensor.ino
  libraries/ESP32/examples/Zigbee/Zigbee_Temperature_Sensor/ci.json
  libraries/ESP32/examples/Zigbee/Zigbee_Thermostat/Zigbee_Thermostat.ino
  libraries/ESP32/examples/Zigbee/Zigbee_Thermostat/ci.json
  libraries/Zigbee/examples/Zigbee_Color_Dimmable_Light/README.md
  libraries/Zigbee/examples/Zigbee_Color_Dimmable_Light/Zigbee_Color_Dimmable_Light.ino
  libraries/Zigbee/examples/Zigbee_Color_Dimmable_Light/ci.json
  libraries/Zigbee/examples/Zigbee_Color_Dimmer_Switch/README.md
  libraries/Zigbee/examples/Zigbee_Color_Dimmer_Switch/Zigbee_Color_Dimmer_Switch.ino
  libraries/Zigbee/examples/Zigbee_Color_Dimmer_Switch/ci.json
  libraries/Zigbee/examples/Zigbee_On_Off_Light/README.md
  libraries/Zigbee/examples/Zigbee_On_Off_Light/Zigbee_On_Off_Light.ino
  libraries/Zigbee/examples/Zigbee_On_Off_Light/ci.json
  libraries/Zigbee/examples/Zigbee_On_Off_Switch/README.md
  libraries/Zigbee/examples/Zigbee_On_Off_Switch/Zigbee_On_Off_Switch.ino
  libraries/Zigbee/examples/Zigbee_On_Off_Switch/ci.json
  libraries/Zigbee/examples/Zigbee_Scan_Networks/README.md
  libraries/Zigbee/examples/Zigbee_Scan_Networks/Zigbee_Scan_Networks.ino
  libraries/Zigbee/examples/Zigbee_Scan_Networks/ci.json
  libraries/Zigbee/examples/Zigbee_Temperature_Sensor/README.md
  libraries/Zigbee/examples/Zigbee_Temperature_Sensor/Zigbee_Temperature_Sensor.ino
  libraries/Zigbee/examples/Zigbee_Temperature_Sensor/ci.json
  libraries/Zigbee/examples/Zigbee_Thermostat/README.md
  libraries/Zigbee/examples/Zigbee_Thermostat/Zigbee_Thermostat.ino
  libraries/Zigbee/examples/Zigbee_Thermostat/ci.json
  libraries/Zigbee/keywords.txt
  libraries/Zigbee/library.properties
  libraries/Zigbee/src/ZigbeeCore.cpp
  libraries/Zigbee/src/ZigbeeCore.h
  libraries/Zigbee/src/ZigbeeEP.cpp
  libraries/Zigbee/src/ZigbeeEP.h
  libraries/Zigbee/src/ZigbeeHandlers.cpp
  libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.cpp
  libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.h
  libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.cpp
  libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.h
  libraries/Zigbee/src/ep/ZigbeeLight.cpp
  libraries/Zigbee/src/ep/ZigbeeLight.h
  libraries/Zigbee/src/ep/ZigbeeSwitch.cpp
  libraries/Zigbee/src/ep/ZigbeeSwitch.h
  libraries/Zigbee/src/ep/ZigbeeTempSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeTempSensor.h
  libraries/Zigbee/src/ep/ZigbeeThermostat.cpp
  libraries/Zigbee/src/ep/ZigbeeThermostat.h
Labels: Area: Libraries, Status: Pending Merge

#10406 fix(spiram): Fix OPI PSRAM init
  cores/esp32/esp32-hal-misc.c
Labels: Status: Pending Merge

#10410 IDF release/v5.1
  package/package_esp32_index.template.json
Labels: Status: Pending Merge

#10412 Update FreeRTOS Symbols in OThreadCLI
  libraries/OpenThread/README.md
  libraries/OpenThread/src/OThreadCLI.cpp
  libraries/OpenThread/src/OThreadCLI.h
Labels: Area: Libraries, Status: Pending Merge

#10416 IDF release/v5.3
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10408 Wire library: Add conditional compilation for second I2C interface based on SOC_I2C_NUM
  libraries/Wire/src/Wire.cpp
  libraries/Wire/src/Wire.h
Labels: Status: Pending Merge

#10389 ci(tests): Add linpack FPU tests
  tests/performance/linpack_double/ci.json
  tests/performance/linpack_double/linpack_double.ino
  tests/performance/linpack_double/test_linpack_double.py
  tests/performance/linpack_float/ci.json
  tests/performance/linpack_float/linpack_float.ino
  tests/performance/linpack_float/test_linpack_float.py
Labels: Type: CI & Testing, Status: Pending Merge

#10392 ci(compilation): Use default partition and add append to FQBN option
  .github/scripts/install-platformio-esp32.sh
  .github/scripts/sketch_utils.sh
  .github/scripts/tests_run.sh
  .github/workflows/tests_build.yml
  .github/workflows/tests_hw.yml
  docs/en/contributing.rst
  libraries/ESP32/examples/Camera/CameraWebServer/ci.json
  libraries/ESP32/examples/Camera/CameraWebServer/partitions.csv
  libraries/RainMaker/examples/RMakerCustom/ci.json
  libraries/RainMaker/examples/RMakerCustomAirCooler/ci.json
  libraries/RainMaker/examples/RMakerSonoffDualR3/ci.json
  libraries/RainMaker/examples/RMakerSwitch/ci.json
  libraries/WiFiProv/examples/WiFiProv/ci.json
  libraries/Zigbee/examples/Zigbee_Color_Dimmable_Light/ci.json
  libraries/Zigbee/examples/Zigbee_Color_Dimmer_Switch/ci.json
  libraries/Zigbee/examples/Zigbee_On_Off_Light/ci.json
  libraries/Zigbee/examples/Zigbee_On_Off_Switch/ci.json
  libraries/Zigbee/examples/Zigbee_Scan_Networks/ci.json
  libraries/Zigbee/examples/Zigbee_Temperature_Sensor/ci.json
  libraries/Zigbee/examples/Zigbee_Thermostat/ci.json
  platform.txt
Labels: Type: CI & Testing, Status: Pending Merge

#10402 feat(Variants): Add Arduino libraries for Lora 4G Module and Node Wifi o…
  boards.txt
  variants/BharatPi-A7672S-4G/pins_arduino.h
  variants/BharatPi-LoRa/pins_arduino.h
  variants/BharatPi-Node-Wifi/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10428 feat(uart) 3.1.x Core: fixes serialEventRun() to avoid calling available() if serialEvent() is not declared
  cores/esp32/HardwareSerial.cpp
Labels: Status: Pending Merge, Peripheral: UART, Status: Review needed

#10429 fix(uart) 2.0.x Core: fixes serialEventRun() to avoid calling available() if serialEvent() is not declared
  cores/esp32/HardwareSerial.cpp
Labels: Status: Pending Merge, Peripheral: UART, Status: Review needed

#10409 test(psram): Add PSRAM test
  tests/validation/psram/ci.json
  tests/validation/psram/psram.ino
  tests/validation/psram/test_psram.py
Labels: Type: CI & Testing, Status: Pending Merge

#10426 fix(arduino): adds ESP32-P4 to the package description
  README.md
  package.json
Labels: Type: Documentation, Status: Pending Merge

#10415 fix(asyncudp): Fixes and implements tcpip thread locking
  libraries/AsyncUDP/src/AsyncUDP.cpp
Labels: Status: Pending Merge

#10444 IDF release/v5.3
  libraries/ESP32/examples/Camera/CameraWebServer/app_httpd.cpp
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10446 IDF release/v5.1
  cores/esp32/esp32-hal-tinyusb.c
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10447 fix(uart): Add missing HP UARTs for ESP32-P4
  cores/esp32/HardwareSerial.cpp
  cores/esp32/HardwareSerial.h
  cores/esp32/esp32-hal-uart.c
Labels: Area: Peripherals API, Status: Pending Merge, Peripheral: UART

#10433 Added variant for Waveshare ESP32-S3-Touch-AMOLED-1.8
  boards.txt
  variants/waveshare_esp32_s3_touch_amoled_18/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10456 Update esp-insights version
  idf_component.yml
Labels: Status: Pending Merge

#10465 IDF release/v5.3
  cores/esp32/esp32-hal-tinyusb.c
  idf_component.yml
  package/package_esp32_index.template.json
Labels: Status: Pending Merge

#10454 IDF release/v5.1
  cores/esp32/esp32-hal-tinyusb.c
  package/package_esp32_index.template.json
Labels: Status: Pending Merge

#10473 IDF release/v5.3
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10434 addition(3rd_party_board): Add Waveshare-S3-touch-lcd
  boards.txt
  variants/waveshare_esp32_s3_touch_lcd_4/pins_arduino.h
  variants/waveshare_esp32_s3_touch_lcd_43/pins_arduino.h
  variants/waveshare_esp32_s3_touch_lcd_43b/pins_arduino.h
  variants/waveshare_esp32_s3_touch_lcd_5/pins_arduino.h
  variants/waveshare_esp32_s3_touch_lcd_5b/pins_arduino.h
  variants/waveshare_esp32_s3_touch_lcd_7/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10471 Add IOXESP32-C6 and ATD3.5-S3 board
  boards.txt
  variants/atd35s3/pins_arduino.h
  variants/ioxesp32c6/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10462 Add our new board "cezerio dev ESP32C6"
  boards.txt
  variants/cezerio_dev_esp32c6/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10450 fix(example): print correct fade direction
  libraries/ESP32/examples/AnalogOut/LEDCFade/LEDCFade.ino
Labels: Type: Example, Status: Pending Merge

#10476 fix(esp-rainmaker): update esp-rainmaker version to 1.5.0
  idf_component.yml
Labels: Status: Pending Merge

#10479 Add RMII Ethernet support for ESP32-P4
  boards.txt
  libraries/Ethernet/examples/ETH_LAN8720/ETH_LAN8720.ino
  libraries/Ethernet/examples/ETH_TLK110/ETH_TLK110.ino
  libraries/Ethernet/examples/ETH_TLK110/ci.json
  libraries/Ethernet/examples/ETH_W5500_Arduino_SPI/ETH_W5500_Arduino_SPI.ino
  libraries/Ethernet/examples/ETH_W5500_IDF_SPI/ETH_W5500_IDF_SPI.ino
  libraries/Ethernet/src/ETH.cpp
  libraries/Ethernet/src/ETH.h
  variants/esp32p4/pins_arduino.h
Labels: Status: Pending Merge

#10480 IDF release/v5.3
  package/package_esp32_index.template.json
Labels: Status: Pending Merge

#10484 fix(build): Fix sdkconfig copy for board manager
  platform.txt
Labels: Status: Pending Merge, Area: Tools & Build System

#10472 ci(json): Add requires_any field and use QIO by default to match IDE
  .editorconfig
  .github/scripts/install-platformio-esp32.sh
  .github/scripts/sketch_utils.sh
  .github/scripts/tests_run.sh
  docs/en/contributing.rst
Labels: Type: CI & Testing, Status: Pending Merge

#10460 feat(sdmmc): Add SDMMC support for P4 + remove BUILTIN LED
  libraries/SD_MMC/examples/SDMMC_Test/SDMMC_Test.ino
  libraries/SD_MMC/examples/SDMMC_time/SDMMC_time.ino
  libraries/SD_MMC/src/SD_MMC.cpp
  libraries/SD_MMC/src/SD_MMC.h
  variants/esp32p4/pins_arduino.h
Labels: Area: Libraries, Status: Pending Merge

#10435 fix(testing): Checkout proper branch for Wokwi tests and small QoL improvements
  .github/scripts/tests_matrix.sh
  .github/workflows/dangerjs.yml
  .github/workflows/tests.yml
  .github/workflows/tests_results.yml
  .github/workflows/tests_wokwi.yml
  tests/performance/coremark/coremark.ino
  tests/performance/fibonacci/fibonacci.ino
  tests/performance/fibonacci/test_fibonacci.py
  tests/performance/psramspeed/ci.json
  tests/performance/psramspeed/psramspeed.ino
  tests/performance/ramspeed/ramspeed.ino
  tests/performance/superpi/superpi.ino
  tests/requirements.txt
  tests/validation/gpio/test_gpio.py
  tests/validation/nvs/test_nvs.py
  tests/validation/periman/test_periman.py
  tests/validation/psram/ci.json
  tests/validation/wifi/test_wifi.py
Labels: Type: CI & Testing, Status: Review needed

#10492 fix(formatting): Fix formatting and disable JSON hook
  .pre-commit-config.yaml
  tests/performance/fibonacci/test_fibonacci.py
  tests/validation/gpio/test_gpio.py
  tests/validation/nvs/test_nvs.py
  tests/validation/periman/test_periman.py
  tests/validation/wifi/test_wifi.py
Labels: Type: CI & Testing, Status: Pending Merge

#10495 fix(ci): Chnage approach in listing the changed boards
  .github/scripts/find_new_boards.sh
Labels: Type: CI & Testing, Status: Pending Merge

#10493 fix(arduino): Move extra_flags to flags
  platform.txt
Labels: Status: Pending Merge

#10496 fix(littlefs): Add missing dependency
  CMakeLists.txt
Labels: Area: Libraries, Status: Pending Merge

#10503 IDF release/v5.3
  cores/esp32/esp32-hal-psram.h
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10505 IDF release/v5.1
  cores/esp32/esp32-hal-psram.h
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10507 fix(ci): Boards test - get correct file for the diff
  .github/scripts/find_new_boards.sh
  .github/workflows/boards.yml
Labels: Type: CI & Testing, Status: Pending Merge

#10501 fix(tests): Add missing files to compilation tests
  .github/workflows/push.yml
Labels: Type: CI & Testing, Status: Pending Merge

#10491 fix(zigbee): Enable the internal pull-up resistor for BUTTON_PIN
  libraries/Zigbee/examples/Zigbee_Color_Dimmable_Light/Zigbee_Color_Dimmable_Light.ino
  libraries/Zigbee/examples/Zigbee_Color_Dimmer_Switch/Zigbee_Color_Dimmer_Switch.ino
  libraries/Zigbee/examples/Zigbee_On_Off_Light/Zigbee_On_Off_Light.ino
  libraries/Zigbee/examples/Zigbee_Temperature_Sensor/Zigbee_Temperature_Sensor.ino
  libraries/Zigbee/examples/Zigbee_Thermostat/Zigbee_Thermostat.ino
Labels: Type: Example, Status: Pending Merge

#10508 fix(ci): Boards test set fail-fast to false
  .github/workflows/boards.yml
Labels: Type: CI & Testing, Status: Pending Merge

#10482 Add multiple boards of the Waveshare ESP32-S3-Touch-LCD-1.46 type
  boards.txt
  variants/waveshare_esp32_s3_lcd_146/pins_arduino.h
  variants/waveshare_esp32_s3_lcd_147/pins_arduino.h
  variants/waveshare_esp32_s3_lcd_185/pins_arduino.h
  variants/waveshare_esp32_s3_relay_6ch/pins_arduino.h
  variants/waveshare_esp32_s3_touch_lcd_146/pins_arduino.h
  variants/waveshare_esp32_s3_touch_lcd_185_box/pins_arduino.h
  variants/waveshare_esp32_s3_touch_lcd_21/pins_arduino.h
  variants/waveshare_esp32_s3_touch_lcd_28/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10509 fix(i2s): Use separate variables when reading and writing
  libraries/ESP_I2S/src/ESP_I2S.cpp
Labels: Area: Peripherals API, Status: Pending Merge

#10512 fix(ble): Fixed typos (or copy/paste issues) in comments for AD types in BLEAdvertising
  libraries/BLE/src/BLEAdvertising.cpp
Labels: Status: Pending Merge, Area: BLE

#10513 fix(eth): Set default clock in pin value to zero
  libraries/Ethernet/src/ETH.cpp
Labels: Status: Pending Merge

#10510 Update lib - User can choose if calc MD5 from encrypted or decrypted file
  libraries/Update/src/Update.h
  libraries/Update/src/Updater.cpp
Labels: Area: Libraries, Status: Pending Merge

#10522 IDF release/v5.3
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10515 feature(rtos): Add Tasks status print function
  CMakeLists.txt
  cores/esp32/Arduino.h
  cores/esp32/freertos_stats.cpp
  cores/esp32/freertos_stats.h
Labels: Status: Pending Merge

#10521 ESP32-P4 UART Pin Definitions
  cores/esp32/HardwareSerial.cpp
  cores/esp32/HardwareSerial.h
  tests/validation/uart/uart.ino
Labels: Status: Pending Merge, Peripheral: UART

#10525 feat(uart): uart break example improvement
  libraries/ESP32/examples/Serial/OnReceiveError_BREAK_Demo/OnReceiveError_BREAK_Demo.ino
Labels: Type: Example, Status: Pending Merge, Peripheral: UART

#10524 feat(esptool): Update esptool to v4.8.1
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, Area: Tools & Build System

#10533 fix(bm): Board Manager install will fail on Windows
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, Area: Tools & Build System

#10529 fix(sntp): Lock / Unlock LWIP if CONFIG_LWIP_TCPIP_CORE_LOCKING is set
  cores/esp32/esp32-hal-time.c
Labels: Area: Peripherals API, Status: Pending Merge

#10535 docs(lib-builder): Improve UI and Docker image sections
  docs/en/lib_builder.rst
Labels: Type: Documentation, Status: Pending Merge
