Repository espressif/arduino-esp32, pull requests merged in 2024-12, with the labels that each got.

#10658 feat(matter): New example => Wifi Prov within Matter as alternative for wireless network provisioning
  libraries/Matter/examples/WiFiProvWithinMatter/WiFiProvWithinMatter.ino
  libraries/Matter/examples/WiFiProvWithinMatter/ci.json
Labels: Area: Libraries, Type: Example, Status: Pending Merge, Area: WiFi

#10662 feat(matter): Adds a new Matter Endpoint: Generic Switch (smart button)
  CMakeLists.txt
  libraries/Matter/examples/MatterSmartButon/MatterSmartButon.ino
  libraries/Matter/examples/MatterSmartButon/ci.json
  libraries/Matter/keywords.txt
  libraries/Matter/src/Matter.h
  libraries/Matter/src/MatterEndpoints/MatterGenericSwitch.cpp
  libraries/Matter/src/MatterEndpoints/MatterGenericSwitch.h
Labels: Status: Pending Merge

#10665 BLECharacteristic optimization
  libraries/BLE/src/BLECharacteristic.cpp
Labels: Status: Pending Merge, Area: BLE

#10666 Remove 3rd party references in code and documentation
  .github/ISSUE_TEMPLATE/Issue-report.yml
  docs/_static/logo_pio.png
  docs/en/getting_started.rst
  docs/en/installing.rst
  docs/en/tutorials/blink.rst
  libraries/ESP32/examples/FreeRTOS/BasicMultiThreading/README.md
  libraries/ESP32/examples/FreeRTOS/Mutex/README.md
  libraries/ESP32/examples/FreeRTOS/Queue/README.md
  libraries/ESP32/examples/FreeRTOS/Semaphore/README.md
  libraries/ESP32/examples/RMT/Legacy_RMT_Driver_Compatible/Legacy_RMT_Driver_Compatible.ino
  libraries/ESP32/examples/Template/ExampleTemplate/README.md
  libraries/LittleFS/examples/LITTLEFS_PlatformIO/.gitignore
  libraries/LittleFS/examples/LITTLEFS_PlatformIO/README.md
  libraries/LittleFS/examples/LITTLEFS_PlatformIO/data/file1.txt
  libraries/LittleFS/examples/LITTLEFS_PlatformIO/data/testfolder/test2.txt
  libraries/LittleFS/examples/LITTLEFS_PlatformIO/include/.placeholder.txt
  libraries/LittleFS/examples/LITTLEFS_PlatformIO/lib/.placeholder.txt
  libraries/LittleFS/examples/LITTLEFS_PlatformIO/partitions_custom.csv
  libraries/LittleFS/examples/LITTLEFS_PlatformIO/platformio.ini
  libraries/LittleFS/examples/LITTLEFS_PlatformIO/src/main.cpp
  libraries/NetworkClientSecure/README.md
  libraries/WebServer/examples/MultiHomedServers/README.md
  libraries/WiFi/examples/FTM/FTM_Initiator/README.md
  libraries/WiFi/examples/FTM/FTM_Responder/README.md
  libraries/WiFi/examples/WiFiClient/README.md
  libraries/WiFi/examples/WiFiClientConnect/README.md
  libraries/WiFi/examples/WiFiScan/README.md
  libraries/WiFi/examples/WiFiScanAsync/README.md
  libraries/WiFi/examples/WiFiScanDualAntenna/README.md
  libraries/WiFi/examples/WiFiScanTime/README.md
Labels: Type: Documentation, Status: Pending Merge

#10593 refactor(uart): Refactor UART test to work with any number of UARTs
  tests/validation/uart/diagram.esp32.json
  tests/validation/uart/uart.ino
Labels: Type: CI & Testing, Status: Pending Merge

#10671 feat (Variants) Added custom boards variants GLYPH C3, GLYPHC6 & GLYPHH2
  boards.txt
  variants/Pcbcupid_GLYPH_C3/pins_arduino.h
  variants/Pcbcupid_GLYPH_C6/pins_arduino.h
  variants/Pcbcupid_GLYPH_H2/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10676 feat(Zigbee): Recall bounded devices after reboot + IEEE address option for commands
  libraries/Zigbee/examples/Zigbee_Color_Dimmer_Switch/Zigbee_Color_Dimmer_Switch.ino
  libraries/Zigbee/examples/Zigbee_On_Off_Switch/Zigbee_On_Off_Switch.ino
  libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/Zigbee_Temp_Hum_Sensor_Sleepy.ino
  libraries/Zigbee/src/ZigbeeCore.cpp
  libraries/Zigbee/src/ZigbeeCore.h
  libraries/Zigbee/src/ZigbeeEP.cpp
  libraries/Zigbee/src/ZigbeeEP.h
  libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.cpp
  libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.h
  libraries/Zigbee/src/ep/ZigbeeSwitch.cpp
  libraries/Zigbee/src/ep/ZigbeeSwitch.h
  libraries/Zigbee/src/ep/ZigbeeTempSensor.cpp
Labels: Area: Libraries, Status: Pending Merge

#10680 ci(pre-commit): Bump hooks versions and fix leftover files
  .github/ISSUE_TEMPLATE/Issue-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/scripts/merge_packages.py
  .github/workflows/allboards.yml
  .github/workflows/boards.yml
  .github/workflows/build_py_tools.yml
  .github/workflows/dangerjs.yml
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  .github/workflows/gh-pages.yml
  .github/workflows/lib.yml
  .github/workflows/pre-commit.yml
  .github/workflows/publishlib.yml
  .github/workflows/publishsizes-2.x.yml
  .github/workflows/publishsizes.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .github/workflows/tests_build.yml
  .github/workflows/tests_hw.yml
  .github/workflows/tests_qemu.yml
  .github/workflows/tests_results.yml
  .github/workflows/tests_wokwi.yml
  .pre-commit-config.yaml
  libraries/Matter/src/MatterEndpoints/MatterGenericSwitch.cpp
  tests/performance/psramspeed/test_psramspeed.py
  tests/performance/ramspeed/test_ramspeed.py
  tools/gen_esp32part.py
Labels: Type: CI & Testing, Status: Pending Merge

#10691 feat(Matter): Creates New Matter Fan Controller Endpoint
  CMakeLists.txt
  libraries/Matter/examples/MatterFan/MatterFan.ino
  libraries/Matter/examples/MatterFan/ci.json
  libraries/Matter/keywords.txt
  libraries/Matter/src/Matter.h
  libraries/Matter/src/MatterEndPoint.h
  libraries/Matter/src/MatterEndpoints/MatterFan.cpp
  libraries/Matter/src/MatterEndpoints/MatterFan.h
Labels: Status: Pending Merge

#10697 Fix spiTransaction not updating clock line immediately (backport of #9333 into v2.x branch)
  cores/esp32/esp32-hal-spi.c
Labels: Area: Peripherals API

#10696 fix(esp32): ESP32-U4WDH chip detection by ESP.getChipModel()
  cores/esp32/Esp.cpp
Labels: Status: Pending Merge

#10698 feat(matter): adds new Temperature Sensor Matter Endpoint
  CMakeLists.txt
  libraries/Matter/examples/MatterTemperatureSensor/MatterTemperatureSensor.ino
  libraries/Matter/examples/MatterTemperatureSensor/ci.json
  libraries/Matter/keywords.txt
  libraries/Matter/src/Matter.h
  libraries/Matter/src/MatterEndpoints/MatterTemperatureSensor.cpp
  libraries/Matter/src/MatterEndpoints/MatterTemperatureSensor.h
Labels: Status: Pending Merge

#10700 feat(chip): Add definition for BOOT_PIN for all chips
  cores/esp32/esp32-hal.h
Labels: Status: Pending Merge

#10703 feat(Matter): Adds New Matter Humidity Sensor Endpoint
  CMakeLists.txt
  libraries/Matter/examples/MatterHumiditySensor/MatterHumiditySensor.ino
  libraries/Matter/examples/MatterHumiditySensor/ci.json
  libraries/Matter/keywords.txt
  libraries/Matter/src/Matter.h
  libraries/Matter/src/MatterEndpoints/MatterHumiditySensor.cpp
  libraries/Matter/src/MatterEndpoints/MatterHumiditySensor.h
Labels: Status: Pending Merge

#10702 feat(matter_examples): apply boot button change to all examples
  libraries/Matter/examples/MatterColorLight/MatterColorLight.ino
  libraries/Matter/examples/MatterColorLight/ci.json
  libraries/Matter/examples/MatterComposedLights/MatterComposedLights.ino
  libraries/Matter/examples/MatterDimmableLight/MatterDimmableLight.ino
  libraries/Matter/examples/MatterEnhancedColorLight/MatterEnhancedColorLight.ino
  libraries/Matter/examples/MatterFan/MatterFan.ino
  libraries/Matter/examples/MatterMinimum/MatterMinimum.ino
  libraries/Matter/examples/MatterOnOffLight/MatterOnOffLight.ino
  libraries/Matter/examples/MatterSmartButon/MatterSmartButon.ino
  libraries/Matter/examples/MatterTemperatureLight/MatterTemperatureLight.ino
  libraries/Matter/examples/MatterTemperatureLight/ci.json
  libraries/Matter/examples/MatterTemperatureSensor/MatterTemperatureSensor.ino
  libraries/Matter/examples/WiFiProvWithinMatter/WiFiProvWithinMatter.ino
Labels: Status: Pending Merge

#10708 ci(tests): Remove 3rd party tools tests
  .github/scripts/install-platformio-esp32.sh
  .github/scripts/on-push.sh
  .github/scripts/on-release.sh
  .github/scripts/set_push_chunks.sh
  .github/workflows/push.yml
  platform.txt
  tools/pioarduino-build.py
Labels: Type: CI & Testing, Status: Pending Merge, Area: Tools & Build System

#10710 feat(matter): adds a Pressure Sensor Matter Endpoint
  CMakeLists.txt
  libraries/Matter/examples/MatterPressureSensor/MatterPressureSensor.ino
  libraries/Matter/examples/MatterPressureSensor/ci.json
  libraries/Matter/keywords.txt
  libraries/Matter/src/Matter.h
  libraries/Matter/src/MatterEndpoints/MatterPressureSensor.cpp
  libraries/Matter/src/MatterEndpoints/MatterPressureSensor.h
Labels: Status: Pending Merge

#10713 fix(SDMMC): Remove need for BOARD_HAS_SDMMC for esp32
  libraries/SD_MMC/src/SD_MMC.cpp
Labels: Area: Libraries, Status: Pending Merge

#10704 fix(zigbee): Fix rejoin issue for battery powered devices
  libraries/Zigbee/examples/Zigbee_Color_Dimmable_Light/Zigbee_Color_Dimmable_Light.ino
  libraries/Zigbee/examples/Zigbee_Color_Dimmer_Switch/Zigbee_Color_Dimmer_Switch.ino
  libraries/Zigbee/examples/Zigbee_On_Off_Light/Zigbee_On_Off_Light.ino
  libraries/Zigbee/examples/Zigbee_On_Off_Switch/Zigbee_On_Off_Switch.ino
  libraries/Zigbee/examples/Zigbee_Scan_Networks/Zigbee_Scan_Networks.ino
  libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/Zigbee_Temp_Hum_Sensor_Sleepy.ino
  libraries/Zigbee/examples/Zigbee_Temperature_Sensor/Zigbee_Temperature_Sensor.ino
  libraries/Zigbee/examples/Zigbee_Thermostat/Zigbee_Thermostat.ino
  libraries/Zigbee/src/ZigbeeCore.cpp
  libraries/Zigbee/src/ZigbeeCore.h
Labels: Status: Pending Merge

#10699 feat(board): Add custom boards YB-ESP32-S3-AMP-V2 & YB-ESP32-S3-AMP-V3
  boards.txt
  variants/yb_esp32s3_amp_v2/pins_arduino.h
  variants/yb_esp32s3_amp_v3/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10712 feat(matter): creates a Matter Contact Sensor Endpoint
  CMakeLists.txt
  libraries/Matter/examples/MatterContactSensor/MatterContactSensor.ino
  libraries/Matter/examples/MatterContactSensor/ci.json
  libraries/Matter/keywords.txt
  libraries/Matter/src/Matter.h
  libraries/Matter/src/MatterEndpoints/MatterContactSensor.cpp
  libraries/Matter/src/MatterEndpoints/MatterContactSensor.h
Labels: Status: Pending Merge

#10677 fix: Split provisioning into two parts for better synchronization
  libraries/RainMaker/examples/RMakerSwitch/RMakerSwitch.ino
  libraries/WiFiProv/src/WiFiProv.cpp
  libraries/WiFiProv/src/WiFiProv.h
Labels: Status: Pending Merge

#10715 feat(arduino): remove all while(not serial) in examples
  libraries/ESP32/examples/AnalogOut/LEDCFade/LEDCFade.ino
  libraries/ESP32/examples/DeepSleep/SmoothBlink_ULP_Code/SmoothBlink_ULP_Code.ino
  libraries/ESP32/examples/FreeRTOS/Mutex/Mutex.ino
  libraries/ESP32/examples/FreeRTOS/Queue/Queue.ino
  libraries/ESP32/examples/FreeRTOS/Semaphore/Semaphore.ino
  libraries/ESP32/examples/GPIO/FunctionalInterrupt/FunctionalInterrupt.ino
  libraries/ESP32/examples/MacAddress/GetMacAddress/GetMacAddress.ino
  libraries/ESP32/examples/Serial/RS485_Echo_Demo/RS485_Echo_Demo.ino
  libraries/ESP32/examples/Utilities/HEXBuilder/HEXBuilder.ino
  libraries/ESP32/examples/Utilities/MD5Builder/MD5Builder.ino
  libraries/ESP32/examples/Utilities/SHA1Builder/SHA1Builder.ino
  libraries/ESP_I2S/examples/ES8388_loopback/ES8388_loopback.ino
  libraries/ESP_I2S/examples/Record_to_WAV/Record_to_WAV.ino
  libraries/ESP_NOW/examples/ESP_NOW_Broadcast_Master/ESP_NOW_Broadcast_Master.ino
  libraries/ESP_NOW/examples/ESP_NOW_Broadcast_Slave/ESP_NOW_Broadcast_Slave.ino
  libraries/ESP_NOW/examples/ESP_NOW_Network/ESP_NOW_Network.ino
  libraries/SD/examples/SD_Test/SD_Test.ino
  libraries/WebServer/examples/HttpAuthCallback/HttpAuthCallback.ino
  libraries/WebServer/examples/HttpAuthCallbackInline/HttpAuthCallbackInline.ino
  libraries/WebServer/examples/HttpBasicAuthSHA1/HttpBasicAuthSHA1.ino
  libraries/WebServer/examples/HttpBasicAuthSHA1orBearerToken/HttpBasicAuthSHA1orBearerToken.ino
  libraries/WebServer/examples/MultiHomedServers/MultiHomedServers.ino
  libraries/WiFi/examples/WiFiClient/WiFiClient.ino
Labels: Type: Example, Status: Pending Merge

#10705 IDF release/v5.1
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10719 IDF release/v5.3
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10717 feat(matter): adds new Matter Occupancy Sensor endpoint
  CMakeLists.txt
  libraries/Matter/examples/MatterOccupancySensor/MatterOccupancySensor.ino
  libraries/Matter/examples/MatterOccupancySensor/ci.json
  libraries/Matter/keywords.txt
  libraries/Matter/src/Matter.h
  libraries/Matter/src/MatterEndpoints/MatterOccupancySensor.cpp
  libraries/Matter/src/MatterEndpoints/MatterOccupancySensor.h
Labels: Status: Pending Merge

#10725 fix(sntp): Lock / Unlock LWIP if CONFIG_LWIP_TCPIP_CORE_LOCKING is set
  cores/esp32/esp32-hal-time.c
Labels: Status: Pending Merge

#10722 feat(matter): adds a new endpoint to Matter - On/Off Plugin (Power Relay)
  CMakeLists.txt
  libraries/Matter/examples/MatterOnOffPlugin/MatterOnOffPlugin.ino
  libraries/Matter/examples/MatterOnOffPlugin/ci.json
  libraries/Matter/keywords.txt
  libraries/Matter/src/Matter.h
  libraries/Matter/src/MatterEndpoints/MatterOnOffPlugin.cpp
  libraries/Matter/src/MatterEndpoints/MatterOnOffPlugin.h
Labels: Status: Pending Merge

#10724 Cap size of last chunk in raw read in WebServer
  libraries/WebServer/src/Parsing.cpp
Labels: Status: Pending Merge

#10727 Zigbee: Add dimmable light endpoint class
  CMakeLists.txt
  libraries/Zigbee/examples/Zigbee_Dimmable_Light/README.md
  libraries/Zigbee/examples/Zigbee_Dimmable_Light/Zigbee_Dimmable_Light.ino
  libraries/Zigbee/examples/Zigbee_Dimmable_Light/ci.json
  libraries/Zigbee/src/Zigbee.h
  libraries/Zigbee/src/ep/ZigbeeDimmableLight.cpp
  libraries/Zigbee/src/ep/ZigbeeDimmableLight.h
Labels: Area: Libraries, Status: Pending Merge

#10730 Use INPUT_PULLUP instead of INPUT
  libraries/ESP32/examples/Timer/RepeatTimer/RepeatTimer.ino
Labels: Type: Example, Status: Pending Merge

#10732 feat(matter): General Review - remove while(!serial) ipv6(enable) and fixes some commentaries in the code
  libraries/Matter/examples/MatterColorLight/MatterColorLight.ino
  libraries/Matter/examples/MatterCommissionTest/MatterCommissionTest.ino
  libraries/Matter/examples/MatterComposedLights/MatterComposedLights.ino
  libraries/Matter/examples/MatterContactSensor/MatterContactSensor.ino
  libraries/Matter/examples/MatterDimmableLight/MatterDimmableLight.ino
  libraries/Matter/examples/MatterEnhancedColorLight/MatterEnhancedColorLight.ino
  libraries/Matter/examples/MatterFan/MatterFan.ino
  libraries/Matter/examples/MatterHumiditySensor/MatterHumiditySensor.ino
  libraries/Matter/examples/MatterMinimum/MatterMinimum.ino
  libraries/Matter/examples/MatterOccupancySensor/MatterOccupancySensor.ino
  libraries/Matter/examples/MatterOnOffLight/MatterOnOffLight.ino
  libraries/Matter/examples/MatterOnOffPlugin/MatterOnOffPlugin.ino
  libraries/Matter/examples/MatterPressureSensor/MatterPressureSensor.ino
  libraries/Matter/examples/MatterSmartButon/MatterSmartButon.ino
  libraries/Matter/examples/MatterTemperatureLight/MatterTemperatureLight.ino
  libraries/Matter/examples/MatterTemperatureSensor/MatterTemperatureSensor.ino
  libraries/Matter/src/MatterEndpoints/MatterColorLight.cpp
  libraries/Matter/src/MatterEndpoints/MatterColorLight.h
  libraries/Matter/src/MatterEndpoints/MatterColorTemperatureLight.cpp
  libraries/Matter/src/MatterEndpoints/MatterColorTemperatureLight.h
  libraries/Matter/src/MatterEndpoints/MatterContactSensor.cpp
  libraries/Matter/src/MatterEndpoints/MatterDimmableLight.cpp
  libraries/Matter/src/MatterEndpoints/MatterDimmableLight.h
  libraries/Matter/src/MatterEndpoints/MatterEnhancedColorLight.cpp
  libraries/Matter/src/MatterEndpoints/MatterEnhancedColorLight.h
  libraries/Matter/src/MatterEndpoints/MatterFan.cpp
  libraries/Matter/src/MatterEndpoints/MatterFan.h
  libraries/Matter/src/MatterEndpoints/MatterHumiditySensor.cpp
  libraries/Matter/src/MatterEndpoints/MatterOccupancySensor.cpp
  libraries/Matter/src/MatterEndpoints/MatterOnOffLight.cpp
  libraries/Matter/src/MatterEndpoints/MatterOnOffLight.h
  libraries/Matter/src/MatterEndpoints/MatterOnOffPlugin.cpp
  libraries/Matter/src/MatterEndpoints/MatterOnOffPlugin.h
  libraries/Matter/src/MatterEndpoints/MatterPressureSensor.cpp
  libraries/Matter/src/MatterEndpoints/MatterPressureSensor.h
  libraries/Matter/src/MatterEndpoints/MatterTemperatureSensor.cpp
  libraries/Matter/src/MatterEndpoints/MatterTemperatureSensor.h
Labels: Area: Libraries, Status: Pending Merge

#10735 fix(clk_src): Fix error as APLL is not yet supported for P4
  cores/esp32/esp32-hal-cpu.c
Labels: Status: Pending Merge

#10737 [NetworkClient] Init members of NetworkClient
  libraries/Network/src/NetworkClient.h
Labels: Status: Pending Merge

#10734 feat(matter) adds Identification callback to all matter endpoints
  libraries/Matter/examples/MatterOnIdentify/MatterOnIdentify.ino
  libraries/Matter/examples/MatterOnIdentify/ci.json
  libraries/Matter/src/Matter.cpp
  libraries/Matter/src/MatterEndPoint.h
  libraries/Matter/src/MatterEndpoints/MatterColorLight.cpp
  libraries/Matter/src/MatterEndpoints/MatterColorTemperatureLight.cpp
  libraries/Matter/src/MatterEndpoints/MatterContactSensor.cpp
  libraries/Matter/src/MatterEndpoints/MatterDimmableLight.cpp
  libraries/Matter/src/MatterEndpoints/MatterEnhancedColorLight.cpp
  libraries/Matter/src/MatterEndpoints/MatterFan.cpp
  libraries/Matter/src/MatterEndpoints/MatterGenericSwitch.cpp
  libraries/Matter/src/MatterEndpoints/MatterHumiditySensor.cpp
  libraries/Matter/src/MatterEndpoints/MatterOccupancySensor.cpp
  libraries/Matter/src/MatterEndpoints/MatterOnOffLight.cpp
  libraries/Matter/src/MatterEndpoints/MatterOnOffPlugin.cpp
  libraries/Matter/src/MatterEndpoints/MatterPressureSensor.cpp
  libraries/Matter/src/MatterEndpoints/MatterTemperatureSensor.cpp
Labels: Area: Libraries, Status: Pending Merge

#10741 feat(board): Add custom board YB-ESP32-S3-ETH
  boards.txt
  variants/yb_esp32s3_eth/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10745 fix(readme): Update readme and fix badges
  .github/workflows/tests_results.yml
  README.md
Labels: Type: Documentation, Status: Pending Merge

#10738 IDF release/v5.1
  package/package_esp32_index.template.json
Labels: 🚫 System PR

#10752 fix(component): Checkout proper branch for uploading component
  .github/workflows/upload-idf-component.yml
Labels: Type: CI & Testing, Status: Pending Merge
