Repository espressif/arduino-esp32, pull requests merged in 2024-11, with the labels that each got.

#10544 ci(workflows): General improvements and fixes
  .github/scripts/set_push_chunks.sh
  .github/workflows/pre-commit.yml
  .github/workflows/push.yml
  .github/workflows/tests.yml
  tests/requirements.txt
  tools/pre-commit/requirements.txt
Labels: Type: CI & Testing, Status: Pending Merge, Area: Tools & Build System

#10563 fix(zigbee): Fix and bump zigbee version and stay on 1.6.0
  idf_component.yml
  libraries/Zigbee/src/ep/ZigbeeTempSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeThermostat.cpp
Labels: Status: Blocked upstream 🛑

#10549 feat(boards): add Waveshare ESP32-S3-Touch-AMOLED boards
  boards.txt
  variants/waveshare_esp32_s3_touch_amoled_143/pins_arduino.h
  variants/waveshare_esp32_s3_touch_amoled_164/pins_arduino.h
  variants/waveshare_esp32_s3_touch_amoled_191/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10538 fix(example):Update comment in BLE5_periodic_advertising.ino
  libraries/BLE/examples/BLE5_periodic_advertising/BLE5_periodic_advertising.ino
Labels: Type: Example, Status: Pending Merge

#10567 fix(wokwi): Delete generated diagram to avoid issues running locally
  .github/scripts/tests_run.sh
Labels: Type: CI & Testing, Status: Pending Merge

#10546 fix(IPaddress): IPv6 restore zone id
  cores/esp32/IPAddress.cpp
Labels: Status: Pending Merge, Area: WiFi

#10570 fix(esptool): Bump esptool version to 4.9.dev1 on 3.1.x
  package/package_esp32_index.template.json
  platform.txt
Labels: Type: CI & Testing, Status: Pending Merge, Area: Tools & Build System

#10577 IDF release/v5.1
  idf_component.yml
  libraries/Zigbee/src/ZigbeeCore.cpp
  libraries/Zigbee/src/ZigbeeCore.h
  libraries/Zigbee/src/ZigbeeEP.cpp
  libraries/Zigbee/src/ZigbeeEP.h
  libraries/Zigbee/src/ZigbeeHandlers.cpp
  libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.cpp
  libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.h
  libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.cpp
  libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.h
  libraries/Zigbee/src/ep/ZigbeeLight.cpp
  libraries/Zigbee/src/ep/ZigbeeLight.h
  libraries/Zigbee/src/ep/ZigbeeSwitch.cpp
  libraries/Zigbee/src/ep/ZigbeeSwitch.h
  libraries/Zigbee/src/ep/ZigbeeTempSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeTempSensor.h
  libraries/Zigbee/src/ep/ZigbeeThermostat.cpp
  libraries/Zigbee/src/ep/ZigbeeThermostat.h
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10579 fix(wifi): Fix requirements and guards for hosted Wi-Fi
  libraries/ESP_NOW/examples/ESP_NOW_Broadcast_Master/ci.json
  libraries/ESP_NOW/examples/ESP_NOW_Broadcast_Slave/ci.json
  libraries/ESP_NOW/examples/ESP_NOW_Network/ci.json
  libraries/ESP_NOW/examples/ESP_NOW_Serial/ci.json
  libraries/ESP_NOW/src/ESP32_NOW.cpp
  libraries/ESP_NOW/src/ESP32_NOW.h
  libraries/ESP_NOW/src/ESP32_NOW_Serial.cpp
  libraries/ESP_NOW/src/ESP32_NOW_Serial.h
  libraries/HTTPClient/examples/HTTPClientEnterprise/HTTPClientEnterprise.ino
  libraries/HTTPClient/examples/HTTPClientEnterprise/ci.json
  libraries/NetworkClientSecure/examples/WiFiClientSecureEnterprise/WiFiClientSecureEnterprise.ino
  libraries/NetworkClientSecure/examples/WiFiClientSecureEnterprise/ci.json
  libraries/WiFi/examples/WPS/WPS.ino
  libraries/WiFi/examples/WPS/ci.json
  libraries/WiFi/examples/WiFiSmartConfig/WiFiSmartConfig.ino
  libraries/WiFi/examples/WiFiSmartConfig/ci.json
  tests/validation/wifi/ci.json
Labels: Type: CI & Testing, Status: Pending Merge

#10581 fix(Zigbee): Fix typo in Zigbee_Temp_Hum_Sensor_Sleepy.ino
  libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/Zigbee_Temp_Hum_Sensor_Sleepy.ino
Labels: Type: Example, Status: Pending Merge

#10583 fix(tests): Fix wrong selection of tests and add debug flag for testing
  .github/scripts/sketch_utils.sh
  .github/scripts/tests_run.sh
Labels: Type: CI & Testing, Status: Pending Merge

#10591 feat(usb_hid_keyboard): Adds Keyboard Layout and Sends reports just for Modifier Keys
  CMakeLists.txt
  libraries/USB/src/USBHIDKeyboard.cpp
  libraries/USB/src/USBHIDKeyboard.h
  libraries/USB/src/keyboardLayout/KeyboardLayout.h
  libraries/USB/src/keyboardLayout/KeyboardLayout_da_DK.cpp
  libraries/USB/src/keyboardLayout/KeyboardLayout_de_DE.cpp
  libraries/USB/src/keyboardLayout/KeyboardLayout_en_US.cpp
  libraries/USB/src/keyboardLayout/KeyboardLayout_es_ES.cpp
  libraries/USB/src/keyboardLayout/KeyboardLayout_fr_FR.cpp
  libraries/USB/src/keyboardLayout/KeyboardLayout_hu_HU.cpp
  libraries/USB/src/keyboardLayout/KeyboardLayout_it_IT.cpp
  libraries/USB/src/keyboardLayout/KeyboardLayout_pt_BR.cpp
  libraries/USB/src/keyboardLayout/KeyboardLayout_pt_PT.cpp
  libraries/USB/src/keyboardLayout/KeyboardLayout_sv_SE.cpp
  libraries/USB/src/keyboardLayout/Keyboard_da_DK.h
  libraries/USB/src/keyboardLayout/Keyboard_de_DE.h
  libraries/USB/src/keyboardLayout/Keyboard_es_ES.h
  libraries/USB/src/keyboardLayout/Keyboard_fr_FR.h
  libraries/USB/src/keyboardLayout/Keyboard_hu_HU.h
  libraries/USB/src/keyboardLayout/Keyboard_it_IT.h
  libraries/USB/src/keyboardLayout/Keyboard_pt_BR.h
  libraries/USB/src/keyboardLayout/Keyboard_pt_PT.h
  libraries/USB/src/keyboardLayout/Keyboard_sv_SE.h
Labels: Area: Libraries, Status: Pending Merge

#10595 fix(wifi): fixes WiFi.isconnected() to return true when it is connected and it has an IP Addr
  libraries/WiFi/src/WiFiSTA.cpp
Labels: Status: Pending Merge, Area: WiFi

#10582 fix(net): Allow to compile without IPv6 enabled
  cores/esp32/IPAddress.cpp
  cores/esp32/IPAddress.h
  libraries/AsyncUDP/src/AsyncUDP.cpp
  libraries/AsyncUDP/src/AsyncUDP.h
  libraries/Ethernet/src/ETH.cpp
  libraries/Network/src/NetworkClient.cpp
  libraries/Network/src/NetworkEvents.h
  libraries/Network/src/NetworkInterface.cpp
  libraries/Network/src/NetworkInterface.h
  libraries/Network/src/NetworkManager.cpp
  libraries/Network/src/NetworkServer.cpp
  libraries/Network/src/NetworkUdp.cpp
  libraries/NetworkClientSecure/src/ssl_client.cpp
  libraries/WiFi/src/AP.cpp
  libraries/WiFi/src/STA.cpp
  libraries/WiFi/src/WiFiAP.cpp
  libraries/WiFi/src/WiFiAP.h
  libraries/WiFi/src/WiFiGeneric.cpp
  libraries/WiFi/src/WiFiGeneric.h
  libraries/WiFi/src/WiFiMulti.cpp
  libraries/WiFi/src/WiFiMulti.h
  libraries/WiFi/src/WiFiSTA.cpp
  libraries/WiFi/src/WiFiSTA.h
  libraries/WiFi/src/WiFiScan.h
  libraries/WiFi/src/WiFiType.h
  libraries/WiFiProv/src/WiFiProv.cpp
  libraries/WiFiProv/src/WiFiProv.h
Labels: Status: Pending Merge

#10597 fix(build): Allow Arduino to compile in IDF without components
  CMakeLists.txt
  libraries/ArduinoOTA/src/ArduinoOTA.cpp
  libraries/ESP_I2S/src/ESP_I2S.cpp
  libraries/ESP_I2S/src/ESP_I2S.h
  libraries/ESPmDNS/src/ESPmDNS.cpp
  libraries/ESPmDNS/src/ESPmDNS.h
  libraries/LittleFS/src/LittleFS.cpp
  libraries/LittleFS/src/LittleFS.h
  libraries/PPP/src/PPP.cpp
  libraries/PPP/src/PPP.h
  libraries/PPP/src/ppp.c
Labels: Status: Pending Merge

#10600 IDF release/v5.1
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10599 IDF release/v5.3
  idf_component.yml
  libraries/WiFi/src/WiFiGeneric.cpp
  libraries/Zigbee/src/ZigbeeCore.cpp
  libraries/Zigbee/src/ZigbeeCore.h
  libraries/Zigbee/src/ZigbeeEP.cpp
  libraries/Zigbee/src/ZigbeeEP.h
  libraries/Zigbee/src/ZigbeeHandlers.cpp
  libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.cpp
  libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.h
  libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.cpp
  libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.h
  libraries/Zigbee/src/ep/ZigbeeLight.cpp
  libraries/Zigbee/src/ep/ZigbeeLight.h
  libraries/Zigbee/src/ep/ZigbeeSwitch.cpp
  libraries/Zigbee/src/ep/ZigbeeSwitch.h
  libraries/Zigbee/src/ep/ZigbeeTempSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeTempSensor.h
  libraries/Zigbee/src/ep/ZigbeeThermostat.cpp
  libraries/Zigbee/src/ep/ZigbeeThermostat.h
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10610 fix(M5Stack Fire): Fixed TF reader SS pin value.
  variants/m5stack_fire/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10604 Feat: Feather V2 and Qt PY larger SPIFFS PartitionScheme
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#10614 Fixed incorrect Flash size for UM FeatherS3 Neo build flash size
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#10617 fix weird formatting, no code change
  cores/esp32/esp32-hal-cpu.c
Labels: Status: Pending Merge

#10618 Matter example patch
  libraries/Matter/examples/MatterDimmableLight/MatterDimmableLight.ino
  libraries/Matter/examples/MatterOnOffLight/MatterOnOffLight.ino
Labels: Status: Pending Merge

#10609 Guard ethernet parts to make it possible to use without
  libraries/Ethernet/src/ETH.cpp
  libraries/Ethernet/src/ETH.h
  libraries/Network/src/NetworkEvents.h
  libraries/WiFi/src/WiFiGeneric.h
Labels: Status: Pending Merge

#10616 Guard WPA Enterprise support
  libraries/WiFi/src/STA.cpp
  libraries/WiFi/src/WiFiSTA.cpp
  libraries/WiFi/src/WiFiSTA.h
Labels: Status: Pending Merge

#10626 feat(zigbee): Add setLight APIs to manually operate lights
  libraries/Zigbee/examples/Zigbee_Color_Dimmable_Light/Zigbee_Color_Dimmable_Light.ino
  libraries/Zigbee/examples/Zigbee_On_Off_Light/Zigbee_On_Off_Light.ino
  libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.cpp
  libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.h
  libraries/Zigbee/src/ep/ZigbeeLight.cpp
  libraries/Zigbee/src/ep/ZigbeeLight.h
Labels: Area: Libraries, Status: Pending Merge

#10631 feat(openthread): add license declaration to all soure code and examples
  libraries/OpenThread/examples/COAP/coap_lamp/coap_lamp.ino
  libraries/OpenThread/examples/COAP/coap_switch/coap_switch.ino
  libraries/OpenThread/examples/SimpleCLI/SimpleCLI.ino
  libraries/OpenThread/examples/SimpleNode/SimpleNode.ino
  libraries/OpenThread/examples/SimpleThreadNetwork/ExtendedRouterNode/ExtendedRouterNode.ino
  libraries/OpenThread/examples/SimpleThreadNetwork/LeaderNode/LeaderNode.ino
  libraries/OpenThread/examples/SimpleThreadNetwork/RouterNode/RouterNode.ino
  libraries/OpenThread/examples/ThreadScan/ThreadScan.ino
  libraries/OpenThread/examples/onReceive/onReceive.ino
  libraries/OpenThread/src/OThreadCLI.cpp
  libraries/OpenThread/src/OThreadCLI.h
  libraries/OpenThread/src/OThreadCLI_Util.cpp
  libraries/OpenThread/src/OThreadCLI_Util.h
Labels: Type: Example, Status: Pending Merge

#10639 Adds a Minimum Code Matter Example
  libraries/Matter/examples/MatterMinimum/MatterMinimum.ino
  libraries/Matter/examples/MatterMinimum/ci.json
Labels: Type: Example, Status: Pending Merge, Status: Review needed

#10638 fix compile of P4 caused from missing ")" in debug macro
  cores/esp32/esp32-hal-cpu.c
Labels: Status: Pending Merge

#10642 feat(uart): [IDF5.1] fixes HardwareSerial::updateBaudRate() using a baud rate higher 230400 - checks UART Clock Source
  cores/esp32/esp32-hal-uart.c
  libraries/OpenThread/examples/COAP/coap_lamp/coap_lamp.ino
  libraries/OpenThread/examples/COAP/coap_switch/coap_switch.ino
  libraries/OpenThread/examples/SimpleCLI/SimpleCLI.ino
  libraries/OpenThread/examples/SimpleNode/SimpleNode.ino
  libraries/OpenThread/examples/SimpleThreadNetwork/ExtendedRouterNode/ExtendedRouterNode.ino
  libraries/OpenThread/examples/SimpleThreadNetwork/LeaderNode/LeaderNode.ino
  libraries/OpenThread/examples/SimpleThreadNetwork/RouterNode/RouterNode.ino
  libraries/OpenThread/examples/ThreadScan/ThreadScan.ino
  libraries/OpenThread/examples/onReceive/onReceive.ino
  libraries/OpenThread/src/OThreadCLI.cpp
  libraries/OpenThread/src/OThreadCLI.h
  libraries/OpenThread/src/OThreadCLI_Util.cpp
  libraries/OpenThread/src/OThreadCLI_Util.h
Labels: Status: Pending Merge, Peripheral: UART

#10643 feat(uart): [IDF 5.3] fixes HardwareSerial::updateBaudRate() using a baud rate higher 230400 - checks UART Clock Source
  cores/esp32/esp32-hal-uart.c
Labels: Status: Pending Merge, Peripheral: UART

#10636 fix(zigbee): Add connected(), minor fixes, example update
  boards.txt
  libraries/Zigbee/examples/Zigbee_Color_Dimmable_Light/Zigbee_Color_Dimmable_Light.ino
  libraries/Zigbee/examples/Zigbee_Color_Dimmer_Switch/Zigbee_Color_Dimmer_Switch.ino
  libraries/Zigbee/examples/Zigbee_On_Off_Light/Zigbee_On_Off_Light.ino
  libraries/Zigbee/examples/Zigbee_On_Off_Switch/Zigbee_On_Off_Switch.ino
  libraries/Zigbee/examples/Zigbee_Scan_Networks/Zigbee_Scan_Networks.ino
  libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/Zigbee_Temp_Hum_Sensor_Sleepy.ino
  libraries/Zigbee/examples/Zigbee_Temperature_Sensor/Zigbee_Temperature_Sensor.ino
  libraries/Zigbee/examples/Zigbee_Thermostat/Zigbee_Thermostat.ino
  libraries/Zigbee/keywords.txt
  libraries/Zigbee/src/ZigbeeCore.cpp
  libraries/Zigbee/src/ZigbeeCore.h
  libraries/Zigbee/src/ZigbeeEP.cpp
  libraries/Zigbee/src/ZigbeeEP.h
  libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.h
Labels: Area: Libraries, Status: Pending Merge

#10637 AsyncUdp license and keyword update
  libraries/AsyncUDP/keywords.txt
Labels: Status: Pending Merge

#10651 fix(zigbee): Increase timeout, commision again on failure + setScanDuration
  libraries/Zigbee/keywords.txt
  libraries/Zigbee/src/ZigbeeCore.cpp
  libraries/Zigbee/src/ZigbeeCore.h
Labels: Area: Libraries, Status: Pending Merge

#10648 Add our new development board "cezerio mini dev ESP32C6"
  boards.txt
  variants/cezerio_mini_dev_esp32c6/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards
