Repository espressif/arduino-esp32, pull requests merged in 2024-07, with the labels that each got.

#9948 feat(net): Enable IPv6 immediately if already connected
  libraries/Network/src/NetworkInterface.cpp
Labels: Status: Pending Merge

#9956 Added LilyGo T3S3 variants
  boards.txt
  variants/lilygo_t3_s3_lr1121/pins_arduino.h
  variants/lilygo_t3_s3_sx1262/pins_arduino.h
  variants/lilygo_t3_s3_sx127x/pins_arduino.h
  variants/lilygo_t3_s3_sx1280/pins_arduino.h
  variants/lilygo_t3_s3_sx1280pa/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#9968 fix(docs): Correct i2s.srt api example
  docs/en/api/i2s.rst
Labels: Type: Example, Status: Pending Merge

#9952 [release/2.x] fix(uart): Set back Pin signal polarity
  cores/esp32/esp32-hal-uart.c
Labels: Status: Pending Merge, Peripheral: UART, Backport needed :back:

#9961 feat (3rd_party_board): Add new Adafruit Feather C6 - rev B
  boards.txt
  variants/adafruit_feather_esp32c6/pins_arduino.h
  variants/adafruit_feather_esp32c6/variant.cpp
Labels: Status: Pending Merge, Type: 3rd party Boards

#9977 docs(lib-builder): Add instructions to use the UI
  docs/en/lib_builder.rst
Labels: Type: Documentation, Area: LIB Builder, Status: Pending Merge

#9991 Fix timeout in WebServer::_uploadReadByte and handleClient() (#9990)
  libraries/WebServer/src/Parsing.cpp
  libraries/WebServer/src/WebServer.cpp
  libraries/WebServer/src/WebServer.h
Labels: Status: Pending Merge

#9998 fix(httpc): Fix data read was less than expected
  libraries/HTTPClient/src/HTTPClient.cpp
Labels: Status: Pending Merge

#10003 feat(eth): Allow setting the RX task stack size
  libraries/Ethernet/src/ETH.cpp
  libraries/Ethernet/src/ETH.h
Labels: Status: Pending Merge

#10002 FS library position() to return (size_t) -1 on error
  libraries/FS/src/FS.cpp
  libraries/FS/src/FS.h
Labels: Status: Pending Merge

#9999 fix(example): Add better WPS logging
  libraries/WiFi/examples/WPS/WPS.ino
Labels: Status: Pending Merge

#9979 docs(badge): Generate runtime tests badge
  .github/workflows/tests_results.yml
  README.md
Labels: Type: Documentation, Type: CI & Testing, Status: Pending Merge

#10005 docs(component): Update to IDF 5.1 and add component manager instructions
  docs/en/esp-idf_component.rst
Labels: Type: Documentation, Status: Pending Merge

#10012 fix(nodemcu-32s): Fix Upload Speed menu on Windows
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#10021 add(board): Add LOLIN S3 Mini Pro
  boards.txt
  variants/lolin_s3_mini_pro/pins_arduino.h
  variants/lolin_s3_mini_pro/variant.cpp
Labels: Status: Pending Merge, Type: 3rd party Boards

#10030 Update Zigbee_Temperature_Sensor.ino
  libraries/ESP32/examples/Zigbee/Zigbee_Temperature_Sensor/Zigbee_Temperature_Sensor.ino
Labels: Type: Example, Status: Pending Merge

#10016 change(board): Add default 16MB partition to esp32wroverkit
  boards.txt
Labels: Status: Pending Merge

#10013 ci(tests): Fix conclusion status and badge pushing
  .github/workflows/tests_results.yml
  .github/workflows/tests_wokwi.yml
Labels: Type: CI & Testing, Status: Pending Merge

#9942 add(board): Add M5Stack NanoC6 Dev Kit
  boards.txt
  variants/m5stack_nanoc6/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10035 SDMMC: Fix example code
  libraries/SD_MMC/examples/SDMMC_Test/SDMMC_Test.ino
Labels: Type: Example, Status: Pending Merge

#10034 v2.x: Fix RMT mutex unlock using incorrect channel number in rmtDeinit
  cores/esp32/esp32-hal-rmt.c
Labels: Area: Peripherals API, Status: Pending Merge

#10032 feat(ledc): Allow attaching multiple pins to 1 channel
  cores/esp32/esp32-hal-ledc.c
  cores/esp32/esp32-hal-ledc.h
  docs/en/api/ledc.rst
  libraries/ESP32/examples/AnalogOut/LEDCSingleChannel/LEDCSingleChannel.ino
Labels: Area: Peripherals API, Status: Pending Merge

#10038 IDF release/v5.1
  libraries/Network/src/NetworkInterface.cpp
  libraries/OpenThread/src/OThreadCLI.cpp
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10041 fix(libs): Update all libraries to match the core version
  .github/scripts/update-version.sh
  libraries/ArduinoOTA/library.properties
  libraries/AsyncUDP/library.properties
  libraries/BLE/library.properties
  libraries/BluetoothSerial/library.properties
  libraries/DNSServer/library.properties
  libraries/EEPROM/library.properties
  libraries/ESP32/library.properties
  libraries/ESP_I2S/library.properties
  libraries/ESP_NOW/library.properties
  libraries/ESP_SR/library.properties
  libraries/ESPmDNS/library.properties
  libraries/Ethernet/library.properties
  libraries/FFat/library.properties
  libraries/FS/library.properties
  libraries/HTTPClient/library.properties
  libraries/HTTPUpdate/library.properties
  libraries/HTTPUpdateServer/library.properties
  libraries/Insights/library.properties
  libraries/LittleFS/library.properties
  libraries/NetBIOS/library.properties
  libraries/Network/library.properties
  libraries/NetworkClientSecure/library.properties
  libraries/OpenThread/library.properties
  libraries/PPP/library.properties
  libraries/Preferences/library.properties
  libraries/RainMaker/library.properties
  libraries/SD/library.properties
  libraries/SD_MMC/library.properties
  libraries/SPI/library.properties
  libraries/SPIFFS/library.properties
  libraries/SimpleBLE/library.properties
  libraries/TFLiteMicro/library.properties
  libraries/Ticker/library.properties
  libraries/USB/library.properties
  libraries/Update/library.properties
  libraries/WebServer/library.properties
  libraries/WiFi/library.properties
  libraries/WiFiProv/library.properties
  libraries/Wire/library.properties
Labels: Status: Pending Merge

#10042 add(template): Add version 3.0.3 to the Issue template
  .github/ISSUE_TEMPLATE/Issue-report.yml
Labels: Status: Pending Merge

#10040 docs(lib-builder): Add missing requirements and examples
  docs/en/lib_builder.rst
Labels: Type: Documentation, Status: Pending Merge

#10044 Update analogContinuous function for passing pins as const and constexpr
  cores/esp32/esp32-hal-adc.c
  cores/esp32/esp32-hal-adc.h
  docs/en/api/adc.rst
Labels: Area: Peripherals API, Status: Pending Merge

#10043 PPP: add "battery status" read stub functions
  libraries/PPP/src/PPP.cpp
  libraries/PPP/src/PPP.h
Labels: Area: Libraries, Status: Pending Merge

#10063 fix(wfcs): Replaced expired certificate for howsmyssl.com
  libraries/NetworkClientSecure/examples/WiFiClientSecure/WiFiClientSecure.ino
Labels: Status: Pending Merge

#10067 ci(tests): Fix workflow errors
  .github/scripts/install-arduino-cli.sh
  .github/workflows/tests_hw.yml
Labels: Type: CI & Testing, hil_test, Status: Pending Merge

#10070 fix(gpio): add missing include for digitalPinCanOutput()
  cores/esp32/esp32-hal-gpio.h
Labels: Area: Peripherals API, Status: Pending Merge

#10072 feat(board): add Waveshare ESP32-S3-Matrix
  boards.txt
  variants/ws_esp32_s3_matrix/partitions_all_app_4MB.csv
  variants/ws_esp32_s3_matrix/partitions_otanofs_4MB.csv
  variants/ws_esp32_s3_matrix/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10069 fix(timer): Add check to avoid crashing
  cores/esp32/esp32-hal-timer.c
Labels: Area: Peripherals API, Status: Pending Merge

#9720 ci(wokwi): Pass diagram.json file if exists to pytest
  .github/scripts/tests_run.sh
  tests/requirements.txt
  tests/validation/gpio/diagram.esp32.json
  tests/validation/gpio/diagram.esp32c3.json
  tests/validation/gpio/diagram.esp32c6.json
  tests/validation/gpio/diagram.esp32h2.json
  tests/validation/gpio/diagram.esp32s2.json
  tests/validation/gpio/diagram.esp32s3.json
Labels: Type: CI & Testing, Status: Pending Merge

#10094 fix(ledc): Fix freeing channel if not used anymore
  cores/esp32/esp32-hal-ledc.c
Labels: Area: Peripherals API, Status: Pending Merge

#10097 fix(readme): Update badge for Build status
  README.md
Labels: Type: Documentation, Status: Pending Merge

#10075 fix(lwip): Add early out in `NetworkUDP::parsePacket()` when socket has no data
  libraries/Network/src/NetworkUdp.cpp
Labels: Area: Libraries, Status: Pending Merge

#10080 feat: Print chip features bitfield
  cores/esp32/chip-debug-report.cpp
Labels: Status: Pending Merge
