Repository espressif/arduino-esp32, pull requests merged in 2024-08, with the labels that each got.

#10098 IDF release/v5.1
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10096 fix(example): Update RainMaker examples to work with ESP32C6
  libraries/RainMaker/examples/RMakerCustom/RMakerCustom.ino
  libraries/RainMaker/examples/RMakerCustom/ci.json
  libraries/RainMaker/examples/RMakerCustomAirCooler/RMakerCustomAirCooler.ino
  libraries/RainMaker/examples/RMakerCustomAirCooler/ci.json
  libraries/RainMaker/examples/RMakerSonoffDualR3/ci.json
  libraries/RainMaker/examples/RMakerSwitch/RMakerSwitch.ino
  libraries/RainMaker/examples/RMakerSwitch/ci.json
Labels: Type: Example, Status: Pending Merge, Area: Rainmaker

#10101 fix(ssl): Add size arg to NetworkClientSecure::setCACertBundle
  libraries/NetworkClientSecure/src/NetworkClientSecure.cpp
  libraries/NetworkClientSecure/src/NetworkClientSecure.h
Labels: Area: Libraries, Status: Pending Merge

#10102 fix(ESP-NOW): Remove all peers on ESP_NOW.end()
  libraries/ESP_NOW/src/ESP32_NOW.cpp
  libraries/ESP_NOW/src/ESP32_NOW.h
Labels: Area: Libraries, Status: Pending Merge

#10104 ci(release): Add JSON install test
  .github/scripts/on-release.sh
Labels: Type: CI & Testing, Status: Pending Merge

#10100 feat(net): Add NAPT examples
  libraries/Ethernet/examples/ETH_WIFI_BRIDGE/ETH_WIFI_BRIDGE.ino
  libraries/Ethernet/examples/ETH_WIFI_BRIDGE/ci.json
  libraries/PPP/examples/PPP_WIFI_BRIDGE/PPP_WIFI_BRIDGE.ino
  libraries/PPP/examples/PPP_WIFI_BRIDGE/ci.json
  libraries/WiFi/examples/WiFiExtender/WiFiExtender.ino
  libraries/WiFi/examples/WiFiExtender/ci.json
Labels: Status: Pending Merge

#10066 Enabled the onboard ceramic antenna by default when creating a new project with XIAO_ESP32C6
  variants/XIAO_ESP32C6/pins_arduino.h
  variants/XIAO_ESP32C6/variant.cpp
Labels: Status: Pending Merge, Type: 3rd party Boards

#10106 fix(core): Update versions to 3.0.4
  cores/esp32/esp_arduino_version.h
  libraries/ArduinoOTA/library.properties
  libraries/AsyncUDP/library.properties
  libraries/BLE/library.properties
  libraries/BluetoothSerial/library.properties
  libraries/DNSServer/library.properties
  libraries/EEPROM/library.properties
  libraries/ESP32/library.properties
  libraries/ESP_I2S/library.properties
  libraries/ESP_NOW/library.properties
  libraries/ESP_SR/library.properties
  libraries/ESPmDNS/library.properties
  libraries/Ethernet/library.properties
  libraries/FFat/library.properties
  libraries/FS/library.properties
  libraries/HTTPClient/library.properties
  libraries/HTTPUpdate/library.properties
  libraries/HTTPUpdateServer/library.properties
  libraries/Insights/library.properties
  libraries/LittleFS/library.properties
  libraries/NetBIOS/library.properties
  libraries/Network/library.properties
  libraries/NetworkClientSecure/library.properties
  libraries/OpenThread/library.properties
  libraries/PPP/library.properties
  libraries/Preferences/library.properties
  libraries/RainMaker/library.properties
  libraries/SD/library.properties
  libraries/SD_MMC/library.properties
  libraries/SPI/library.properties
  libraries/SPIFFS/library.properties
  libraries/SimpleBLE/library.properties
  libraries/TFLiteMicro/library.properties
  libraries/Ticker/library.properties
  libraries/USB/library.properties
  libraries/Update/library.properties
  libraries/WebServer/library.properties
  libraries/WiFi/library.properties
  libraries/WiFiProv/library.properties
  libraries/Wire/library.properties
  package.json
  platform.txt
Labels: Status: Pending Merge

#10108 feat(board): Add CircuitART Zero S3 board
  boards.txt
  variants/circuitart_zero_s3/bootloader_tinyuf2.bin
  variants/circuitart_zero_s3/partitions_tinyuf2.csv
  variants/circuitart_zero_s3/pins_arduino.h
  variants/circuitart_zero_s3/tinyuf2.bin
Labels: Status: Pending Merge, Type: 3rd party Boards

#10111 Improving WebServer Example
  libraries/WebServer/examples/WebServer/README.md
  libraries/WebServer/examples/WebServer/WebServer.ino
Labels: Type: Example, Status: Pending Merge

#10113 docs: correct Float type size in Preferences API and Tutorial documentation
  docs/en/api/preferences.rst
  docs/en/tutorials/preferences.rst
Labels: Type: Documentation, Area: Libraries, Status: Pending Merge

#10118 Added variant for Waveshare ESP32-S3-Touch-LCD-1.69 & ESP32-S3-LCD-1.69 board
  boards.txt
  variants/waveshare_esp32_s3_lcd_169/pins_arduino.h
  variants/waveshare_esp32_s3_touch_lcd_169/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10122 Fix use after free in SD library
  libraries/SD/src/sd_diskio.cpp
Labels: Area: Libraries, Status: Pending Merge

#10123 fix(USB): OTG S2 and S3 debug print
  cores/esp32/esp32-hal-uart.c
Labels: Chip: ESP32-S2, Chip: ESP32-S3, Status: Pending Merge

#10125 fix(doc): analogReadMilliVolts
  docs/en/api/adc.rst
Labels: Type: Documentation, Status: Pending Merge

#10133 feat(RMaker): Register common events for better debugging
  libraries/RainMaker/src/RMaker.cpp
Labels: Status: Pending Merge, Area: Rainmaker

#10151 fix(wifiprov): Fix starting Wifi when already provisioned
  libraries/WiFiProv/src/WiFiProv.cpp
Labels: Status: Pending Merge, Area: WiFi

#10162 IDF release/v5.1
  CMakeLists.txt
  idf_component.yml
  libraries/Network/src/NetworkEvents.h
  libraries/RainMaker/examples/RMakerCustom/RMakerCustom.ino
  libraries/RainMaker/examples/RMakerCustomAirCooler/RMakerCustomAirCooler.ino
  libraries/RainMaker/examples/RMakerSonoffDualR3/RMakerSonoffDualR3.ino
  libraries/RainMaker/examples/RMakerSwitch/RMakerSwitch.ino
  libraries/WiFi/src/WiFiGeneric.cpp
  libraries/WiFi/src/WiFiGeneric.h
  libraries/WiFiProv/examples/WiFiProv/WiFiProv.ino
  libraries/WiFiProv/src/WiFiProv.cpp
  libraries/WiFiProv/src/WiFiProv.h
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10144 feat(board):Update M5Stack related board and pin configuration
  boards.txt
  variants/m5stack_dinmeter/pins_arduino.h
  variants/m5stack_tough/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10134 feat(board): Add Alfredo NoU3
  boards.txt
  variants/alfredo-nou3/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10143 feat(3rd party board): Add Fri3d Badge 2024 (ESP32-S3-WROOM-1)
  boards.txt
  variants/fri3d_2024_esp32s3/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10175 Added LILYGO T-Watch-S3 & T-Watch-Ultra variants
  boards.txt
  variants/lilygo_twatch_s3/pins_arduino.h
  variants/lilygo_twatch_ultra/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10172 Fix(UART): ESP32 | ESP32-S2 UART Clock Source
  cores/esp32/esp32-hal-uart.c
Labels: Chip: ESP32-S2, Status: Pending Merge, Peripheral: UART

#10147 docs(BLE): updated obsolete url in library.properties
  libraries/BLE/library.properties
Labels: Type: Documentation, Status: Pending Merge

#10148 docs(BLE): updated obsolete README.md
  libraries/BLE/README.md
Labels: Type: Documentation, Status: Pending Merge

#10128 Add ability for boards to provide a custom pixel order in neopixelWrite()
  cores/esp32/esp32-hal-rgb-led.c
  cores/esp32/esp32-hal-rgb-led.h
  variants/lolin_s3_mini/pins_arduino.h
Labels: Status: Pending Merge

#10201 IDF release/v5.1
  package/package_esp32_index.template.json
Labels: 🚫 System PR

#10210 ci(branches): Remove wildcard from branch triggers
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  .github/workflows/push.yml
Labels: Type: CI & Testing, Status: Pending Merge

#10216 change(build): add -Werror=return-type to default C and C++ flags
  platform.txt
  tools/platformio-build.py
Labels: Status: Pending Merge

#10222 fix(requirements): Avoid version conflicts
  docs/requirements.txt
  tests/requirements.txt
  tools/pre-commit/requirements.txt
Labels: Status: Pending Merge, Area: Tools & Build System

#10223 fix(tests): Use proper API and check for required token
  .github/scripts/tests_run.sh
  tests/validation/democfg/test_democfg.py
  tests/validation/hello_world/test_hello_world.py
  tests/validation/nvs/test_nvs.py
Labels: Type: CI & Testing, Status: Pending Merge

#10188 fix(get.py): Clear old files before extracting
  tools/get.py
Labels: Status: Pending Merge, Area: Tools & Build System

#10198 feat(board):Add Heltec Vision Master series boards
  boards.txt
  variants/heltec_vision_master_e290/pins_arduino.h
  variants/heltec_vision_master_e_213/pins_arduino.h
  variants/heltec_vision_master_t190/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10235 feat(boards): Add ESP32-2432S028R board support
  boards.txt
  variants/jczn_2432s028r/partitions_all_app_4MB.csv
  variants/jczn_2432s028r/partitions_otanofs_4MB.csv
  variants/jczn_2432s028r/pins_arduino.h
  variants/jczn_2432s028r/variant.cpp
Labels: Status: Pending Merge, Type: 3rd party Boards

#10241 Added variant for Waveshare ESP32-S3-Zero
  boards.txt
  tools/partitions/max_app_4MB.csv
  tools/partitions/ota_nofs_4MB.csv
  variants/waveshare_esp32_s3_zero/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10243 fix(chip): Return correct ESP32 chip model
  cores/esp32/Esp.cpp
Labels: Status: Pending Merge

#10233 ArduinoOTA - change occurrence of client.flush() to clear()
  libraries/ArduinoOTA/src/ArduinoOTA.cpp
Labels: Status: Pending Merge, Area: WiFi

#10234 WebServer - change occurrence of client.flush() to clear()
  libraries/WebServer/src/Parsing.cpp
Labels: Status: Pending Merge, Area: WiFi

#10242 fix(client): Make flush() call clear() and deprecate it
  libraries/Network/src/NetworkClient.cpp
  libraries/Network/src/NetworkClient.h
  libraries/Network/src/NetworkUdp.cpp
  libraries/Network/src/NetworkUdp.h
Labels: Status: Pending Merge, Area: WiFi

#10248 fix(uart): sleep retention
  cores/esp32/esp32-hal-uart.c
Labels: Status: Pending Merge, Peripheral: UART

#10231 docs(vale): Enable vale and fix errors
  .pre-commit-config.yaml
  .vale.ini
  docs/en/api/adc.rst
  docs/en/api/dac.rst
  docs/en/api/espnow.rst
  docs/en/api/i2c.rst
  docs/en/api/insights.rst
  docs/en/api/rainmaker.rst
  docs/en/api/touch.rst
  docs/en/api/usb.rst
  docs/en/api/wifi.rst
  docs/en/boards/ESP32-C3-DevKitM-1.rst
  docs/en/boards/ESP32-DevKitC-1.rst
  docs/en/boards/ESP32-S2-Saola-1.rst
  docs/en/boards/generic.rst
  docs/en/esp-idf_component.rst
  docs/en/getting_started.rst
  docs/en/guides/docs_contributing.rst
  docs/en/guides/tools_menu.rst
  docs/en/installing.rst
  docs/en/lib_builder.rst
  docs/en/migration_guides/2.x_to_3.0.rst
  docs/en/troubleshooting.rst
  docs/en/tutorials/partition_table.rst
  docs/en/tutorials/preferences.rst
  libraries/BLE/README.md
  libraries/EEPROM/README.md
  libraries/ESP32/examples/FreeRTOS/BasicMultiThreading/README.md
  libraries/ESP32/examples/Zigbee/Zigbee_Light_Bulb/README.md
  libraries/ESP32/examples/Zigbee/Zigbee_Light_Switch/README.md
  libraries/ESP32/examples/Zigbee/Zigbee_Temperature_Sensor/README.md
  libraries/ESP32/examples/Zigbee/Zigbee_Thermostat/README.md
  libraries/Insights/examples/DiagnosticsSmokeTest/README.md
  libraries/Insights/examples/MinimalDiagnostics/README.md
  libraries/LittleFS/examples/LITTLEFS_PlatformIO/README.md
  libraries/NetworkClientSecure/README.md
  libraries/README.md
  libraries/RainMaker/README.md
  libraries/RainMaker/examples/README.md
  libraries/SD/README.md
  libraries/SD_MMC/README.md
  libraries/WebServer/examples/MultiHomedServers/README.md
  libraries/WebServer/examples/WebServer/README.md
  libraries/WiFi/examples/WiFiClient/README.md
  libraries/WiFi/examples/WiFiClientConnect/README.md
  libraries/WiFi/examples/WiFiClientEnterprise/README.md
  libraries/WiFi/examples/WiFiScan/README.md
  libraries/WiFi/examples/WiFiScanAsync/README.md
  libraries/WiFi/examples/WiFiScanDualAntenna/README.md
  libraries/WiFi/examples/WiFiScanTime/README.md
  libraries/WiFiProv/examples/WiFiProv/README.md
Labels: Type: Documentation, Status: Pending Merge

#10255 fix(release): Fix release script to use new archive method
  .github/scripts/on-release.sh
Labels: Type: CI & Testing, Status: Pending Merge

#10256 fix(release): Fix install test on release
  .github/scripts/on-release.sh
Labels: Type: CI & Testing, Status: Pending Merge

#10258 IDF release/v5.3
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10259 fix(arduino): changes ESP32 definition in CMakeLists.txt file
  CMakeLists.txt
Labels: Status: Pending Merge, Area: Arduino as ESP-IDF component

#10217 fix(littlefs): Use VFSImpl::exists() to avoid false error log
  libraries/FFat/src/FFat.cpp
  libraries/FFat/src/FFat.h
  libraries/LittleFS/src/LittleFS.cpp
Labels: Status: Pending Merge, Status: Review needed

#10264 fix(ppp): Fix PPP not working after reboot if no RST
  libraries/PPP/src/PPP.cpp
Labels: Status: Pending Merge

#10267 ci(push): Use FQBN from ci.json
  .github/scripts/on-push.sh
Labels: Type: CI & Testing, Status: Pending Merge

#10269 fix(http): Replace flush() with clear() in HTTPClient
  libraries/HTTPClient/src/HTTPClient.cpp
Labels: Status: Pending Merge

#10260 ci(release): Make workflows dependent on release completion
  .github/workflows/docs_deploy.yml
  .github/workflows/upload-idf-component.yml
Labels: Type: CI & Testing, Status: Pending Merge
