Repository espressif/arduino-esp32, pull requests merged in 2024-05, with the labels that each got.

#9574 docs(flags): Add build system breaking changes to migration guide
  docs/en/migration_guides/2.x_to_3.0.rst
Labels: Type: Documentation, Status: Pending Merge, 3.0 migration

#9577 change(variant): add additional pin mappings and #define to variant/unphone9
  variants/unphone9/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#9581 Docs: Typo fix in installing guide
  docs/en/installing.rst
Labels: Type: Documentation, Status: Pending Merge

#9583 fix(config): Fix wrong names in Kconfig that cause Network and NetworkClientSecure to fail
  Kconfig.projbuild
Labels: Area: Libraries, Status: Pending Merge

#9560 ci(performance): Add performance tests to CI
  .flake8
  .github/scripts/sketch_utils.sh
  .github/scripts/tests_build.sh
  .github/scripts/tests_run.sh
  .github/workflows/hil.yml
  .pre-commit-config.yaml
  tests/.gitignore
  tests/performance/coremark/core_list_join.c
  tests/performance/coremark/core_main.c
  tests/performance/coremark/core_matrix.c
  tests/performance/coremark/core_portme.c
  tests/performance/coremark/core_portme.h
  tests/performance/coremark/core_state.c
  tests/performance/coremark/core_util.c
  tests/performance/coremark/coremark.h
  tests/performance/coremark/coremark.ino
  tests/performance/coremark/test_coremark.py
  tests/performance/fibonacci/fibonacci.ino
  tests/performance/fibonacci/test_fibonacci.py
  tests/performance/psramspeed/.skip.esp32c3
  tests/performance/psramspeed/.skip.esp32c6
  tests/performance/psramspeed/.skip.esp32h2
  tests/performance/psramspeed/psramspeed.ino
  tests/performance/psramspeed/test_psramspeed.py
  tests/performance/ramspeed/cfg.json
  tests/performance/ramspeed/ramspeed.ino
  tests/performance/ramspeed/test_ramspeed.py
  tests/performance/superpi/fftsg_h.cpp
  tests/performance/superpi/fftsg_h.h
  tests/performance/superpi/pi_fftcs.cpp
  tests/performance/superpi/pi_fftcs.h
  tests/performance/superpi/superpi.ino
  tests/performance/superpi/test_superpi.py
  tests/requirements.txt
  tests/validation/democfg/cfg.json
  tests/validation/democfg/democfg.ino
  tests/validation/democfg/test_democfg.py
  tests/validation/hello_world/hello_world.ino
  tests/validation/hello_world/test_hello_world.py
  tests/validation/nvs/cfg.json
  tests/validation/nvs/nvs.ino
  tests/validation/nvs/test_nvs.py
  tests/validation/periman/periman.ino
  tests/validation/periman/test_periman.py
  tests/validation/timer/test_timer.py
  tests/validation/timer/timer.ino
  tests/validation/touch/test_touch.py
  tests/validation/touch/touch.ino
  tests/validation/uart/test_uart.py
  tests/validation/uart/uart.ino
  tests/validation/unity/test_unity.py
  tests/validation/unity/unity.ino
Labels: Type: CI & Testing, hil_test, Status: Pending Merge, perf_test

#9597 feat(ci): Run Wokwi tests on PR
  .github/workflows/wokwi.yml
Labels: Type: CI & Testing, Status: Pending Merge

#9540 ci(wokwi): Add Wokwi emulator to workflow
  .github/scripts/tests_run.sh
  .github/workflows/hil.yml
  .github/workflows/publish.yml
  .github/workflows/wokwi.yml
  tests/.gitignore
  tests/performance/coremark/.skip.wokwi
  tests/performance/fibonacci/.skip.wokwi
  tests/performance/psramspeed/.skip.wokwi
  tests/performance/ramspeed/.skip.wokwi
  tests/performance/superpi/.skip.wokwi
  tests/pytest.ini
  tests/requirements.txt
  tests/validation/gpio/.skip.hardware
  tests/validation/gpio/.skip.qemu
  tests/validation/gpio/esp32.diagram.json
  tests/validation/gpio/esp32c3.diagram.json
  tests/validation/gpio/esp32c6.diagram.json
  tests/validation/gpio/esp32h2.diagram.json
  tests/validation/gpio/esp32s2.diagram.json
  tests/validation/gpio/esp32s3.diagram.json
  tests/validation/gpio/gpio.ino
  tests/validation/gpio/scenario.yaml
  tests/validation/gpio/test_gpio.py
  tests/validation/nvs/test_nvs.py
  tests/validation/periman/.skip.wokwi
  tests/validation/touch/.skip.wokwi
  tests/validation/uart/.skip.wokwi
  tests/validation/wifi/.skip.esp32h2
  tests/validation/wifi/.skip.hardware
  tests/validation/wifi/.skip.qemu
  tests/validation/wifi/cfg.json
  tests/validation/wifi/test_wifi.py
  tests/validation/wifi/wifi.ino
Labels: Type: CI & Testing, Status: Pending Merge

#9603 IDF release/v5.1
  package/package_esp32_index.template.json
Labels: Status: Pending Merge

#9594 fix(RAM): define HTTP_METHOD_STR as static const to save RAM
  libraries/WebServer/src/Parsing.cpp
Labels: Area: Libraries, Status: Pending Merge, Backport needed :back:

#9605 ci(hil): Touch skip file when platform is skipped
  .github/scripts/tests_run.sh
  .github/workflows/hil.yml
  .github/workflows/wokwi.yml
  tests/validation/touch/.skip.esp32c3
  tests/validation/touch/.skip.esp32c6
  tests/validation/touch/.skip.esp32h2
  tests/validation/touch/touch.ino
Labels: hil_test, Status: Pending Merge, perf_test

#9611 Arduino core for the esp32 - Add new function "bool isDirty()" to EEPROM.h and EEPROM.cpp
  libraries/EEPROM/src/EEPROM.cpp
  libraries/EEPROM/src/EEPROM.h
Labels: Status: Pending Merge

#9610 fix: I2C pin are relocated for arduino nano compatability
  variants/Geekble_ESP32C3/pins_arduino.h
Labels: Status: Pending Merge

#9609 BLEAdvertising.h: Fix spelling mistake in setScanFilter parameter
  libraries/BLE/src/BLEAdvertising.h
Labels: Status: Pending Merge

#9542 NetworkClient - close the connection in stop() method
  libraries/Network/src/NetworkClient.cpp
Labels: Type: CI & Testing, Status: Pending Merge, Area: WiFi

#9558 ci(qemu): Add QEMU emulator to CI
  .github/scripts/on-push.sh
  .github/scripts/sketch_utils.sh
  .github/scripts/tests_run.sh
  .github/workflows/hil.yml
  platform.txt
  tests/performance/coremark/.skip.qemu
  tests/performance/fibonacci/.skip.qemu
  tests/performance/psramspeed/.skip.qemu
  tests/performance/ramspeed/.skip.qemu
  tests/performance/superpi/.skip.qemu
  tests/pytest.ini
  tests/requirements.txt
  tests/validation/democfg/.skip.qemu
  tests/validation/nvs/.skip.qemu
  tests/validation/periman/.skip.qemu
  tests/validation/touch/.skip.qemu
  tests/validation/uart/.skip.qemu
Labels: Type: CI & Testing, Status: Pending Merge

#9613 IDF release/v5.1
  CMakeLists.txt
  cores/esp32/esp32-hal-tinyusb.c
  libraries/TFLiteMicro/examples/micro_speech/README.md
  libraries/TFLiteMicro/examples/micro_speech/audio_provider.cpp
  libraries/TFLiteMicro/examples/micro_speech/audio_provider.h
  libraries/TFLiteMicro/examples/micro_speech/command_responder.cpp
  libraries/TFLiteMicro/examples/micro_speech/command_responder.h
  libraries/TFLiteMicro/examples/micro_speech/feature_provider.cpp
  libraries/TFLiteMicro/examples/micro_speech/feature_provider.h
  libraries/TFLiteMicro/examples/micro_speech/micro_features_generator.cpp
  libraries/TFLiteMicro/examples/micro_speech/micro_features_generator.h
  libraries/TFLiteMicro/examples/micro_speech/micro_model_settings.cpp
  libraries/TFLiteMicro/examples/micro_speech/micro_model_settings.h
  libraries/TFLiteMicro/examples/micro_speech/micro_speech.ino
  libraries/TFLiteMicro/examples/micro_speech/model.cpp
  libraries/TFLiteMicro/examples/micro_speech/model.h
  libraries/TFLiteMicro/examples/micro_speech/recognize_commands.cpp
  libraries/TFLiteMicro/examples/micro_speech/recognize_commands.h
  libraries/TFLiteMicro/examples/micro_speech/ringbuf.c
  libraries/TFLiteMicro/examples/micro_speech/ringbuf.h
  package/package_esp32_index.template.json
Labels: Status: Pending Merge

#9623 Reduced GPIO17 (Ethernet clock GPIO) signal strength to reduce noise.
  variants/esp32-gateway/variant.cpp
Labels: Status: Pending Merge, Type: 3rd party Boards

#9621 docs(lib-builder): Add docker image documentation
  .gitignore
  docs/en/lib_builder.rst
Labels: Type: Documentation, Status: Pending Merge

#9625 ci(wokwi): Fix concurrency
  .github/workflows/hil.yml
  .github/workflows/publish.yml
  .github/workflows/wokwi.yml
Labels: Type: CI & Testing, Status: Pending Merge

#9635 fix(net): Add back the friend classes required for Ethernet.h to work
  cores/esp32/IPAddress.h
Labels: Status: Pending Merge

#9637 Fixes log with NULL ptr
  cores/esp32/esp32-hal-uart.c
Labels: Type: Bug :bug:, Status: Pending Merge, Peripheral: UART

#9632 NetworkClientSecure - copyability improvements and _timeout shadowing fixed
  libraries/NetworkClientSecure/src/NetworkClientSecure.cpp
  libraries/NetworkClientSecure/src/NetworkClientSecure.h
  libraries/NetworkClientSecure/src/ssl_client.cpp
  libraries/NetworkClientSecure/src/ssl_client.h
Labels: Status: Pending Merge

#9638 fix(ledc): Match channel number with groups
  cores/esp32/esp32-hal-ledc.c
Labels: Area: Peripherals API, Status: Pending Merge

#9628 fix(cdc): Disable SOF interrupt and CDC reset on begin()
  cores/esp32/HWCDC.cpp
  cores/esp32/HWCDC.h
  cores/esp32/USBCDC.cpp
  cores/esp32/esp32-hal-uart.c
Labels: Status: Pending Merge

#9640 feat(usb): Remove redundant absolute mouse support
  libraries/USB/examples/MIDI/MidiController/MidiController.ino
  libraries/USB/src/USBHIDMouse.h
  libraries/USB/src/tusb_hid_mouse.h
Labels: Status: Pending Merge

#9639 Add support for specifying a WPA2 EAP-TTLS phase 2 method to WiFi.begin
  libraries/WiFi/src/STA.cpp
  libraries/WiFi/src/WiFiSTA.cpp
  libraries/WiFi/src/WiFiSTA.h
Labels: Status: Pending Merge, Area: WiFi

#9642 Update(3rd_party_board): Updated ESPDuino with extra options
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#9653 feat (3rd_party_board): add support for WeAct Studio ESP32C3
  boards.txt
  variants/weact_studio_esp32c3/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#9658 fix(eth): Attach ETH events at the correct place
  libraries/Ethernet/src/ETH.cpp
Labels: Status: Pending Merge

#9659 feat(eth): Enable the possibility to use SPI ETH with only 4 wires
  libraries/Ethernet/src/ETH.h
Labels: Status: Pending Merge

#9661 fix(eth): Fix ETH.end()
  libraries/Ethernet/src/ETH.cpp
  libraries/Ethernet/src/ETH.h
Labels: Status: Pending Merge

#9665 Nano ESP32: delete `programmer.default` entry (on 2.0.x)
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#9666 Nano ESP32: delete `programmer.default` entry (on main)
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#9684 Update Kconfig.projbuild to fix LittleFS selective compilation
  Kconfig.projbuild
Labels: Status: Pending Merge, Area: Arduino as ESP-IDF component

#9680 docs(ledc.rst):Fixed outdated function signature (ledcWrite)
  docs/en/api/ledc.rst
Labels: Type: Documentation, Status: Pending Merge

#9693 fix(eth): Fix ETH.stop() with IDF SPI
  libraries/Ethernet/src/ETH.cpp
Labels: Status: Pending Merge

#9692 fix(adc): Remove masking for ADC channel number
  cores/esp32/esp32-hal-adc.c
Labels: Area: Peripherals API, Status: Pending Merge

#9688 feat(3rd_party_board):Add GPIO pin mappings for M5Stack CamS3 Unit and select OPI PSRAM by default
  boards.txt
  libraries/ESP32/examples/Camera/CameraWebServer/CameraWebServer.ino
  libraries/ESP32/examples/Camera/CameraWebServer/camera_pins.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#9686 fix(esp-hal-log):Provide a default TAG name for USE_ESP_IDF_LOG logging macro
  cores/esp32/esp32-hal-log.h
Labels: Status: Pending Merge

#9694 fix(release): Update merge_package.py
  .github/scripts/merge_packages.py
Labels: Status: Pending Merge

#9699 feat(reports): Update Issue-report.yml with new versions
  .github/ISSUE_TEMPLATE/Issue-report.yml
Labels: Status: Pending Merge

#9697 change(readme): Update C6 and H2 support
  README.md
Labels: Type: Documentation, Status: Pending Merge

#9698 fix(release): install missing 'packaging' package
  .github/workflows/release.yml
Labels: Status: Pending Merge

#9701 ci(wokwi): Self host Wokwi CLI server
  .github/scripts/tests_run.sh
  .github/workflows/hil.yml
  .github/workflows/wokwi.yml
Labels: Type: CI & Testing, Status: Pending Merge

#9703 fix(IDF): Define max IDF version for the component
  idf_component.yml
Labels: Status: Pending Merge, Area: Arduino as ESP-IDF component

#9708 fix(ci): Compare correct name of the artifact
  .github/workflows/publishlib.yml
  .github/workflows/publishsizes.yml
Labels: Type: CI & Testing, Status: Pending Merge

#9705 ci(external_libs): Add ZACwire to External libraries compilation test
  .github/workflows/lib.json
Labels: Type: CI & Testing, Status: Pending Merge, lib_test

#9683 Addition (3rd_party_board): Add board support for Autosport Labs ESP32-CAN-X2 development board
  boards.txt
  variants/aslcanx2/default_8MB_ffat.csv
  variants/aslcanx2/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#9706 fix(net): Don't unregister events if there are interfaces still open
  libraries/Ethernet/src/ETH.cpp
  libraries/Ethernet/src/ETH.h
  libraries/Network/src/NetworkInterface.cpp
  libraries/PPP/src/PPP.cpp
  libraries/WiFi/src/AP.cpp
  libraries/WiFi/src/STA.cpp
Labels: Status: Pending Merge

#9717 fix(boards): Remove duplicate VID/PID from boards.txt and add default CDC/JTAG board
  .github/scripts/find_new_boards.sh
  boards.txt
Labels: Status: Pending Merge

#9709 docs(libraries): Add new SoCs H2 and C6 to missing parts in docs
  docs/en/getting_started.rst
  docs/en/libraries.rst
  docs/en/tutorials/cdc_dfu_flash.rst
Labels: Type: Documentation, Status: Pending Merge

#9649 feat(tools):Use Windows native path separator in ESP_SR model copy command pattern
  .github/scripts/on-release.sh
  platform.txt
Labels: Status: Pending Merge

#9722 fix(variant): Arduino Nano ESP32 variant fix for core 3
  variants/arduino_nano_nora/dfu_callbacks.cpp
Labels: Status: Pending Merge, Type: 3rd party Boards

#9725 fix(net): Fix IPv4 address construction from ip_addr_t and comparison (#9724)
  cores/esp32/IPAddress.cpp
Labels: Status: Pending Merge

#9726 Updated UM boards for IDE2 & CLI
  boards.txt
  variants/um_rmp/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards
