Repository espressif/arduino-esp32, pull requests merged in 2024-09, with the labels that each got.

#10276 fix(boards): Correct typos in port prop. associations for "Bee" boards
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#10268 Update variants for M5Dial and M5StampS3
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#10262 Adds HW Serial CDC as IDF component example
  idf_component.yml
  idf_component_examples/hw_cdc_hello_world/CMakeLists.txt
  idf_component_examples/hw_cdc_hello_world/README.md
  idf_component_examples/hw_cdc_hello_world/main/CMakeLists.txt
  idf_component_examples/hw_cdc_hello_world/main/idf_component.yml
  idf_component_examples/hw_cdc_hello_world/main/main.cpp
  idf_component_examples/hw_cdc_hello_world/sdkconfig.defaults
Labels: Status: Pending Merge, Area: Arduino as ESP-IDF component

#10271 fix(boards): Remove port property assoc. for non-unique VID/PID pairs
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#10277 fix(report): Print correct chip revision
  cores/esp32/chip-debug-report.cpp
Labels: Status: Pending Merge

#10282 fix(scan): Make sure scan struct is cleared before set
  libraries/WiFi/src/WiFiScan.cpp
Labels: Status: Pending Merge

#10298 Added Unexpected Maker OMGS3
  boards.txt
  variants/um_omgs3/bootloader_tinyuf2.bin
  variants/um_omgs3/partitions_tinyuf2.csv
  variants/um_omgs3/pins_arduino.h
  variants/um_omgs3/tinyuf2.bin
Labels: Status: Pending Merge, Type: 3rd party Boards

#10300 update tinyuf2 for Adafruit boards to 0.20.1
  variants/adafruit_camera_esp32s3/bootloader-tinyuf2.bin
  variants/adafruit_camera_esp32s3/tinyuf2.bin
  variants/adafruit_feather_esp32s2/bootloader-tinyuf2.bin
  variants/adafruit_feather_esp32s2/tinyuf2.bin
  variants/adafruit_feather_esp32s2_reversetft/bootloader-tinyuf2.bin
  variants/adafruit_feather_esp32s2_reversetft/tinyuf2.bin
  variants/adafruit_feather_esp32s2_tft/bootloader-tinyuf2.bin
  variants/adafruit_feather_esp32s2_tft/tinyuf2.bin
  variants/adafruit_feather_esp32s3/bootloader-tinyuf2.bin
  variants/adafruit_feather_esp32s3/tinyuf2.bin
  variants/adafruit_feather_esp32s3_nopsram/bootloader-tinyuf2.bin
  variants/adafruit_feather_esp32s3_nopsram/tinyuf2.bin
  variants/adafruit_feather_esp32s3_reversetft/bootloader-tinyuf2.bin
  variants/adafruit_feather_esp32s3_reversetft/tinyuf2.bin
  variants/adafruit_feather_esp32s3_tft/bootloader-tinyuf2.bin
  variants/adafruit_feather_esp32s3_tft/tinyuf2.bin
  variants/adafruit_funhouse_esp32s2/bootloader-tinyuf2.bin
  variants/adafruit_funhouse_esp32s2/tinyuf2.bin
  variants/adafruit_magtag29_esp32s2/bootloader-tinyuf2.bin
  variants/adafruit_magtag29_esp32s2/tinyuf2.bin
  variants/adafruit_matrixportal_esp32s3/bootloader-tinyuf2.bin
  variants/adafruit_matrixportal_esp32s3/tinyuf2.bin
  variants/adafruit_metro_esp32s2/bootloader-tinyuf2.bin
  variants/adafruit_metro_esp32s2/tinyuf2.bin
  variants/adafruit_metro_esp32s3/bootloader-tinyuf2.bin
  variants/adafruit_metro_esp32s3/tinyuf2.bin
  variants/adafruit_qtpy_esp32s2/bootloader-tinyuf2.bin
  variants/adafruit_qtpy_esp32s2/tinyuf2.bin
  variants/adafruit_qtpy_esp32s3_n4r2/bootloader-tinyuf2.bin
  variants/adafruit_qtpy_esp32s3_n4r2/tinyuf2.bin
  variants/adafruit_qtpy_esp32s3_nopsram/bootloader-tinyuf2.bin
  variants/adafruit_qtpy_esp32s3_nopsram/tinyuf2.bin
  variants/adafruit_qualia_s3_rgb666/bootloader-tinyuf2.bin
  variants/adafruit_qualia_s3_rgb666/tinyuf2.bin
Labels: Status: Pending Merge, Type: 3rd party Boards

#10302 fix(ci): Log default FQBN if not passed as argument
  .github/scripts/sketch_utils.sh
Labels: Type: CI & Testing, Status: Pending Merge

#10305 Adds setToneChannel() implementation
  cores/esp32/Tone.cpp
Labels: Area: Peripherals API, Status: Pending Merge

#10299 OpenThread Example Improvement
  libraries/OpenThread/examples/SimpleThreadNetwork/ExtendedRouterNode/ExtendedRouterNode.ino
  libraries/OpenThread/examples/SimpleThreadNetwork/ExtendedRouterNode/ci.json
  libraries/OpenThread/examples/SimpleThreadNetwork/LeaderNode/LeaderNode.ino
  libraries/OpenThread/examples/SimpleThreadNetwork/RouterNode/RouterNode.ino
  libraries/OpenThread/keywords.txt
Labels: Type: Example, Status: Pending Merge

#10221 docs(contrib): Add instructions on how to test changes
  docs/en/contributing.rst
  docs/en/guides/docs_contributing.rst
Labels: Type: Documentation, Status: Pending Merge

#10313 fix(i2c): Ensure that semaphore is properly given if init fails
  cores/esp32/esp32-hal-i2c.c
Labels: Area: Peripherals API, Status: Pending Merge

#10312 fix(scan): Make sure that we do not leak memory if reading the APs fails
  libraries/WiFi/src/WiFiScan.cpp
Labels: Status: Pending Merge, Area: WiFi

#10324 feat(pre-commit): Add JSON formatter to pre-commit hooks
  .pre-commit-config.yaml
  libraries/ESP32/examples/HWCDC_Events/ci.json
  libraries/ESP_SR/examples/Basic/ci.json
  libraries/OpenThread/examples/COAP/coap_lamp/ci.json
  libraries/OpenThread/examples/COAP/coap_switch/ci.json
  libraries/OpenThread/examples/SimpleCLI/ci.json
  libraries/OpenThread/examples/SimpleNode/ci.json
  libraries/OpenThread/examples/SimpleThreadNetwork/ExtendedRouterNode/ci.json
  libraries/OpenThread/examples/SimpleThreadNetwork/LeaderNode/ci.json
  libraries/OpenThread/examples/SimpleThreadNetwork/RouterNode/ci.json
  libraries/OpenThread/examples/ThreadScan/ci.json
  libraries/OpenThread/examples/onReceive/ci.json
  libraries/SD_MMC/examples/SD2USBMSC/ci.json
  tests/performance/psramspeed/ci.json
  tests/performance/ramspeed/ci.json
  tests/validation/democfg/ci.json
  tests/validation/gpio/ci.json
  tests/validation/nvs/ci.json
  tests/validation/touch/ci.json
  tests/validation/wifi/ci.json
Labels: Type: CI & Testing, Status: Pending Merge, Area: Tools & Build System

#10321 fix(events): Fix crash in getStdFunctionAddress
  libraries/Network/src/NetworkEvents.cpp
Labels: Status: Pending Merge, Area: WiFi

#10328 fix(api): Update Arduino Stream class
  cores/esp32/Stream.cpp
  cores/esp32/Stream.h
Labels: Status: Pending Merge

#10331 fix(networking): NetworkClientRxBuffer::clear() may not always clear
  libraries/Network/src/NetworkClient.cpp
Labels: Status: Pending Merge, Area: WiFi

#10338 fix(arduino): rain maker common version
  idf_component.yml
Labels: Status: Pending Merge, Area: Arduino as ESP-IDF component

#10339 [WebServer] Mark functions as const + reduce copy of strings
  libraries/WebServer/src/Parsing.cpp
  libraries/WebServer/src/WebServer.cpp
  libraries/WebServer/src/WebServer.h
Labels: Area: Libraries, Status: Pending Merge

#10342 add waveshare_esp32_touch_amoled_241
  boards.txt
  variants/waveshare_esp32_touch_amoled_241/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10335 [WiFiScan] Allow allocation in _scanDone() to fail and prevent memory leak
  libraries/WiFi/src/WiFiScan.cpp
Labels: Status: Pending Merge

#10337 Fix(NetworkEvents): Don't skip event callbacks in NetworkEvents::remo…
  libraries/Network/src/NetworkEvents.cpp
  libraries/Network/src/NetworkEvents.h
Labels: Status: Pending Merge

#10293 change(esp_now_serial): No teardown on retry limit
  libraries/ESP_NOW/src/ESP32_NOW_Serial.cpp
  libraries/ESP_NOW/src/ESP32_NOW_Serial.h
Labels: Status: Pending Merge

#10345 Reduce copy of Strings in WebServer RequestHandler
  libraries/WebServer/examples/WebServer/WebServer.ino
  libraries/WebServer/src/detail/RequestHandler.h
  libraries/WebServer/src/detail/RequestHandlersImpl.h
Labels: Status: Pending Merge, Area: WiFi

#10355 fix(variant): Rename waveshare esp32-s3 board.
  boards.txt
  variants/waveshare_esp32_s3_touch_amoled_241/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10290 ESP Matter + Arduino as IDF Component Light example
  idf_component.yml
  idf_component_examples/esp_matter_light/CMakeLists.txt
  idf_component_examples/esp_matter_light/README.md
  idf_component_examples/esp_matter_light/main/CMakeLists.txt
  idf_component_examples/esp_matter_light/main/Kconfig.projbuild
  idf_component_examples/esp_matter_light/main/builtinLED.cpp
  idf_component_examples/esp_matter_light/main/builtinLED.h
  idf_component_examples/esp_matter_light/main/idf_component.yml
  idf_component_examples/esp_matter_light/main/matter_accessory_driver.cpp
  idf_component_examples/esp_matter_light/main/matter_accessory_driver.h
  idf_component_examples/esp_matter_light/main/matter_light.cpp
  idf_component_examples/esp_matter_light/partitions.csv
  idf_component_examples/esp_matter_light/sdkconfig.defaults.c6_thread
  idf_component_examples/esp_matter_light/sdkconfig.defaults.esp32c3
  idf_component_examples/esp_matter_light/sdkconfig.defaults.esp32c6
  idf_component_examples/esp_matter_light/sdkconfig.defaults.esp32s3
Labels: Area: Libraries, Status: Pending Merge

#10320 IDF release/v5.1
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10357 Update Matter Light README.md
  idf_component_examples/esp_matter_light/README.md
Labels: Status: Pending Merge

#10371 fix(esp32p4): Fix compilation errors
  cores/esp32/esp32-hal-i2c-slave.c
  cores/esp32/esp32-hal-spi.c
  cores/esp32/esp32-hal-touch.c
  libraries/BLE/examples/BLE5_multi_advertising/ci.json
  libraries/BLE/examples/BLE5_periodic_advertising/ci.json
  libraries/BLE/examples/BLE5_periodic_sync/ci.json
  libraries/BLE/examples/Beacon_Scanner/ci.json
  libraries/BLE/examples/Client/ci.json
  libraries/BLE/examples/Notify/ci.json
  libraries/BLE/examples/Server/ci.json
  libraries/BLE/examples/Server_multiconnect/ci.json
  libraries/BLE/examples/UART/ci.json
  libraries/BLE/examples/Write/ci.json
  libraries/BLE/examples/iBeacon/ci.json
  libraries/ESP32/examples/DeepSleep/TouchWakeUp/ci.json
  libraries/ESP32/examples/Touch/TouchButton/ci.json
  libraries/ESP32/examples/Touch/TouchButtonV2/ci.json
  libraries/ESP32/examples/Touch/TouchInterrupt/ci.json
  libraries/ESP32/examples/Touch/TouchRead/ci.json
  libraries/Ethernet/examples/ETH_LAN8720/ci.json
  libraries/Ethernet/examples/ETH_TLK110/ci.json
  libraries/OpenThread/examples/COAP/coap_switch/ci.json
  libraries/OpenThread/examples/SimpleCLI/ci.json
  libraries/OpenThread/examples/SimpleNode/ci.json
  libraries/OpenThread/examples/SimpleThreadNetwork/ExtendedRouterNode/ci.json
  libraries/SPI/examples/SPI_Multiple_Buses/SPI_Multiple_Buses.ino
  tests/validation/periman/ci.json
  tests/validation/touch/ci.json
  tests/validation/uart/uart.ino
  tests/validation/wifi/ci.json
  variants/esp32p4/pins_arduino.h
Labels: Type: Chip support, Status: Pending Merge

#10366 fix: DNSServer Lib - improper startup code in WiFi mode
  libraries/DNSServer/examples/CaptivePortal/CaptivePortal.ino
  libraries/DNSServer/src/DNSServer.cpp
Labels: Status: Pending Merge

#10382 Added Sparkfun ESP32-S3 Thing Plus board
  boards.txt
  variants/sparkfun_esp32s3_thing_plus/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards
