Repository espressif/arduino-esp32, pull requests merged in 2024-03, with the labels that each got.

#9313 ETH: Support physical address auto detection
  libraries/Ethernet/src/ETH.cpp
  libraries/Ethernet/src/ETH.h
Labels: Area: Libraries

#9319 HardwareSerial Available For Write
  cores/esp32/HardwareSerial.cpp
  cores/esp32/esp32-hal-uart.c
Labels: Status: Pending Merge, Peripheral: UART

#9323 Update binary.h
  cores/esp32/binary.h
Labels: Status: Pending Merge

#9325 ESP32-S3 PowerFeather Support for v2.x
  boards.txt
  tools/partitions/default_ffat_8MB.csv
  tools/partitions/large_ffat_8MB.csv
  tools/partitions/large_spiffs_8MB.csv
  variants/esp32s3_powerfeather/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#9333 Fix spiTransaction not updating clock line immediately (#9221)
  cores/esp32/esp32-hal-spi.c
Labels: Area: Peripherals API, hil_test

#9322 Fix compile branch master as Arduino as component with latest IDF 5.1
  cores/esp32/esp32-hal-tinyusb.c
Labels: Area: Arduino as ESP-IDF component, Status: Review needed

#9331 fix: perimgr + begin
  cores/esp32/HWCDC.cpp
Labels: Area: Peripherals API, hil_test, Status: Pending Merge

#9332 Add hardware tests results
  README.md
Labels: Type: CI & Testing, Status: Pending Merge

#9335 Fix spiTransaction not updating clock line immediately (C2,C6,H2)
  cores/esp32/esp32-hal-spi.c
Labels: Area: Peripherals API

#9338 Update upload and download artifact action to v4
  .github/workflows/docs_build.yml
  .github/workflows/hil.yml
  .github/workflows/lib.yml
Labels: Type: CI & Testing, hil_test, lib_test

#9343 Fix indentation for UART BLE example
  libraries/BLE/examples/UART/UART.ino
Labels: Type: Documentation, Type: Example

#9344 fix: HWCDC removed clearing USB Serial/JTAG interrupts during begin (#9316)
  cores/esp32/HWCDC.cpp
Labels: Area: Peripherals API

#9353 HardwareSerial:begin() changes RTS and CTS pins preventing detaching those pins
  cores/esp32/esp32-hal-uart.c
Labels: Status: Pending Merge, Peripheral: UART

#9349 Improve USBVendor Example
  cores/esp32/USB.cpp
  docs/_static/webusb.html
  docs/en/api/usb.rst
  libraries/USB/examples/USBVendor/USBVendor.ino
  libraries/USB/examples/USBVendor/index.html
  libraries/USB/src/USBVendor.cpp
  variants/esp32s2usb/pins_arduino.h
Labels: Type: Documentation, Area: Libraries, Type: Example, Status: Pending Merge

#9350 Fix documentation build instructions
  docs/en/guides/docs_contributing.rst
Labels: Type: Documentation, Status: Pending Merge

#9365 Fixes HW Serial attaching pins, PHY initialization, crash after end()
  cores/esp32/HWCDC.cpp
Labels: Type: Bug :bug:, Status: In Progress, Status: Pending Merge, Backport needed :back:

#9374 Fixes issue related to writing RGB LED fast in a row
  cores/esp32/esp32-hal-rgb-led.c
Labels: Type: Bug :bug:, Backport needed :back:

#9373 fix: UART0 boot pin setup
  cores/esp32/HardwareSerial.cpp
Labels: Type: Bug :bug:, Peripheral: UART, Backport needed :back:

#9367 Heltec ESP32 Series boards update
  boards.txt
  variants/heltec_capsule_sensor_v3/partitions.csv
  variants/heltec_capsule_sensor_v3/pins_arduino.h
  variants/heltec_ht_de01/pins_arduino.h
  variants/heltec_wireless_bridge/pins_arduino.h
  variants/heltec_wireless_mini_shell/pins_arduino.h
  variants/heltec_wireless_paper/pins_arduino.h
  variants/heltec_wireless_shell_v3/pins_arduino.h
  variants/heltec_wireless_stick_lite_v3/pins_arduino.h
  variants/heltec_wireless_stick_v3/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#9380 Platformio add `f_boot` to build script
  tools/platformio-build.py
Labels: IDE: PlaformIO, Status: Pending Merge

#9304 Feature: New Class MacAddress similar to IPAddress
  CMakeLists.txt
  cores/esp32/MacAddress.cpp
  cores/esp32/MacAddress.h
Labels: Type: Feature request, Area: BT&Wifi, Status: In Progress

#9390 Fixes for some boards which are failing CI test.
  .github/scripts/find_all_boards.sh
  cores/esp32/io_pin_remap.h
  variants/imbrios-logsens-v1p1/pins_arduino.h
Labels: Type: CI & Testing, Status: Pending Merge

#9389 Fixing typo in DiscoverConnect.ino BluetoothSerial example
  libraries/BluetoothSerial/examples/DiscoverConnect/DiscoverConnect.ino
Labels: Type: Example, Status: Pending Merge

#9398 Define Wire1 pins for ESP32-S3 PowerFeather
  variants/esp32s3_powerfeather/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#9399 Add board definition for ThingPulse ePulse Feather C6
  boards.txt
  variants/thingpulse_epulse_feather_c6/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#9400 Add MacAddress string constructor
  cores/esp32/MacAddress.cpp
  cores/esp32/MacAddress.h
Labels: Area: Libraries, Status: Pending Merge

#9386 Add variant for Waveshare ESP32-S3-Touch-LCD-1.28
  boards.txt
  variants/waveshare_esp32s3_touch_lcd_128/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#9405 Add method to set the WiFi radio channel
  libraries/WiFi/src/WiFiGeneric.cpp
  libraries/WiFi/src/WiFiGeneric.h
Labels: Area: Peripherals API, Status: Pending Merge, Area: WiFi

#9415 Adds a new example: onReceiveExample.ino
  libraries/ESP32/examples/Serial/onReceiveExample/onReceiveExample.ino
Labels: Type: Example, Status: Pending Merge, Peripheral: UART

#9417 [DOC] Add core compatibility guide
  docs/en/guides/core_compatibility.rst
Labels: Type: Documentation, Status: Pending Merge

#9422 Matched pin numbers in doco to numbers in variants files
  libraries/SD/README.md
  libraries/SD/examples/SD_Test/SD_Test.ino
  libraries/SD/examples/SD_time/SD_time.ino
Labels: Type: Documentation, Status: Pending Merge

#9431 Define Wire1 pins for ESP32-S3 PowerFeather
  variants/esp32s3_powerfeather/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards
