Repository espressif/arduino-esp32, pull requests merged in 2024-06, with the labels that each got.

#9738 Allow setting scan timeout in milliseconds
  libraries/WiFi/src/WiFiScan.cpp
  libraries/WiFi/src/WiFiScan.h
Labels: Status: Pending Merge

#9755 ci(sizes): Sites test between master and 2.x branch
  .github/workflows/publishsizes-2.x.yml
Labels: Type: CI & Testing, Status: Pending Merge

#9754 feat(boards): Add Zigbee menu for all C6/H2 boards
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#9759 Add missing parameter to esp32_family board for IDE1
  boards.txt
Labels: Status: Pending Merge

#9758 Fix getFlashChipMode breaking on S3 and C3
  cores/esp32/Esp.cpp
  cores/esp32/chip-debug-report.cpp
Labels: Status: Pending Merge

#9761 feat(usb): Support the new USB IDF API
  cores/esp32/esp32-hal-tinyusb.c
Labels: Status: Pending Merge

#9762 feat(idf): Require esp_psram when as component
  CMakeLists.txt
Labels: Status: Pending Merge

#9764 fix(idf): Require MDNS as public
  idf_component.yml
Labels: Status: Pending Merge, Area: Arduino as ESP-IDF component

#9763 fix(tls): do not attach bundle from runtime
  libraries/NetworkClientSecure/src/NetworkClientSecure.cpp
  libraries/NetworkClientSecure/src/ssl_client.cpp
  libraries/NetworkClientSecure/src/ssl_client.h
Labels: Status: Pending Merge

#9765 docs(component): Improve Arduino as component documentation
  docs/en/esp-idf_component.rst
Labels: Type: Documentation, Status: Pending Merge

#9767 fix(ssl): Fix load stream memory leak
  libraries/NetworkClientSecure/src/NetworkClientSecure.cpp
  libraries/NetworkClientSecure/src/NetworkClientSecure.h
Labels: Status: Pending Merge

#9769 feat(partition): Add 4MB No File System partition scheme
  boards.txt
  tools/partitions/no_fs.csv
Labels: Status: Pending Merge

#9760 fix(release): Shorten all toolchain names/versions
  .github/scripts/on-release.sh
Labels: Status: Pending Merge

#9773 fix(3rd party board): Changed Board name to describe board more clearly
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#9778 Updated Smart Bee Boards for IDE2 & CLI
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#9779 add upload_port vid/pid for Adafruit boards
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#9770 IDF release/v5.1
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#9781 fix(readme): Fix tests badge
  README.md
Labels: Type: Documentation, Status: Pending Merge

#9793 ci(refactor): Fix workflows and small improvements
  .github/scripts/tests_run.sh
  .github/workflows/build_tests.yml
  .github/workflows/hw.yml
  .github/workflows/pre-commit.yml
  .github/workflows/push.yml
  .github/workflows/qemu.yml
  .github/workflows/tests.yml
  .github/workflows/wokwi.yml
  tests/validation/gpio/ci.json
  tools/pre-commit/requirements.txt
Labels: Type: CI & Testing, Status: Pending Merge

#9801 change(idf): Rename component example and fix compilation warnings
  .github/workflows/build_tests.yml
  .github/workflows/hw.yml
  .github/workflows/push.yml
  .github/workflows/qemu.yml
  .github/workflows/wokwi.yml
  cores/esp32/MacAddress.cpp
  cores/esp32/esp32-hal-adc.c
  idf_component.yml
  idf_component_examples/hello_world/CMakeLists.txt
  idf_component_examples/hello_world/README.md
  idf_component_examples/hello_world/main/CMakeLists.txt
  idf_component_examples/hello_world/main/idf_component.yml
  idf_component_examples/hello_world/main/main.cpp
  idf_component_examples/hello_world/sdkconfig.defaults
  libraries/Ethernet/src/ETH.cpp
Labels: Type: CI & Testing, Status: Pending Merge, Area: Arduino as ESP-IDF component

#9805 ci(wifi): Add scan to wifi test
  tests/validation/wifi/test_wifi.py
  tests/validation/wifi/wifi.ino
Labels: Type: CI & Testing, Status: Pending Merge

#9796 feat(sdmmc): Add RAW disk functions
  libraries/SD_MMC/examples/SD2USBMSC/SD2USBMSC.ino
  libraries/SD_MMC/examples/SD2USBMSC/ci.json
  libraries/SD_MMC/src/SD_MMC.cpp
  libraries/SD_MMC/src/SD_MMC.h
Labels: Area: Libraries, Status: Pending Merge

#9839 ci(push): Fix sizes upload if there is no changes (2.x)
  .github/workflows/lib.yml
  .github/workflows/push.yml
Labels: Type: CI & Testing

#9829 fix(ci): Fix issues found in workflows
  .github/scripts/on-push.sh
  .github/scripts/set_push_chunks.sh
  .github/scripts/sketch_utils.sh
  .github/scripts/tests_run.sh
  .github/workflows/hw.yml
  .github/workflows/lib.yml
  .github/workflows/publishsizes-2.x.yml
  .github/workflows/push.yml
  .github/workflows/qemu.yml
  .github/workflows/wokwi.yml
Labels: Type: CI & Testing, Status: Pending Merge

#9821 feat(crypto): Add libsodium to the included components
  idf_component.yml
Labels: Status: Pending Merge

#9824 fix(client): Implement readBytes in NetworkClient for faster downloads
  libraries/Network/src/NetworkClient.cpp
  libraries/Network/src/NetworkClient.h
Labels: Status: Pending Merge

#9845 fix(client): Fix NetworkClient::localIP()
  libraries/Network/src/NetworkClient.cpp
Labels: Status: Pending Merge

#9832 Added support for removing routes in WebServer library
  libraries/WebServer/src/WebServer.cpp
  libraries/WebServer/src/WebServer.h
Labels: Area: Libraries, Status: Pending Merge

#9842 feat: added support for filters in WebServer library
  libraries/WebServer/examples/Filters/Filters.ino
  libraries/WebServer/examples/Filters/ci.json
  libraries/WebServer/src/Parsing.cpp
  libraries/WebServer/src/WebServer.cpp
  libraries/WebServer/src/WebServer.h
  libraries/WebServer/src/detail/RequestHandler.h
  libraries/WebServer/src/detail/RequestHandlersImpl.h
Labels: Area: Libraries, Status: Pending Merge

#9851 fix: removeRoute should remove all matching routes (WebServer)
  libraries/WebServer/src/WebServer.cpp
Labels: Area: Libraries, Status: Pending Merge

#9852 fix(ota): Magic byte check fails with encrypted firmware
  libraries/Update/src/Updater.cpp
Labels: Status: Pending Merge

#9853 fix(ota): Allow password and partition change while idle
  libraries/ArduinoOTA/src/ArduinoOTA.cpp
Labels: Status: Pending Merge

#9855 feat(uart): Add esp-modbus to the included components
  idf_component.yml
Labels: Status: Pending Merge

#9798 change (3rd_party_board): XIAO_C3 delete the definition of pin A3
  variants/XIAO_ESP32C3/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#9817 Add (3rd party board): DPTechnics Walter board support
  boards.txt
  variants/walter/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#9877 ci(boards): Add cache for libs
  .github/workflows/boards.yml
Labels: Type: CI & Testing, Status: Pending Merge

#9865 add(board): Add LILYGO T-ETH-Lite
  boards.txt
  variants/lilygo_t_eth_lite/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#9863 feat(http): Allow to set Accept-Encoding header
  libraries/HTTPClient/src/HTTPClient.cpp
  libraries/HTTPClient/src/HTTPClient.h
Labels: Status: Pending Merge

#9869 ClientSecure.available() fix for connection closed by remote socket
  libraries/NetworkClientSecure/src/NetworkClientSecure.cpp
  libraries/NetworkClientSecure/src/ssl_client.cpp
Labels: Status: Pending Merge, Area: WiFi

#9875 fix(BLE): Arduino String shall not be used within std::map<>
  libraries/BLE/src/BLEClient.cpp
  libraries/BLE/src/BLEClient.h
  libraries/BLE/src/BLERemoteCharacteristic.cpp
  libraries/BLE/src/BLERemoteCharacteristic.h
  libraries/BLE/src/BLERemoteService.cpp
  libraries/BLE/src/BLERemoteService.h
  libraries/BLE/src/BLEScan.cpp
  libraries/BLE/src/BLEScan.h
Labels: Type: Bug :bug:, Type: Regression, Status: Pending Merge, Area: BLE

#9857 fix: Update the root certificate for the BasicHttpsClient example
  libraries/HTTPClient/examples/BasicHttpsClient/BasicHttpsClient.ino
Labels: Type: Example, Status: Pending Merge

#9885 fix(netbios): Return interface address for NetBIOS name lookup
  libraries/NetBIOS/src/NetBIOS.cpp
Labels: Status: Pending Merge

#9886 fix(time): Fix SimpleTime to also use time servers from DHCP
  libraries/ESP32/examples/Time/SimpleTime/SimpleTime.ino
Labels: Type: Example, Status: Pending Merge

#9889 fix(boards): set XTAL 26MHz for Heltec WiFi & LoRa V1
  boards.txt
  variants/heltec_wifi_kit_32/pins_arduino.h
  variants/heltec_wifi_lora_32/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#9900 IDF release/v5.1
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#9901 docs(preferences): Fix getBool function
  docs/en/api/preferences.rst
Labels: Type: Documentation, Status: Pending Merge

#9897 Add variant for Elecrow CrowPanel 7.0"
  boards.txt
  variants/elecrow_crowpanel_7/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#9902 fix(version): Update version to 3.0.2
  .github/scripts/on-release.sh
  cores/esp32/esp_arduino_version.h
  package.json
  platform.txt
Labels: Status: Pending Merge

#9904 Deep Sleep Example Fix
  libraries/ESP32/examples/DeepSleep/ExternalWakeUp/ExternalWakeUp.ino
Labels: Type: Example, Status: Pending Merge

#9905 BluetoothSerial - Reduce bluetooth serial flush delay
  libraries/BluetoothSerial/src/BluetoothSerial.cpp
Labels: Status: Pending Merge

#9893 HTTPClient lib - add HTTPCLIENT_NOSECURE build flag
  libraries/HTTPClient/src/HTTPClient.cpp
  libraries/HTTPClient/src/HTTPClient.h
Labels: Area: Libraries, Status: Pending Merge

#9906 feat(rmt): Solve neopixel issue
  cores/esp32/esp32-hal-rmt.c
Labels: Area: Peripherals API, Status: Pending Merge

#9899 ci(tests): Avoid the use of pull_request_target where possible
  .github/workflows/tests.yml
  .github/workflows/tests_build.yml
  .github/workflows/tests_hw.yml
  .github/workflows/tests_qemu.yml
  .github/workflows/tests_results.yml
  .github/workflows/tests_wokwi.yml
  .github/workflows/wokwi.yml
Labels: Type: CI & Testing, Status: Pending Merge

#9916 docs(i2s): Fix I2S documentation example
  docs/en/advanced_utils.rst
  docs/en/api/i2s.rst
Labels: Type: Documentation, Type: Example, Status: Pending Merge

#9909 feat(net): Switch to typedefs for WiFiClient, WiFiServer, WiFiUdp and WiFiClientSecure
  Kconfig.projbuild
  libraries/NetworkClientSecure/src/WiFiClientSecure.h
  libraries/WebServer/examples/UploadHugeFile/UploadHugeFile.ino
  libraries/WiFi/src/WiFiClient.h
  libraries/WiFi/src/WiFiServer.h
  libraries/WiFi/src/WiFiUdp.h
Labels: Status: Pending Merge

#9925 Update boards.rst
  docs/en/boards/boards.rst
Labels: Type: Documentation, Status: Pending Merge

#9910 PPP: Make modem reset delay configurable
  libraries/PPP/examples/PPP_Basic/PPP_Basic.ino
  libraries/PPP/src/PPP.cpp
  libraries/PPP/src/PPP.h
Labels: Status: Pending Merge

#9908 New OpenThread CLI Arduino Library for ESP32-C6 and ESP32-H2
  CMakeLists.txt
  libraries/OpenThread/README.md
  libraries/OpenThread/examples/COAP/coap_lamp/ci.json
  libraries/OpenThread/examples/COAP/coap_lamp/coap_lamp.ino
  libraries/OpenThread/examples/COAP/coap_switch/ci.json
  libraries/OpenThread/examples/COAP/coap_switch/coap_switch.ino
  libraries/OpenThread/examples/SimpleCLI/SimpleCLI.ino
  libraries/OpenThread/examples/SimpleCLI/ci.json
  libraries/OpenThread/examples/SimpleNode/SimpleNode.ino
  libraries/OpenThread/examples/SimpleNode/ci.json
  libraries/OpenThread/examples/SimpleThreadNetwork/LeaderNode/LeaderNode.ino
  libraries/OpenThread/examples/SimpleThreadNetwork/LeaderNode/ci.json
  libraries/OpenThread/examples/SimpleThreadNetwork/RouterNode/RouterNode.ino
  libraries/OpenThread/examples/SimpleThreadNetwork/RouterNode/ci.json
  libraries/OpenThread/examples/ThreadScan/ThreadScan.ino
  libraries/OpenThread/examples/ThreadScan/ci.json
  libraries/OpenThread/examples/onReceive/ci.json
  libraries/OpenThread/examples/onReceive/onReceive.ino
  libraries/OpenThread/helper_functions.md
  libraries/OpenThread/keywords.txt
  libraries/OpenThread/library.properties
  libraries/OpenThread/src/OThreadCLI.cpp
  libraries/OpenThread/src/OThreadCLI.h
  libraries/OpenThread/src/OThreadCLI_Util.cpp
  libraries/OpenThread/src/OThreadCLI_Util.h
Labels: Area: Libraries, Status: Pending Merge

#9930 fix(boards): boards.txt error
  boards.txt
Labels: Status: Pending Merge

#9928 IDF release/v5.1
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#9934 fix(idf): Require openthread on H2 and C6
  CMakeLists.txt
Labels: Status: Pending Merge, 🚫 System PR

#9841 feat(3rd party board): Adding ViraLink IoT Gate Boards
  boards.txt
  variants/ViraLink-G0.1/pins_arduino.h
  variants/ViraLink-G1.1/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#9932 ci(tests): Fix cache cleaning
  .github/workflows/tests_results.yml
Labels: Type: CI & Testing, Status: Pending Merge

#9941 RMT Legacy Driver option
  .pre-commit-config.yaml
  cores/esp32/esp32-hal-gpio.c
  libraries/ESP32/examples/RMT/Legacy_RMT_Driver_Compatible/Legacy_RMT_Driver_Compatible.ino
  libraries/ESP32/examples/RMT/Legacy_RMT_Driver_Compatible/build_opt.h
Labels: Status: Pending Merge

#9946 Fixes WiFiProv.ino
  libraries/WiFiProv/examples/WiFiProv/WiFiProv.ino
Labels: Area: BT&Wifi, Status: Pending Merge
