Repository espressif/arduino-esp32, pull requests merged in 2025-04, with the labels that each got.

#11205 feat(zigbee): Add PM2.5 endpoint support
  CMakeLists.txt
  libraries/Zigbee/examples/Zigbee_PM25_Sensor/README.md
  libraries/Zigbee/examples/Zigbee_PM25_Sensor/Zigbee_PM25_Sensor.ino
  libraries/Zigbee/examples/Zigbee_PM25_Sensor/ci.json
  libraries/Zigbee/src/Zigbee.h
  libraries/Zigbee/src/ep/ZigbeePM25Sensor.cpp
  libraries/Zigbee/src/ep/ZigbeePM25Sensor.h
Labels: Status: Pending Merge, Area: Zigbee

#11199 fix(zigbeeEP): review of names and memory allocation
  libraries/Zigbee/src/ZigbeeEP.cpp
  libraries/Zigbee/src/ZigbeeEP.h
Labels: Status: Pending Merge, Area: Zigbee

#11191 Add an option to force IDF's default UART clock source
  cores/esp32/HardwareSerial.cpp
  cores/esp32/HardwareSerial.h
  cores/esp32/esp32-hal-uart.c
  cores/esp32/esp32-hal-uart.h
Labels: Status: Pending Merge, Peripheral: UART

#11206 fix(board): Alfredo NoU3 pins_arduino.h uses uint8_t but it causes error with esp32-hal-gpio.h
  variants/alfredo-nou3/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#11210 feat(zigbee): Add battery voltage attribute support
  libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/Zigbee_Temp_Hum_Sensor_Sleepy.ino
  libraries/Zigbee/src/ZigbeeEP.cpp
  libraries/Zigbee/src/ZigbeeEP.h
Labels: Status: Pending Merge, Area: Zigbee

#11214 Use CONFIG_BT_BLUEDROID_ENABLED for enabling
  cores/esp32/esp32-hal-bt.c
Labels: Area: BT&Wifi, Status: Pending Merge, Area: BLE

#11221 refactor(rmt): refactored RMT loopback example
  libraries/ESP32/examples/RMT/RMTLoopback/RMTLoopback.ino
Labels: Type: Example, Status: Pending Merge

#11222 fix(usb): uninitilized variable warning message
  cores/esp32/USB.cpp
Labels: Type: Bug :bug:, Area: Peripherals API, Status: Pending Merge

#11227 feat(usb): add a few more consumer control HID commands
  libraries/USB/src/USBHIDConsumerControl.h
Labels: Area: Peripherals API, Status: Pending Merge

#11242 fix(usb_hid): duplicated CONSUMER_CONTROL_PLAY_PAUSE
  libraries/USB/src/USBHIDConsumerControl.h
Labels: Area: Peripherals API, Status: Pending Merge

#11159 feat(logging): Arduino log redirection
  cores/esp32/HWCDC.cpp
  cores/esp32/USBCDC.cpp
  cores/esp32/esp32-hal-uart.c
Labels: Status: Pending Merge, Peripheral: UART

#11234 check for `CONFIG_BT_BLUEDROID_ENABLED` in esp32-hal-misc.c
  cores/esp32/esp32-hal-misc.c
Labels: Status: Pending Merge, Area: BLE

#11239 fix(wifi): Workaround bug in esp_wifi_get_protocol()
  libraries/WiFi/src/WiFiGeneric.cpp
Labels: Status: Pending Merge, Area: WiFi

#11255 fix(esp32c5): Add proper RTC clock source to uartSetClockSource
  cores/esp32/esp32-hal-uart.c
Labels: Status: Review needed

#11268 fix(gpio): Fix GPIO warning message
  cores/esp32/esp32-hal-gpio.c
Labels: Status: Pending Merge

#11267 docs(language): Enforce English on contributions and issues
  .github/ISSUE_TEMPLATE/Feature-request.yml
  .github/ISSUE_TEMPLATE/Issue-report.yml
  docs/en/contributing.rst
Labels: Type: Documentation, Status: Pending Merge

#11271 i2c_ll_enable_arbitration(i2c->dev, true)
  cores/esp32/esp32-hal-i2c-slave.c
Labels: Status: Pending Merge

#11204 IDF master
  libraries/ESP_NOW/src/ESP32_NOW.cpp
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#11276 feat(ledc): clear all fields added to ledc struct in IDF 5.4
  cores/esp32/esp32-hal-ledc.c
Labels: Status: Pending Merge

#11286 feat(uart): sets correct ESP32/S2 clock source for the example
  libraries/ESP32/examples/Serial/RxTimeout_Demo/RxTimeout_Demo.ino
Labels: Status: Pending Merge, Peripheral: UART

#11240 ci(idf): Use included IDF examples in CI
  .github/scripts/on-push-idf.sh
  .github/scripts/sketch_utils.sh
  .github/workflows/push.yml
  idf_component_examples/.gitignore
  idf_component_examples/esp_matter_light/CMakeLists.txt
  idf_component_examples/esp_matter_light/README.md
  idf_component_examples/esp_matter_light/ci.json
  idf_component_examples/esp_matter_light/main/Kconfig.projbuild
  idf_component_examples/esp_matter_light/main/idf_component.yml
  idf_component_examples/esp_matter_light/sdkconfig.defaults
  idf_component_examples/esp_matter_light/sdkconfig.defaults.esp32c3
  idf_component_examples/esp_matter_light/sdkconfig.defaults.esp32c6
  idf_component_examples/hello_world/CMakeLists.txt
  idf_component_examples/hw_cdc_hello_world/CMakeLists.txt
  idf_component_examples/hw_cdc_hello_world/ci.json
Labels: Type: CI & Testing, Status: Pending Merge, Area: Arduino as ESP-IDF component

#11288 ci(release): Add package JSON with chinese mirrors
  .github/scripts/on-release.sh
Labels: Type: CI & Testing, Status: Pending Merge

#11299 Update LilyGo T-Watch-S3-Ultra and T-LoRa-Pager variants
  boards.txt
  variants/lilygo_tlora_pager/pins_arduino.h
  variants/lilygo_twatch_s3/pins_arduino.h
  variants/lilygo_twatch_ultra/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#11292 feat(rmt): fixes example to run correctly within IDF 5.x
  libraries/ESP32/examples/RMT/RMT_LED_Blink/RMT_LED_Blink.ino
Labels: Area: Libraries, Type: Example, Status: Pending Merge

#11297 New SPI invert hardware SS function in hall-spi and SPI library
  cores/esp32/esp32-hal-spi.c
  cores/esp32/esp32-hal-spi.h
  libraries/SPI/src/SPI.cpp
  libraries/SPI/src/SPI.h
Labels: Area: Libraries, Status: Pending Merge

#11315 Restore proper pin remapping functionality after 3.2.0
  cores/esp32/Arduino.h
Labels: Status: Pending Merge

#11309 feat(uart): simplifies UART example based on MODBUS standard
  libraries/ESP32/examples/Serial/onReceiveExample/onReceiveExample.ino
Labels: Type: Example, Status: Pending Merge, Peripheral: UART

#11317 docs(mirror): Add Chinese mirror links
  docs/en/installing.rst
  docs/en/troubleshooting.rst
Labels: Type: Documentation, Status: Pending Merge

#11320 fix(spi): Add missing initializer for ss_invert
  cores/esp32/esp32-hal-spi.c
Labels: Status: Pending Merge

#11289 IDF master
  cores/esp32/esp32-hal-i2c-slave.c
  idf_component.yml
  libraries/BluetoothSerial/src/BTAddress.cpp
  libraries/BluetoothSerial/src/BTAddress.h
  libraries/BluetoothSerial/src/BTAdvertisedDevice.h
  libraries/BluetoothSerial/src/BTAdvertisedDeviceSet.cpp
  libraries/BluetoothSerial/src/BTScan.h
  libraries/BluetoothSerial/src/BTScanResultsSet.cpp
  libraries/BluetoothSerial/src/BluetoothSerial.cpp
  libraries/BluetoothSerial/src/BluetoothSerial.h
  libraries/SimpleBLE/examples/SimpleBleDevice/ci.json
  libraries/SimpleBLE/src/SimpleBLE.cpp
  libraries/SimpleBLE/src/SimpleBLE.h
  package/package_esp32_index.template.json
Labels: 🚫 System PR
