Repository espressif/arduino-esp32, pull requests merged in 2025-08, with the labels that each got.

#11673 ci(component): Move component compilation to a separate workflow
  .github/scripts/set_push_chunks.sh
  .github/workflows/build_component.yml
  .github/workflows/push.yml
  .github/workflows/tests.yml
Labels: Type: CI & Testing, Status: Pending Merge

#11677 feat(esp32): Added a new device(xiao esp32c5)
  boards.txt
  variants/XIAO_ESP32C5/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#11678 variant lilyho_t3_s3_sx127x duplicates LORA_BUSY - deleting one of them
  variants/lilygo_t3_s3_sx127x/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#11689 fix(esp32:m5stack_atoms3) : Update pins_arduino.h of variant m5stack_atoms3 with correct LED_BUILTIN value matching GPIO #35
  variants/m5stack_atoms3/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#11692 change(partitions): Reorder No OTA TinyUF2 partition scheme to come first on 4MB boards
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#11746 fix: Use correct category for ESP_NOW
  libraries/ESP_NOW/library.properties
Labels: Status: Pending Merge

#11698 Added FoBE Quill ESP32S3 Mesh board support
  boards.txt
  variants/fobe_quill_esp32s3_mesh/bootloader-tinyuf2.bin
  variants/fobe_quill_esp32s3_mesh/pins_arduino.h
  variants/fobe_quill_esp32s3_mesh/tinyuf2.bin
  variants/fobe_quill_esp32s3_mesh/variant.cpp
Labels: Status: Pending Merge, Type: 3rd party Boards

#11753 fix(docs): Updates SPI reference link in documentation
  docs/en/api/spi.rst
Labels: Type: Documentation, Status: Pending Merge

#11772 feat(zigbee): Update esp-zigbee-lib to 1.6.7
  idf_component.yml
Labels: Status: Pending Merge, Area: Zigbee

#11751 BLE: `BLECharacteristic::setValue()` cleanup and optimization
  libraries/BLE/src/BLE2901.cpp
  libraries/BLE/src/BLE2901.h
  libraries/BLE/src/BLECharacteristic.cpp
  libraries/BLE/src/BLECharacteristic.h
  libraries/BLE/src/BLEDescriptor.cpp
  libraries/BLE/src/BLEDescriptor.h
  libraries/BLE/src/BLEValue.cpp
  libraries/BLE/src/BLEValue.h
Labels: Status: Pending Merge, Area: BLE

#11766 Add function to handle library installation from ci.json
  .github/scripts/sketch_utils.sh
  docs/en/contributing.rst
Labels: Type: CI & Testing, Status: Pending Merge

#11643 feat(touch): Support all touch versions in NG driver
  .github/scripts/tests_run.sh
  CMakeLists.txt
  cores/esp32/esp32-hal-touch-ng.c
  cores/esp32/esp32-hal-touch-ng.h
  cores/esp32/esp32-hal-touch.c
  cores/esp32/esp32-hal-touch.h
  libraries/ESP32/examples/Touch/TouchButton/TouchButton.ino
  libraries/ESP32/examples/Touch/TouchButton/ci.json
  libraries/ESP32/examples/Touch/TouchButtonV2/TouchButtonV2.ino
  libraries/ESP32/examples/Touch/TouchButtonV2/ci.json
  libraries/ESP32/examples/Touch/TouchInterrupt/TouchInterrupt.ino
  libraries/ESP32/examples/Touch/TouchRead/TouchRead.ino
  tests/validation/touch/ci.json
  tests/validation/touch/touch.ino
Labels: Area: Peripherals API, hil_test, Status: Pending Merge
