Repository espressif/arduino-esp32, pull requests merged in 2025-10, with the labels that each got.

#11890 ci(tests): Move hardware tests to GitLab
  .github/scripts/tests_matrix.sh
  .github/workflows/tests.yml
  .github/workflows/tests_hw.yml
  .github/workflows/tests_hw_wokwi.yml
  .github/workflows/tests_results.yml
  .gitlab-ci.yml
  .gitlab/scripts/gen_hw_jobs.py
  .gitlab/scripts/get_artifacts.sh
  .gitlab/scripts/get_results.sh
  .gitlab/workflows/common.yml
  .gitlab/workflows/hardware_tests_dynamic.yml
  .gitlab/workflows/hw_test_template.yml
  .gitlab/workflows/sample.yml
  tests/performance/coremark/test_coremark.py
  tests/performance/fibonacci/test_fibonacci.py
  tests/performance/linpack_double/test_linpack_double.py
  tests/performance/linpack_float/test_linpack_float.py
  tests/performance/psramspeed/ci.json
  tests/performance/psramspeed/test_psramspeed.py
  tests/performance/ramspeed/test_ramspeed.py
  tests/performance/superpi/test_superpi.py
  tests/requirements.txt
  tests/validation/psram/ci.json
  tests/validation/wifi/ci.json
Labels: Type: CI & Testing, Status: Pending Merge

#11903 Runtime Flash Clock detection
  cores/esp32/Esp.cpp
  cores/esp32/Esp.h
  cores/esp32/chip-debug-report.cpp
Labels: Status: Pending Merge

#11853 IDF release/v5.5
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR
