Repository espressif/arduino-esp32, pull requests merged in 2025-07, with the labels that each got.

#11534 pioarduino only: make adresses for partitions.bin and boot_app0.bin configureable
  tools/pioarduino-build.py
Labels: Status: Pending Merge

#11530 fix(csrf): Fix SCRF vulnerability in OTA examples and libraries
  libraries/HTTPUpdateServer/src/HTTPUpdateServer.h
  libraries/Update/examples/OTAWebUpdater/OTAWebUpdater.ino
  libraries/WebServer/examples/WebUpdate/WebUpdate.ino
Labels: Status: Pending Merge

#11485 feat(board): add support for RAKwireless RAK3112
  boards.txt
  variants/rakwireless_rak3112/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#11528 Update ZigbeeColorDimmableLight to clamp color hue and saturation to 0-254 (Fixes #11527)
  libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.cpp
Labels: Status: Pending Merge, Area: Zigbee

#11532 fix(board): Update variant.cpp for senseBox MCU-S2 ESP32-S2
  boards.txt
  variants/sensebox_mcu_esp32s2/APOTA.bin
  variants/sensebox_mcu_esp32s2/APOTA.ino
  variants/sensebox_mcu_esp32s2/variant.cpp
Labels: Status: Pending Merge, Type: 3rd party Boards

#11543 IDF release/v5.5
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#11547 fix(spi): Fix bus clock for ESP32-P4 + remove S2 leftover
  cores/esp32/esp32-hal-spi.c
Labels: Area: Peripherals API, Status: Pending Merge

#11545 Add Deneyap Kart v2
  boards.txt
  variants/deneyapkartv2/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#11552 fix(board): Update PSRAM configuration for RAK3112 to fix PSRAM error
  boards.txt
  variants/rakwireless_rak3112/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#11556 pioarduino only: fix deprecated warnings caused from esptool v5.0.0
  tools/pioarduino-build.py
Labels: Status: Pending Merge

#11559 feat(zigbee): Add Fan Control endpoint support
  CMakeLists.txt
  libraries/Zigbee/examples/Zigbee_Fan_Control/README.md
  libraries/Zigbee/examples/Zigbee_Fan_Control/Zigbee_Fan_Control.ino
  libraries/Zigbee/examples/Zigbee_Fan_Control/ci.json
  libraries/Zigbee/keywords.txt
  libraries/Zigbee/src/Zigbee.h
  libraries/Zigbee/src/ep/ZigbeeFanControl.cpp
  libraries/Zigbee/src/ep/ZigbeeFanControl.h
Labels: Status: Pending Merge, Area: Zigbee

#11565 fix(dangerjs): Disable target branch rule
  .github/workflows/dangerjs.yml
Labels: Type: CI & Testing, Status: Pending Merge

#11566 Backport: pioarduino only change for esptool v5.0.0 support
  tools/pioarduino-build.py
Labels: Status: Pending Merge

#11562 change(esptool): Upgrade esptool to release v5.0.0 (3.2.x)
  .github/scripts/package_esptool.sh
  .github/scripts/update_esptool.py
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, Area: Tools & Build System

#11561 feat(matter): new matter example
  libraries/Matter/examples/MatterLambdaSingleCallbackManyEPs/MatterLambdaSingleCallbackManyEPs.ino
  libraries/Matter/examples/MatterLambdaSingleCallbackManyEPs/ci.json
  libraries/Matter/keywords.txt
Labels: Status: Pending Merge, Area: Matter

#11582 feat(wire): std::functional Wire slave callback functions
  cores/esp32/HardwareI2C.h
  docs/en/api/i2c.rst
  libraries/Wire/examples/WireSlaveFunctionalCallback/WireSlaveFunctionalCallback.ino
  libraries/Wire/examples/WireSlaveFunctionalCallback/ci.json
  libraries/Wire/src/Wire.cpp
  libraries/Wire/src/Wire.h
Labels: Type: Feature request, Area: Peripherals API, Status: Pending Merge

#11589 feat(gpio): new functional interrupt lambda example
  libraries/ESP32/examples/GPIO/FunctionalInterruptLambda/FunctionalInterruptLambda.ino
  libraries/ESP32/examples/GPIO/FunctionalInterruptLambda/README.md
Labels: Area: Peripherals API, Type: Example, Status: Pending Merge

#11601 IDF release/v5.5
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#11614 fix(zigbee): Replace assert with error log to solve immediate crash
  libraries/Zigbee/src/ZigbeeCore.cpp
Labels: Status: Pending Merge, Area: Zigbee

#11525 feat(docs): Add Zigbee library API documentation
  docs/en/libraries.rst
  docs/en/zigbee/ep_analog.rst
  docs/en/zigbee/ep_binary.rst
  docs/en/zigbee/ep_carbon_dioxide_sensor.rst
  docs/en/zigbee/ep_color_dimmable_light.rst
  docs/en/zigbee/ep_color_dimmer_switch.rst
  docs/en/zigbee/ep_contact_switch.rst
  docs/en/zigbee/ep_dimmable_light.rst
  docs/en/zigbee/ep_door_window_handle.rst
  docs/en/zigbee/ep_electrical_measurement.rst
  docs/en/zigbee/ep_flow_sensor.rst
  docs/en/zigbee/ep_gateway.rst
  docs/en/zigbee/ep_illuminance_sensor.rst
  docs/en/zigbee/ep_light.rst
  docs/en/zigbee/ep_occupancy_sensor.rst
  docs/en/zigbee/ep_pm25_sensor.rst
  docs/en/zigbee/ep_power_outlet.rst
  docs/en/zigbee/ep_pressure_sensor.rst
  docs/en/zigbee/ep_range_extender.rst
  docs/en/zigbee/ep_switch.rst
  docs/en/zigbee/ep_temperature_sensor.rst
  docs/en/zigbee/ep_thermostat.rst
  docs/en/zigbee/ep_vibration_sensor.rst
  docs/en/zigbee/ep_wind_speed_sensor.rst
  docs/en/zigbee/ep_window_covering.rst
  docs/en/zigbee/zigbee.rst
  docs/en/zigbee/zigbee_core.rst
  docs/en/zigbee/zigbee_ep.rst
Labels: Type: Documentation, Status: Pending Merge, Area: Zigbee

#11623 IDF release/v5.5
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#11625 fix(tamc_termod_s3): Fix header includes
  variants/tamc_termod_s3/pins_arduino.h
  variants/tamc_termod_s3/variant.cpp
Labels: Status: Pending Merge, Type: 3rd party Boards

#11627 feat(docs): Updaze Zigbee docs with latest changes
  docs/en/zigbee/ep_fan_control.rst
  docs/en/zigbee/zigbee_core.rst
  docs/en/zigbee/zigbee_ep.rst
Labels: Type: Documentation, Status: Pending Merge

#11624 fix(zigbee): Fix RGB color calculation
  cores/esp32/ColorFormat.c
  cores/esp32/ColorFormat.h
  libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.cpp
Labels: Status: Pending Merge, Area: Zigbee

#11608 Add senseBox Eye board
  boards.txt
  variants/sensebox_eye/bootloader-tinyuf2.bin
  variants/sensebox_eye/partitions-16MB-tinyuf2.csv
  variants/sensebox_eye/pins_arduino.h
  variants/sensebox_eye/tinyuf2.bin
  variants/sensebox_eye/variant.cpp
  variants/sensebox_mcu_esp32s2/APOTA.ino
Labels: Status: Pending Merge, Type: 3rd party Boards

#11639 feat(github): remove ESP32 forum from issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: Status: Pending Merge

#11640 feat(github): Update template type
  .github/ISSUE_TEMPLATE/Issue-report.yml
Labels: Status: Pending Merge

#11641 feat(zigbee): Update ESP-ZIGBEE-SDK to 1.6.6
  idf_component.yml
Labels: Status: Pending Merge

#11667 fix(github-template): indentation
  .github/ISSUE_TEMPLATE/Issue-report.yml
Labels: Status: Pending Merge
