Repository espressif/arduino-esp32, pull requests merged in 2025-03, with the labels that each got.

#11037 c5 flash base address is 0x2000
  cores/esp32/Esp.cpp
Labels: Status: Pending Merge

#11035 fix(bt): Compile error on ESP32-P4
  cores/esp32/esp32-hal-misc.c
Labels: Status: Pending Merge

#11022 test(i2c): Add test to scan bus
  tests/validation/i2c_master/i2c_master.ino
Labels: Type: CI & Testing, Status: Pending Merge

#11042 feat(matter): necessary changes to insights version for esp_matter
  idf_component.yml
Labels: Status: Pending Merge, Area: Matter

#11016 feat(gpio): allows mixing digital and analog read/write operations
  cores/esp32/esp32-hal-gpio.c
Labels: Area: Peripherals API, Status: Pending Merge

#11064 fix(zigbee): Fixed Guru Meditation crash with Zigbee Analog example
  libraries/Zigbee/src/ep/ZigbeeAnalog.cpp
Labels: Status: Pending Merge, Area: Zigbee

#11048 fix(eth): Fix RMII Ethernet not being able to be restarted
  libraries/Ethernet/src/ETH.cpp
Labels: Status: Pending Merge

#11053 feat(eth): Add setters for negotiation, speed and duplex modes
  libraries/Ethernet/src/ETH.cpp
  libraries/Ethernet/src/ETH.h
Labels: Status: Pending Merge

#11065 fix(zigbee): Use correct attributeID in setAnalogInputReporting
  libraries/Zigbee/src/ep/ZigbeeAnalog.cpp
Labels: Status: Pending Merge, Area: Zigbee

#11066 fix(zigbee): Add manuf_code to report attribute commands
  libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/Zigbee_Temp_Hum_Sensor_Sleepy.ino
  libraries/Zigbee/src/ep/ZigbeeAnalog.cpp
  libraries/Zigbee/src/ep/ZigbeeCarbonDioxideSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeFlowSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeOccupancySensor.cpp
  libraries/Zigbee/src/ep/ZigbeePressureSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeTempSensor.cpp
Labels: Status: Pending Merge, Area: Zigbee

#11067 fix(matter): removes a few matter 1.4 / IDF 5.4 compilation warning messages
  libraries/Matter/src/MatterEndpoints/MatterColorLight.h
  libraries/Matter/src/MatterEndpoints/MatterEnhancedColorLight.h
Labels: Status: Pending Merge, Area: Matter

#11070 fix(matter): examples must set pin to Digital Mode after analogWrite() and before digitalWrite()
  libraries/Matter/examples/MatterColorLight/MatterColorLight.ino
  libraries/Matter/examples/MatterDimmableLight/MatterDimmableLight.ino
  libraries/Matter/examples/MatterEnhancedColorLight/MatterEnhancedColorLight.ino
  libraries/Matter/examples/MatterFan/MatterFan.ino
  libraries/Matter/examples/MatterTemperatureLight/MatterTemperatureLight.ino
Labels: Status: Pending Merge, Area: Matter

#11068 fix(network): fixes a macro name conflict warning
  libraries/Network/src/NetworkClient.cpp
Labels: Status: Pending Merge

#11045 feat(wifi): Add support for 2.4GHz and 5GHz band switching
  libraries/WiFi/examples/WiFiScan/WiFiScan.ino
  libraries/WiFi/src/WiFiGeneric.cpp
  libraries/WiFi/src/WiFiGeneric.h
Labels: Status: Pending Merge, Area: WiFi

#11060 IDF release/v5.4
  package/package_esp32_index.template.json
Labels: Status: Pending Merge

#10455 feat(Zigbee): Adding Zigbee Wind speed sensor endpoint
  CMakeLists.txt
  libraries/Zigbee/examples/Zigbee_Wind_Speed_Sensor/README.md
  libraries/Zigbee/examples/Zigbee_Wind_Speed_Sensor/Zigbee_Wind_Speed_Sensor.ino
  libraries/Zigbee/examples/Zigbee_Wind_Speed_Sensor/ci.json
  libraries/Zigbee/src/Zigbee.h
  libraries/Zigbee/src/ep/ZigbeeWindSpeedSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeWindSpeedSensor.h
Labels: Status: Pending Merge, Area: Zigbee

#11080 test(i2c): Do not use delta as Wokwi timing can be inconsistent
  tests/validation/i2c_master/i2c_master.ino
Labels: Type: CI & Testing, Status: Pending Merge

#11081 docs(esp32p4): Add missing information and improve organization
  README.md
  docs/en/boards/boards.rst
  docs/en/common/datasheet.inc
  docs/en/getting_started.rst
  docs/en/lib_builder.rst
  docs/en/libraries.rst
  package/package_esp32_index.template.json
Labels: Type: Documentation, Status: Pending Merge

#11130 ci(actions): Replace changed-files
  .github/scripts/set_push_chunks.sh
  .github/workflows/build_py_tools.yml
  .github/workflows/pre-commit.yml
  .github/workflows/push.yml
Labels: Type: CI & Testing, Status: Pending Merge

#11122 fix(UART): sets the correct uart clock source when using begin(baudrate)
  cores/esp32/esp32-hal-uart.c
  cores/esp32/esp32-hal-uart.h
Labels: Status: Pending Merge, Peripheral: UART, bug 🐞

#11123 feat(zigbee): Save network channel after 1st joining for faster rejoin
  libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/Zigbee_Temp_Hum_Sensor_Sleepy.ino
  libraries/Zigbee/src/ZigbeeCore.cpp
  libraries/Zigbee/src/ZigbeeCore.h
  libraries/Zigbee/src/ZigbeeEP.cpp
Labels: Status: Pending Merge, Area: Zigbee

#11141 fix(uart): uart rx timeout validation with proper log message
  cores/esp32/esp32-hal-uart.c
  cores/esp32/esp32-hal-uart.h
Labels: Status: Pending Merge, Peripheral: UART

#11145 fix(camera_webserver): Fix typo in OV2640 definition
  libraries/ESP32/examples/Camera/CameraWebServer/camera_index.h
Labels: Type: Example, Status: Pending Merge

#11136 fix(rmt): Fixed protocol name in RMTReadXJT examples
  libraries/ESP32/examples/RMT/RMTReadXJT/RMTReadXJT.ino
Labels: Area: Peripherals API, Type: Example, Status: Pending Merge

#11143 Add a Default 32MB partition
  boards.txt
  tools/partitions/default_32MB.csv
Labels: Chip: ESP32-S3, Status: Pending Merge, Area: Tools & Build System

#11160 fix(ext_lib): Fix ESPAsyncWebServer URL and examples
  .github/workflows/lib.json
Labels: Type: CI & Testing, Status: Pending Merge, lib_test

#11155 Fix(esp32s3usbotg) stdbool dependency in pins_arduino.h
  variants/esp32s3usbotg/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#11179 fix(net): Use network_event_handle_t for internal callbacks
  libraries/Ethernet/src/ETH.cpp
  libraries/Ethernet/src/ETH.h
  libraries/PPP/src/PPP.cpp
  libraries/PPP/src/PPP.h
  libraries/WiFi/src/AP.cpp
  libraries/WiFi/src/STA.cpp
  libraries/WiFi/src/WiFiAP.h
  libraries/WiFi/src/WiFiSTA.h
Labels: Status: Pending Merge

#11182 fix(eth): Set the ETH properties at the correct time
  libraries/Ethernet/src/ETH.cpp
  libraries/Ethernet/src/ETH.h
Labels: Status: Pending Merge

#11183 fix: Add 16M flash option for xiao_esp32_s3_plus
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#11147 ci(workflows): Lock actions to commits and improve readability
  .github/scripts/set_push_chunks.sh
  .github/workflows/allboards.yml
  .github/workflows/boards.yml
  .github/workflows/build_py_tools.yml
  .github/workflows/dangerjs.yml
  .github/workflows/docs_build.yml
  .github/workflows/docs_deploy.yml
  .github/workflows/gh-pages.yml
  .github/workflows/lib.yml
  .github/workflows/pre-commit-status.yml
  .github/workflows/pre-commit.yml
  .github/workflows/publishlib.yml
  .github/workflows/publishsizes-2.x.yml
  .github/workflows/publishsizes.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .github/workflows/tests_build.yml
  .github/workflows/tests_hw.yml
  .github/workflows/tests_qemu.yml
  .github/workflows/tests_results.yml
  .github/workflows/tests_wokwi.yml
  .github/workflows/upload-idf-component.yml
Labels: Type: CI & Testing, Status: Pending Merge

#11186 fix(arduino_pins): fixes Lolin-C3-Pico and C3-Mini RGB LED pin + C3-Pico SPI SCK pin definition
  variants/lolin_c3_mini/pins_arduino.h
  variants/lolin_c3_pico/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#11154 fix: BLEAdvertising methods return error codes
  libraries/BLE/src/BLEAdvertising.cpp
  libraries/BLE/src/BLEAdvertising.h
Labels: Status: Pending Merge, Area: BLE

#11171 feat(zigbee): Add Illuminance sensor endpoint
  CMakeLists.txt
  libraries/Zigbee/examples/Zigbee_Illuminance_Sensor/README.md
  libraries/Zigbee/examples/Zigbee_Illuminance_Sensor/Zigbee_Illuminance_Sensor.ino
  libraries/Zigbee/examples/Zigbee_Illuminance_Sensor/ci.json
  libraries/Zigbee/keywords.txt
  libraries/Zigbee/src/Zigbee.h
  libraries/Zigbee/src/ep/ZigbeeIlluminanceSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeIlluminanceSensor.h
Labels: Status: Pending Merge, Area: Zigbee

#11188 fix(wifi_scan): Fix some edge cases where WiFi Scan may fail
  libraries/WiFi/src/WiFiScan.cpp
Labels: Status: Pending Merge

#11153 feat(zigbee): Add check, boolean returns, fix Analog, add optional reset on factoryReset
  libraries/Zigbee/examples/Zigbee_Temp_Hum_Sensor_Sleepy/Zigbee_Temp_Hum_Sensor_Sleepy.ino
  libraries/Zigbee/src/ZigbeeCore.cpp
  libraries/Zigbee/src/ZigbeeCore.h
  libraries/Zigbee/src/ZigbeeEP.cpp
  libraries/Zigbee/src/ZigbeeEP.h
  libraries/Zigbee/src/ep/ZigbeeAnalog.cpp
  libraries/Zigbee/src/ep/ZigbeeAnalog.h
  libraries/Zigbee/src/ep/ZigbeeCarbonDioxideSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeCarbonDioxideSensor.h
  libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.cpp
  libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.h
  libraries/Zigbee/src/ep/ZigbeeContactSwitch.cpp
  libraries/Zigbee/src/ep/ZigbeeContactSwitch.h
  libraries/Zigbee/src/ep/ZigbeeDimmableLight.cpp
  libraries/Zigbee/src/ep/ZigbeeDimmableLight.h
  libraries/Zigbee/src/ep/ZigbeeDoorWindowHandle.cpp
  libraries/Zigbee/src/ep/ZigbeeDoorWindowHandle.h
  libraries/Zigbee/src/ep/ZigbeeFlowSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeFlowSensor.h
  libraries/Zigbee/src/ep/ZigbeeIlluminanceSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeIlluminanceSensor.h
  libraries/Zigbee/src/ep/ZigbeeLight.cpp
  libraries/Zigbee/src/ep/ZigbeeLight.h
  libraries/Zigbee/src/ep/ZigbeeOccupancySensor.cpp
  libraries/Zigbee/src/ep/ZigbeeOccupancySensor.h
  libraries/Zigbee/src/ep/ZigbeePressureSensor.cpp
  libraries/Zigbee/src/ep/ZigbeePressureSensor.h
  libraries/Zigbee/src/ep/ZigbeeTempSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeTempSensor.h
  libraries/Zigbee/src/ep/ZigbeeVibrationSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeVibrationSensor.h
  libraries/Zigbee/src/ep/ZigbeeWindSpeedSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeWindSpeedSensor.h
  libraries/Zigbee/src/ep/ZigbeeWindowCovering.cpp
  libraries/Zigbee/src/ep/ZigbeeWindowCovering.h
Labels: Status: Pending Merge, Area: Zigbee

#11149 IDF release/v5.4
  libraries/RainMaker/examples/RMakerCustom/ci.json
  libraries/RainMaker/examples/RMakerSwitch/ci.json
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#11150 IDF master
  package/package_esp32_index.template.json
Labels: 🚫 System PR

#11194 Modify T-LoRa-Pager device PID
  variants/lilygo_tlora_pager/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards
