Repository espressif/arduino-esp32, pull requests merged in 2025-06, with the labels that each got.

#11413 make BT core code execution conditional from include esp_bt.h
  cores/esp32/esp32-hal-bt.c
Labels: Status: Pending Merge

#11423 C2: Disable network provisioning
  idf_component.yml
Labels: Status: Pending Merge

#11431 feat(zigbee): Add method to set/get/report analog output
  libraries/Zigbee/examples/Zigbee_Analog_Input_Output/Zigbee_Analog_Input_Output.ino
  libraries/Zigbee/examples/Zigbee_Analog_Input_Output/ci.json
  libraries/Zigbee/keywords.txt
  libraries/Zigbee/src/ep/ZigbeeAnalog.cpp
  libraries/Zigbee/src/ep/ZigbeeAnalog.h
Labels: Status: Pending Merge, Area: Zigbee

#11436 feat(zigbee): Update to esp-zigbee-sdk 1.6.5 and fix ci.json files
  idf_component.yml
  libraries/Zigbee/examples/Zigbee_On_Off_MultiSwitch/ci.json
  libraries/Zigbee/examples/Zigbee_Power_Outlet/Zigbee_Power_Outlet.ino
  libraries/Zigbee/examples/Zigbee_Power_Outlet/ci.json
Labels: Status: Pending Merge, Area: Zigbee

#11432 fix: Add PSRAM Option for Geekble nano
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#11359 Backport: changes to compile v3.1.x as component of IDF branch release/v5.3
  .github/workflows/build_py_tools.yml
  .github/workflows/push.yml
  cores/esp32/esp32-hal-i2c-slave.c
Labels: Status: Pending Merge, Area: Arduino as ESP-IDF component

#11439 fix(ci): Process only needed files in publish sizes
  .github/workflows/publishsizes.yml
Labels: Type: CI & Testing, Status: Pending Merge

#11453 feat(p4): Add 32MB Flash Partitions to ESP32-P4
  boards.txt
Labels: Status: Pending Merge

#11433 feat(esptool): Upgrade to esptool v5
  .github/scripts/update_esptool.py
  package/package_esp32_index.template.json
  platform.txt
Labels: Status: Pending Merge, Area: Tools & Build System

#11452 feat(ledc): Improve timer management with frequency/resolution matching
  cores/esp32/esp32-hal-ledc.c
  cores/esp32/esp32-hal-ledc.h
Labels: Area: Peripherals API, Status: Pending Merge

#11323 fix(release): Replace all assets with chinese mirrors
  .github/scripts/on-release.sh
  .github/scripts/release_append_cn.py
  docs/en/installing.rst
Labels: Type: Documentation, Type: CI & Testing, Status: Pending Merge

#10954 Fix(I2S example): make fix to the ESP32 I2S simple tone example
  libraries/ESP_I2S/examples/Simple_tone/Simple_tone.ino
Labels: Status: Pending Merge

#11353 remove weak function declaration of tud_msc_is_writable_cb to fix simultaneous CDC and MSC
  cores/esp32/esp32-hal-tinyusb.c
Labels: Status: Pending Merge

#11474 feat(openthread): adds native api
  CMakeLists.txt
  libraries/OpenThread/README.md
  libraries/OpenThread/examples/CLI/COAP/coap_lamp/ci.json
  libraries/OpenThread/examples/CLI/COAP/coap_lamp/coap_lamp.ino
  libraries/OpenThread/examples/CLI/COAP/coap_switch/ci.json
  libraries/OpenThread/examples/CLI/COAP/coap_switch/coap_switch.ino
  libraries/OpenThread/examples/CLI/SimpleCLI/SimpleCLI.ino
  libraries/OpenThread/examples/CLI/SimpleCLI/ci.json
  libraries/OpenThread/examples/CLI/SimpleNode/SimpleNode.ino
  libraries/OpenThread/examples/CLI/SimpleNode/ci.json
  libraries/OpenThread/examples/CLI/SimpleThreadNetwork/ExtendedRouterNode/ExtendedRouterNode.ino
  libraries/OpenThread/examples/CLI/SimpleThreadNetwork/ExtendedRouterNode/ci.json
  libraries/OpenThread/examples/CLI/SimpleThreadNetwork/LeaderNode/LeaderNode.ino
  libraries/OpenThread/examples/CLI/SimpleThreadNetwork/LeaderNode/ci.json
  libraries/OpenThread/examples/CLI/SimpleThreadNetwork/RouterNode/RouterNode.ino
  libraries/OpenThread/examples/CLI/SimpleThreadNetwork/RouterNode/ci.json
  libraries/OpenThread/examples/CLI/ThreadScan/ThreadScan.ino
  libraries/OpenThread/examples/CLI/ThreadScan/ci.json
  libraries/OpenThread/examples/CLI/onReceive/ci.json
  libraries/OpenThread/examples/CLI/onReceive/onReceive.ino
  libraries/OpenThread/examples/Native/SimpleThreadNetwork/LeaderNode/LeaderNode.ino
  libraries/OpenThread/examples/Native/SimpleThreadNetwork/LeaderNode/ci.json
  libraries/OpenThread/examples/Native/SimpleThreadNetwork/RouterNode/RouterNode.ino
  libraries/OpenThread/examples/Native/SimpleThreadNetwork/RouterNode/ci.json
  libraries/OpenThread/keywords.txt
  libraries/OpenThread/src/OThread.cpp
  libraries/OpenThread/src/OThread.h
  libraries/OpenThread/src/OThreadCLI.cpp
  libraries/OpenThread/src/OThreadCLI.h
  libraries/OpenThread/src/OThreadCLI_Util.cpp
  libraries/OpenThread/src/OThreadCLI_Util.h
Labels: Status: Pending Merge, Area: OpenThread

#11464 feat(LEDC): Add Gamma Fade support and enhance auto channel/timer selection for multi-group
  cores/esp32/esp32-hal-ledc.c
  cores/esp32/esp32-hal-ledc.h
  libraries/ESP32/examples/AnalogOut/LEDCGammaFade/LEDCGammaFade.ino
  libraries/ESP32/examples/AnalogOut/LEDCGammaFade/ci.json
Labels: Area: Peripherals API, Status: Pending Merge

#11477 feat(spi): Add return values to SPI begin + comments on SPI buses
  cores/esp32/esp32-hal-spi.h
  libraries/SPI/src/SPI.cpp
  libraries/SPI/src/SPI.h
Labels: Status: Pending Merge

#11480 feat(openthread): Add RLOC16 in otPrintNetworkInformation()
  libraries/OpenThread/src/OThread.cpp
Labels: Status: Pending Merge, Area: OpenThread

#11471 fix(docs): correct code block indentation in core_compatibility.rst
  docs/en/guides/core_compatibility.rst
Labels: Type: Documentation, Status: Pending Merge

#11487 feat(esptool): Upgrade to esptool v5
  .github/scripts/package_esptool.sh
  package/package_esp32_index.template.json
  platform.txt
Labels: Status: Pending Merge, Area: Tools & Build System

#11488 pioarduino changes for updated esptool.py v5.0.0
  tools/pioarduino-build.py
Labels: Status: Pending Merge, Area: Tools & Build System

#11411 Proper EDNS handling and cleaner NOERROR response in DNSSERVER
  libraries/DNSServer/src/DNSServer.cpp
  libraries/DNSServer/src/DNSServer.h
Labels: Area: Libraries, Status: Pending Merge

#11492 feat(uart): fixes loopback function after IDF changes
  cores/esp32/esp32-hal-uart.c
Labels: Type: CI & Testing, Status: Pending Merge, Peripheral: UART

#11499 feat(uart): fixes pin attach for any IDF 5.x
  cores/esp32/esp32-hal-uart.c
Labels: Area: ESP-IDF related, Status: Pending Merge, Peripheral: UART, bug 🐞

#11507 fix(uart): idf 5.5 new gpio_iomux_* functions
  cores/esp32/esp32-hal-uart.c
Labels: Area: ESP-IDF related, Status: Pending Merge, Peripheral: UART

#11505 fix(docs): Fix links and versions
  docs/conf_common.py
  docs/en/contributing.rst
  docs/en/esp-idf_component.rst
  docs/en/guides/docs_contributing.rst
  docs/en/index.rst
  docs/en/lib_builder.rst
  docs/requirements.txt
Labels: Type: Documentation, Status: Pending Merge

#11512 IDF release/v5.4
  libraries/WiFi/src/WiFiGeneric.cpp
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#11521 feat(SDFS): Add destructor for SD card to clean up resources
  libraries/SD/src/SD.cpp
  libraries/SD/src/SD.h
Labels: Status: Pending Merge

#11524 feat(esp_now): Add support for ESP NOW V2
  libraries/ESP_NOW/examples/ESP_NOW_Broadcast_Master/ESP_NOW_Broadcast_Master.ino
  libraries/ESP_NOW/examples/ESP_NOW_Broadcast_Slave/ESP_NOW_Broadcast_Slave.ino
  libraries/ESP_NOW/examples/ESP_NOW_Network/ESP_NOW_Network.ino
  libraries/ESP_NOW/examples/ESP_NOW_Serial/ESP_NOW_Serial.ino
  libraries/ESP_NOW/src/ESP32_NOW.cpp
  libraries/ESP_NOW/src/ESP32_NOW.h
  libraries/ESP_NOW/src/ESP32_NOW_Serial.cpp
Labels: Status: Pending Merge, Area: ESP-NOW

#11523 Fix appending to Strings longer than 64k
  cores/esp32/WString.cpp
Labels: Status: Pending Merge
