Repository espressif/arduino-esp32, pull requests merged in 2025-09, with the labels that each got.

#11786 refactor(http-client): Replace USE_SERIAL with direct Serial
  libraries/HTTPClient/examples/Authorization/Authorization.ino
  libraries/HTTPClient/examples/BasicHttpClient/BasicHttpClient.ino
  libraries/HTTPClient/examples/ReuseConnection/ReuseConnection.ino
  libraries/HTTPClient/examples/StreamHttpClient/StreamHttpClient.ino
Labels: Type: Example, Status: Pending Merge

#11785 feat(sr): Update ESP-SR to 2.x and enable it for ESP32-P4
  idf_component.yml
  libraries/ESP_SR/src/ESP_SR.cpp
  libraries/ESP_SR/src/ESP_SR.h
  libraries/ESP_SR/src/esp32-hal-sr.c
  libraries/ESP_SR/src/esp32-hal-sr.h
Labels: Status: Pending Merge

#11776 ci(pre-commit): Add label if manual fixes are required
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
Labels: Type: CI & Testing, Status: Pending Merge

#11792 fix(zigbee): Add lock in scanNetworks to avoid race condition
  libraries/Zigbee/src/ZigbeeCore.cpp
Labels: Type: Bug :bug:, Status: Pending Merge, Area: Zigbee

#11793 Add header check for esp_bt.h in esp32-hal-misc.c
  cores/esp32/esp32-hal-misc.c
Labels: Status: Pending Merge

#11797 fix(sr): Fix ESP-SR lib and example for v2.x
  boards.txt
  libraries/ESP_SR/examples/Basic/Basic.ino
  libraries/ESP_SR/examples/Basic/ci.json
  libraries/ESP_SR/src/ESP_SR.cpp
  libraries/ESP_SR/src/ESP_SR.h
  libraries/ESP_SR/src/esp32-hal-sr.c
  libraries/ESP_SR/src/esp32-hal-sr.h
Labels: Status: Pending Merge

#11676 feat(hash): Add hashing library and new algorithms
  CMakeLists.txt
  cores/esp32/HEXBuilder.cpp
  cores/esp32/HEXBuilder.h
  cores/esp32/HashBuilder.cpp
  cores/esp32/HashBuilder.h
  cores/esp32/MD5Builder.cpp
  cores/esp32/MD5Builder.h
  libraries/Hash/examples/HEX/HEX.ino
  libraries/Hash/examples/MD5/MD5.ino
  libraries/Hash/examples/PBKDF2_HMAC/PBKDF2_HMAC.ino
  libraries/Hash/examples/SHA1/SHA1.ino
  libraries/Hash/examples/SHA2/SHA2.ino
  libraries/Hash/examples/SHA3/SHA3.ino
  libraries/Hash/examples/SHA3Stream/SHA3Stream.ino
  libraries/Hash/keywords.txt
  libraries/Hash/library.properties
  libraries/Hash/src/PBKDF2_HMACBuilder.cpp
  libraries/Hash/src/PBKDF2_HMACBuilder.h
  libraries/Hash/src/SHA1Builder.cpp
  libraries/Hash/src/SHA1Builder.h
  libraries/Hash/src/SHA2Builder.cpp
  libraries/Hash/src/SHA2Builder.h
  libraries/Hash/src/SHA3Builder.cpp
  libraries/Hash/src/SHA3Builder.h
Labels: Area: Libraries, Status: Pending Merge

#11795 fix(usbmidi): use channel in int16_t USB MIDI pitch bend
  libraries/USB/src/USBMIDI.cpp
Labels: Area: Peripherals API, Status: Pending Merge

#11799 fix(pre-commit): Make tagging work for forks
  .github/workflows/pre-commit-status.yml
  .github/workflows/pre-commit.yml
Labels: Type: CI & Testing, Status: Pending Merge

#11560 feat(zigbee): Add Binary Output support
  docs/en/zigbee/ep_binary.rst
  libraries/Zigbee/examples/Zigbee_Binary_Input_Output/README.md
  libraries/Zigbee/examples/Zigbee_Binary_Input_Output/Zigbee_Binary_Input_Output.ino
  libraries/Zigbee/examples/Zigbee_Binary_Input_Output/ci.json
  libraries/Zigbee/src/ep/ZigbeeBinary.cpp
  libraries/Zigbee/src/ep/ZigbeeBinary.h
Labels: Status: Pending Merge, Area: Zigbee

#11720 feat(usb): allow the MIDI constructor to define a device name
  cores/esp32/Arduino.h
  libraries/USB/examples/MIDI/MidiController/MidiController.ino
  libraries/USB/examples/MIDI/MidiInterface/MidiInterface.ino
  libraries/USB/src/USBMIDI.cpp
  libraries/USB/src/USBMIDI.h
Labels: Area: Peripherals API, Status: Pending Merge

#11815 IDF release/v5.5
  libraries/WiFi/examples/WiFiBlueToothSwitch/WiFiBlueToothSwitch.ino
  libraries/WiFi/examples/WiFiBlueToothSwitch/ci.json
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#11829 fix(esp32): float conversion warning in String::toFloat
  cores/esp32/WString.cpp
Labels: Status: Pending Merge

#11832 feat(variants): Add variant for M5Tab5
  boards.txt
  variants/m5stack_tab5/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#11838 Fix (WiFi): Do not steal scan results
  libraries/WiFi/src/WiFiScan.cpp
Labels: Status: Pending Merge

#11828 fix(esp32): Compiler warning - loop variable `a` shadows previous instance of `a` in function `i2c_slave_gpio_mode`
  cores/esp32/esp32-hal-i2c-slave.c
Labels: Area: Peripherals API, Status: Pending Merge

#11843 feat(eth): Add support for LAN867X ETH PHY
  idf_component.yml
  libraries/Ethernet/src/ETH.cpp
  libraries/Ethernet/src/ETH.h
Labels: Status: Pending Merge

#11848 feat(board): add support for Silicognition ManT1S
  boards.txt
  variants/mant1s/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#11847 IDF release/v5.5
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#11586 Update HTTPUpdateServer.h to Fix SPIFFS Update error: Bad Size Given
  libraries/HTTPUpdateServer/src/HTTPUpdateServer.h
Labels: Status: Pending Merge

#11850 change(script): Update the issue template when version changed
  .github/scripts/update-version.sh
Labels: Status: Pending Merge

#11870 fix(menu): remove unused flash size option for 4D Systems MIPI LCDs
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#11876 fix: Add upload flags to boards.txt for Twin AIoT Module to resolve upload error
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#11877 fix(board): Fix pid parameter for FoBE Quill ESP32S3 Mesh in boards.txt
  boards.txt
Labels: Status: Pending Merge, Type: 3rd party Boards

#11878 Refactor touch pad error logging
  cores/esp32/esp32-hal-gpio.c
  cores/esp32/esp32-hal-touch-ng.c
  cores/esp32/esp32-hal-touch.c
Labels: Area: Peripherals API, Status: Pending Merge
