Repository espressif/arduino-esp32, pull requests merged in 2025-05, with the labels that each got.

#11330 Add new board: Sparkle Motion Stick
  boards.txt
  variants/adafruit_sparklemotionstick_esp32/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#11341 fix compile fail esp_hosted
  idf_component.yml
Labels: Status: Pending Merge

#11342 IDF master
  CMakeLists.txt
  cores/esp32/chip-debug-report.cpp
  idf_component.yml
  libraries/WiFi/src/WiFiGeneric.cpp
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#11350 Added new Unexpected Maker SQUiXL and EDGES3[D] boards.
  boards.txt
  variants/um_edges3_d/pins_arduino.h
  variants/um_squixl/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#11212 IDF release/v5.4
  cores/esp32/esp32-hal-i2c-slave.c
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#11344 Update version for wifi remote
  idf_component.yml
Labels: Status: Pending Merge

#11357 IDF release/v5.4
  package/package_esp32_index.template.json
Labels: Status: Pending Merge

#11358 IDF master
  package/package_esp32_index.template.json
Labels: Status: Pending Merge

#11316 feat(zigbee): Remove static variables, improve binding, new example
  libraries/Zigbee/examples/Zigbee_On_Off_MultiSwitch/README.md
  libraries/Zigbee/examples/Zigbee_On_Off_MultiSwitch/Zigbee_On_Off_MultiSwitch.ino
  libraries/Zigbee/examples/Zigbee_On_Off_MultiSwitch/ci.json
  libraries/Zigbee/src/ZigbeeCore.cpp
  libraries/Zigbee/src/ZigbeeCore.h
  libraries/Zigbee/src/ZigbeeEP.cpp
  libraries/Zigbee/src/ZigbeeEP.h
  libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.cpp
  libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.h
  libraries/Zigbee/src/ep/ZigbeeSwitch.cpp
  libraries/Zigbee/src/ep/ZigbeeSwitch.h
  libraries/Zigbee/src/ep/ZigbeeThermostat.cpp
  libraries/Zigbee/src/ep/ZigbeeThermostat.h
Labels: Status: Pending Merge, Area: Zigbee

#11339 feat(zigbee): Add support for Binary input EP + Analog EP extension
  CMakeLists.txt
  libraries/Zigbee/examples/Zigbee_Analog_Input_Output/Zigbee_Analog_Input_Output.ino
  libraries/Zigbee/examples/Zigbee_Binary_Input/README.md
  libraries/Zigbee/examples/Zigbee_Binary_Input/Zigbee_Binary_Input.ino
  libraries/Zigbee/examples/Zigbee_Binary_Input/ci.json
  libraries/Zigbee/src/Zigbee.h
  libraries/Zigbee/src/ep/ZigbeeAnalog.cpp
  libraries/Zigbee/src/ep/ZigbeeAnalog.h
  libraries/Zigbee/src/ep/ZigbeeBinary.cpp
  libraries/Zigbee/src/ep/ZigbeeBinary.h
Labels: Status: Pending Merge, Area: Zigbee

#11406 IDF release/v5.4
  cores/esp32/esp32-hal-cpu.c
  package/package_esp32_index.template.json
Labels: Status: Pending Merge
