Repository espressif/arduino-esp32, pull requests merged in 2025-02, with the labels that each got.

#10926 FIX [UART]: ESP32-S2 UART baud rate detection CI test case
  tests/validation/uart/uart.ino
Labels: Type: CI & Testing, Status: Pending Merge, Peripheral: UART

#10925 Update README.md to add ESP-SR
  libraries/README.md
Labels: Status: Pending Merge

#10918 feat(zigbee): Add IAS Zone endpoints (Contact Switch + Door/Window Handle)
  CMakeLists.txt
  libraries/Zigbee/examples/Zigbee_Contact_Switch/README.md
  libraries/Zigbee/examples/Zigbee_Contact_Switch/Zigbee_Contact_Switch.ino
  libraries/Zigbee/examples/Zigbee_Contact_Switch/ci.json
  libraries/Zigbee/src/Zigbee.h
  libraries/Zigbee/src/ZigbeeEP.h
  libraries/Zigbee/src/ZigbeeHandlers.cpp
  libraries/Zigbee/src/ep/ZigbeeContactSwitch.cpp
  libraries/Zigbee/src/ep/ZigbeeContactSwitch.h
  libraries/Zigbee/src/ep/ZigbeeDoorWindowHandle.cpp
  libraries/Zigbee/src/ep/ZigbeeDoorWindowHandle.h
Labels: Status: Pending Merge, Area: Zigbee

#10805 NetworkEvents allow stack size to be changed.
  libraries/Network/src/NetworkEvents.cpp
Labels: Status: Pending Merge

#10931 fix(ci): Disable some RainMaker examples on ESP32
  libraries/RainMaker/examples/RMakerCustomAirCooler/ci.json
  libraries/RainMaker/examples/RMakerSonoffDualR3/ci.json
Labels: Status: Pending Merge

#10932 fix(ota): Make sure that ArduinoOTA.end() is called in the destructor
  libraries/ArduinoOTA/src/ArduinoOTA.cpp
Labels: Status: Pending Merge

#10914 Created Zigbee Endpoint for Window Covering.
  CMakeLists.txt
  libraries/Zigbee/examples/Zigbee_Window_Covering/README.md
  libraries/Zigbee/examples/Zigbee_Window_Covering/Zigbee_Window_Covering.ino
  libraries/Zigbee/examples/Zigbee_Window_Covering/ci.json
  libraries/Zigbee/src/Zigbee.h
  libraries/Zigbee/src/ZigbeeEP.h
  libraries/Zigbee/src/ZigbeeHandlers.cpp
  libraries/Zigbee/src/ep/ZigbeeWindowCovering.cpp
  libraries/Zigbee/src/ep/ZigbeeWindowCovering.h
Labels: Status: Pending Merge, Status: Review needed, Area: Zigbee

#10939 fix(wifi): Make sure that esp-hosted events are propagated
  libraries/Network/src/NetworkInterface.cpp
Labels: Status: Pending Merge

#10963 fix(i2s): Add missing initializer for I2S CLK config
  libraries/ESP_I2S/src/ESP_I2S.cpp
Labels: Status: Pending Merge

#10962 feat(cdc): Add support for two CDC ports at once
  cores/esp32/USBCDC.cpp
  cores/esp32/esp32-hal-tinyusb.c
  cores/esp32/esp32-hal-tinyusb.h
Labels: Status: Pending Merge

#10946 feat(zigbee): Add OTA client cluster support
  libraries/Zigbee/examples/Zigbee_OTA_Client/README.md
  libraries/Zigbee/examples/Zigbee_OTA_Client/Zigbee_OTA_Client.ino
  libraries/Zigbee/examples/Zigbee_OTA_Client/ci.json
  libraries/Zigbee/src/ZigbeeEP.cpp
  libraries/Zigbee/src/ZigbeeEP.h
  libraries/Zigbee/src/ZigbeeHandlers.cpp
Labels: Status: Pending Merge, Area: Zigbee

#10873 IDF release/v5.3
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10959 feat(zigbee): Support HSV color commands for RGB light endpoint
  libraries/Zigbee/src/ZigbeeEP.h
  libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.cpp
  libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.h
  libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.cpp
Labels: Status: Pending Merge, Area: Zigbee

#10957 feat(board): Update 3rd party board Huidu HD-WF2/HD-WF4
  boards.txt
  variants/huidu_hd_wf2/pins_arduino.h
  variants/huidu_hd_wf4/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10972 Fix crash in String when using nullptr (#10971)
  cores/esp32/WString.cpp
Labels: Status: Pending Merge

#10832 Arduino 3.2.0 based on ESP-IDF v5.4
  .github/workflows/push.yml
  CMakeLists.txt
  cores/esp32/esp32-hal-i2c-ng.c
  cores/esp32/esp32-hal-i2c-slave.c
  cores/esp32/esp32-hal-i2c.c
  idf_component.yml
  libraries/Ethernet/src/ETH.cpp
  libraries/Ethernet/src/ETH.h
  libraries/Wire/src/Wire.cpp
  libraries/Wire/src/Wire.h
  variants/esp32c6/pins_arduino.h
Labels: Status: Pending Merge, 🚫 System PR

#10980 IDF release/v5.4
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10981 IDF master
  libraries/RainMaker/examples/RMakerCustom/ci.json
  libraries/RainMaker/examples/RMakerSwitch/ci.json
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10967 feat(LP_UART): Implements the ESP32-C6/ESP32-P4 Low Power UART as a possible HardwareSerial port
  cores/esp32/HardwareSerial.cpp
  cores/esp32/HardwareSerial.h
  cores/esp32/esp32-hal-uart.c
  cores/esp32/esp32-hal-uart.h
Labels: Type: Feature request, Status: Pending Merge, Peripheral: UART

#10970 feat(zigbee): Add range extender device endpoint
  CMakeLists.txt
  libraries/Zigbee/examples/Zigbee_Range_Extender/README.md
  libraries/Zigbee/examples/Zigbee_Range_Extender/Zigbee_Range_Extender.ino
  libraries/Zigbee/examples/Zigbee_Range_Extender/ci.json
  libraries/Zigbee/src/Zigbee.h
  libraries/Zigbee/src/ep/ZigbeeRangeExtender.cpp
  libraries/Zigbee/src/ep/ZigbeeRangeExtender.h
Labels: Status: Pending Merge, Area: Zigbee

#10764 ci(report): Add runtime tests report
  .github/scripts/tests_run.sh
  .github/workflows/tests_results.yml
  .github/workflows/tests_wokwi.yml
  README.md
Labels: Type: CI & Testing, Status: Pending Merge

#10950 feat(zigbee): Add Analog endpoint device (input, output, value clusters)
  CMakeLists.txt
  libraries/Zigbee/examples/Zigbee_Analog_Input_Output/README.md
  libraries/Zigbee/examples/Zigbee_Analog_Input_Output/Zigbee_Analog_Input_Output.ino
  libraries/Zigbee/examples/Zigbee_Analog_Input_Output/ci.json
  libraries/Zigbee/src/Zigbee.h
  libraries/Zigbee/src/ep/ZigbeeAnalog.cpp
  libraries/Zigbee/src/ep/ZigbeeAnalog.h
  libraries/Zigbee/src/ep/ZigbeeTempSensor.cpp
Labels: Status: Pending Merge, Area: Zigbee

#11000 fix(board): Update pins_arduino.h for Geekble_ESP32C3
  variants/Geekble_ESP32C3/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10960 ci(runners): Bump runner images version
  .github/workflows/build_py_tools.yml
  .github/workflows/push.yml
Labels: Type: CI & Testing, Status: Pending Merge

#11001 fix(board): Update feathers3 wire1 pin definition
  variants/um_feathers3/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#11005 feat(boards): Add Geekble-nano-ESP32S3
  boards.txt
  variants/Geekble_Nano_ESP32S3/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10998 IDF release/v5.4
  libraries/Zigbee/src/ZigbeeCore.cpp
  libraries/Zigbee/src/ZigbeeCore.h
  libraries/Zigbee/src/ZigbeeEP.cpp
  libraries/Zigbee/src/ZigbeeEP.h
  libraries/Zigbee/src/ZigbeeHandlers.cpp
  libraries/Zigbee/src/ep/ZigbeeAnalog.cpp
  libraries/Zigbee/src/ep/ZigbeeAnalog.h
  libraries/Zigbee/src/ep/ZigbeeCarbonDioxideSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeCarbonDioxideSensor.h
  libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.cpp
  libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.h
  libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.cpp
  libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.h
  libraries/Zigbee/src/ep/ZigbeeContactSwitch.cpp
  libraries/Zigbee/src/ep/ZigbeeContactSwitch.h
  libraries/Zigbee/src/ep/ZigbeeDimmableLight.cpp
  libraries/Zigbee/src/ep/ZigbeeDimmableLight.h
  libraries/Zigbee/src/ep/ZigbeeDoorWindowHandle.cpp
  libraries/Zigbee/src/ep/ZigbeeDoorWindowHandle.h
  libraries/Zigbee/src/ep/ZigbeeFlowSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeFlowSensor.h
  libraries/Zigbee/src/ep/ZigbeeLight.cpp
  libraries/Zigbee/src/ep/ZigbeeLight.h
  libraries/Zigbee/src/ep/ZigbeeOccupancySensor.cpp
  libraries/Zigbee/src/ep/ZigbeeOccupancySensor.h
  libraries/Zigbee/src/ep/ZigbeePressureSensor.cpp
  libraries/Zigbee/src/ep/ZigbeePressureSensor.h
  libraries/Zigbee/src/ep/ZigbeeRangeExtender.cpp
  libraries/Zigbee/src/ep/ZigbeeRangeExtender.h
  libraries/Zigbee/src/ep/ZigbeeSwitch.cpp
  libraries/Zigbee/src/ep/ZigbeeSwitch.h
  libraries/Zigbee/src/ep/ZigbeeTempSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeTempSensor.h
  libraries/Zigbee/src/ep/ZigbeeThermostat.cpp
  libraries/Zigbee/src/ep/ZigbeeThermostat.h
  libraries/Zigbee/src/ep/ZigbeeVibrationSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeVibrationSensor.h
  libraries/Zigbee/src/ep/ZigbeeWindowCovering.cpp
  libraries/Zigbee/src/ep/ZigbeeWindowCovering.h
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#10947 Update of Boards.txt & variants - Adding CYObot board - 3rd party board
  boards.txt
  variants/cyobot_v2_esp32s3/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#11008 fix(zigbee): use correct pressure cluster function in setTolerance
  libraries/Zigbee/src/ep/ZigbeePressureSensor.cpp
Labels: Status: Pending Merge, Area: Zigbee

#10999 IDF master
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR

#11009 feat(zigbee): Add ZigbeeGateway endpoint support + Time Cluster bugfix
  CMakeLists.txt
  boards.txt
  libraries/Zigbee/examples/Zigbee_Gateway/README.md
  libraries/Zigbee/examples/Zigbee_Gateway/Zigbee_Gateway.ino
  libraries/Zigbee/examples/Zigbee_Gateway/ci.json
  libraries/Zigbee/keywords.txt
  libraries/Zigbee/src/Zigbee.h
  libraries/Zigbee/src/ZigbeeCore.cpp
  libraries/Zigbee/src/ZigbeeCore.h
  libraries/Zigbee/src/ZigbeeEP.cpp
  libraries/Zigbee/src/ZigbeeEP.h
  libraries/Zigbee/src/ep/ZigbeeGateway.cpp
  libraries/Zigbee/src/ep/ZigbeeGateway.h
Labels: Status: Pending Merge, Area: Zigbee

#11014 ci(esp32p4): Add missing options for P4
  tests/validation/democfg/ci.json
  tests/validation/nvs/ci.json
Labels: Type: CI & Testing, Status: Pending Merge

#11015 fix(zigbee): use correct carbon dioxide cluster function in setTolerance
  libraries/Zigbee/src/ep/ZigbeeCarbonDioxideSensor.cpp
Labels: Status: Pending Merge, Area: Zigbee

#11018 IDF master
  package/package_esp32_index.template.json
Labels: Status: Pending Merge, 🚫 System PR
