Repository espressif/arduino-esp32, pull requests merged in 2025-01, with the labels that each got.

#10749 docs(3rd-party): Add section for third party tools
  docs/en/index.rst
  docs/en/third_party/pioarduino.rst
  docs/en/third_party/wokwi.rst
  docs/en/third_party_tools.rst
  docs/requirements.txt
Labels: Type: Documentation, Status: Pending Merge

#10750 feat(webserver): Middleware with default middleware for cors, authc, curl-like logging
  CMakeLists.txt
  libraries/WebServer/examples/Middleware/Middleware.ino
  libraries/WebServer/examples/Middleware/ci.json
  libraries/WebServer/src/Middlewares.h
  libraries/WebServer/src/Parsing.cpp
  libraries/WebServer/src/WebServer.cpp
  libraries/WebServer/src/WebServer.h
  libraries/WebServer/src/detail/RequestHandler.h
  libraries/WebServer/src/detail/RequestHandlersImpl.h
  libraries/WebServer/src/middleware/AuthenticationMiddleware.cpp
  libraries/WebServer/src/middleware/CorsMiddleware.cpp
  libraries/WebServer/src/middleware/LoggingMiddleware.cpp
  libraries/WebServer/src/middleware/Middleware.h
  libraries/WebServer/src/middleware/MiddlewareChain.cpp
Labels: Area: Libraries, Status: Pending Merge

#10755 feat(matter): new Matter Endpoint for Thermostat
  CMakeLists.txt
  libraries/Matter/examples/MatterThermostat/MatterThermostat.ino
  libraries/Matter/examples/MatterThermostat/ci.json
  libraries/Matter/keywords.txt
  libraries/Matter/src/Matter.h
  libraries/Matter/src/MatterEndpoints/MatterThermostat.cpp
  libraries/Matter/src/MatterEndpoints/MatterThermostat.h
Labels: Area: Libraries, Status: Pending Merge

#10757 ci: Allow push to the component registry from a given git ref
  .github/workflows/upload-idf-component.yml
Labels: Status: Pending Merge

#10759 feat(matter): Changes Matter Temperature Sensor to report Celsius
  libraries/Matter/examples/MatterTemperatureSensor/MatterTemperatureSensor.ino
  libraries/Matter/src/MatterEndpoints/MatterTemperatureSensor.cpp
  libraries/Matter/src/MatterEndpoints/MatterTemperatureSensor.h
Labels: Area: Libraries, Status: Pending Merge

#10770 ci(dangerjs): Fix and update settings
  .github/workflows/dangerjs.yml
Labels: Type: CI & Testing, Status: Pending Merge

#10776 Restore Arduino Client API
  cores/esp32/Client.h
  libraries/Network/src/NetworkClient.h
Labels: Status: Pending Merge

#10807 feat(matter): adds esp_matter:: namespace to attribute_t
  libraries/Matter/src/MatterEndPoint.h
  libraries/Matter/src/MatterEndpoints/MatterColorLight.cpp
  libraries/Matter/src/MatterEndpoints/MatterColorTemperatureLight.cpp
  libraries/Matter/src/MatterEndpoints/MatterDimmableLight.cpp
  libraries/Matter/src/MatterEndpoints/MatterEnhancedColorLight.cpp
  libraries/Matter/src/MatterEndpoints/MatterOnOffLight.cpp
Labels: Area: Libraries, Status: Pending Merge, Area: Matter

#10813 fix(udp): Add missing LwIP locks to init multicast
  libraries/AsyncUDP/src/AsyncUDP.cpp
Labels: Status: Pending Merge

#10814 fix(camera): Update resolutions and remove face detection
  libraries/ESP32/examples/Camera/CameraWebServer/camera_index.h
Labels: Status: Pending Merge

#10809 Add two more Adafruit Boards (Sparkle Motion & Sparkle Motion mini)
  boards.txt
  variants/adafruit_sparklemotion_esp32/pins_arduino.h
  variants/adafruit_sparklemotionmini_esp32/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10816 IDF release/v5.3
  cores/esp32/esp_arduino_version.h
  libraries/ArduinoOTA/library.properties
  libraries/AsyncUDP/library.properties
  libraries/BLE/library.properties
  libraries/BluetoothSerial/library.properties
  libraries/DNSServer/library.properties
  libraries/EEPROM/library.properties
  libraries/ESP32/library.properties
  libraries/ESP_I2S/library.properties
  libraries/ESP_NOW/library.properties
  libraries/ESP_SR/library.properties
  libraries/ESPmDNS/library.properties
  libraries/Ethernet/library.properties
  libraries/FFat/library.properties
  libraries/FS/library.properties
  libraries/HTTPClient/library.properties
  libraries/HTTPUpdate/library.properties
  libraries/HTTPUpdateServer/library.properties
  libraries/Insights/library.properties
  libraries/LittleFS/library.properties
  libraries/Matter/library.properties
  libraries/NetBIOS/library.properties
  libraries/Network/library.properties
  libraries/NetworkClientSecure/library.properties
  libraries/OpenThread/library.properties
  libraries/PPP/library.properties
  libraries/Preferences/library.properties
  libraries/RainMaker/library.properties
  libraries/SD/library.properties
  libraries/SD_MMC/library.properties
  libraries/SPI/library.properties
  libraries/SPIFFS/library.properties
  libraries/SimpleBLE/library.properties
  libraries/TFLiteMicro/library.properties
  libraries/Ticker/library.properties
  libraries/USB/library.properties
  libraries/Update/library.properties
  libraries/WebServer/library.properties
  libraries/WiFi/library.properties
  libraries/WiFiProv/library.properties
  libraries/Wire/library.properties
  libraries/Zigbee/library.properties
  package.json
  package/package_esp32_index.template.json
  platform.txt
Labels: Status: Pending Merge, 🚫 System PR

#10779 feat(board): Add custom board Huidu HD-WF2/HD-WF4 - esp32-s3 HUB75 driver boards
  boards.txt
  variants/huidu_hd_wf2/pins_arduino.h
  variants/huidu_hd_wf4/pins_arduino.h
Labels: Status: Pending Merge, Type: 3rd party Boards

#10819 ESPmDNS: Add method for querying discovered service name
  libraries/ESPmDNS/examples/mDNS-SD_Extended/mDNS-SD_Extended.ino
  libraries/ESPmDNS/src/ESPmDNS.cpp
  libraries/ESPmDNS/src/ESPmDNS.h
Labels: Status: Pending Merge

#10823 feat(idf): Add support for IDF v5.4
  CMakeLists.txt
  cores/esp32/esp32-hal-i2c-slave.c
  idf_component.yml
Labels: Status: Pending Merge

#10817 fix(zigbee): Fixes of timeout, example, warnings and bounding + add a 2MB part scheme for Zigbee ED
  boards.txt
  libraries/Zigbee/examples/Zigbee_On_Off_Switch/Zigbee_On_Off_Switch.ino
  libraries/Zigbee/src/ZigbeeCore.cpp
  libraries/Zigbee/src/ZigbeeEP.cpp
  libraries/Zigbee/src/ZigbeeEP.h
  libraries/Zigbee/src/ep/ZigbeeCarbonDioxideSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeFlowSensor.cpp
  libraries/Zigbee/src/ep/ZigbeePressureSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeTempSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeThermostat.cpp
  tools/partitions/zigbee_2MB.csv
Labels: Status: Pending Merge, Area: Zigbee

#10834 fix(zigbee): Fixes in handlers, destructors and co2 sensor delta reporting
  libraries/Zigbee/src/ZigbeeCore.cpp
  libraries/Zigbee/src/ZigbeeCore.h
  libraries/Zigbee/src/ZigbeeEP.cpp
  libraries/Zigbee/src/ZigbeeEP.h
  libraries/Zigbee/src/ZigbeeHandlers.cpp
  libraries/Zigbee/src/ep/ZigbeeCarbonDioxideSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeCarbonDioxideSensor.h
  libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.h
  libraries/Zigbee/src/ep/ZigbeeColorDimmerSwitch.h
  libraries/Zigbee/src/ep/ZigbeeDimmableLight.h
  libraries/Zigbee/src/ep/ZigbeeFlowSensor.h
  libraries/Zigbee/src/ep/ZigbeeLight.h
  libraries/Zigbee/src/ep/ZigbeeOccupancySensor.h
  libraries/Zigbee/src/ep/ZigbeePressureSensor.h
  libraries/Zigbee/src/ep/ZigbeeSwitch.h
  libraries/Zigbee/src/ep/ZigbeeTempSensor.h
  libraries/Zigbee/src/ep/ZigbeeThermostat.h
Labels: Status: Pending Merge, Area: Zigbee

#10833 fix(i2s): Check if pin is used before clearing bus
  libraries/ESP_I2S/src/ESP_I2S.cpp
Labels: Area: Peripherals API, Status: Pending Merge

#10841 Bugfix/include order
  cores/esp32/Arduino.h
  cores/esp32/FirmwareMSC.cpp
  cores/esp32/esp32-hal-gpio.h
Labels: Type: Bug :bug:, Area: Peripherals API, Status: Pending Merge

#10859 feat(eth): Add support for generic IEEE 802.3 driver
  libraries/Ethernet/src/ETH.cpp
  libraries/Ethernet/src/ETH.h
Labels: Status: Pending Merge

#10858 feat(i2c): Add support for the new I2C driver in IDF v5.4
  CMakeLists.txt
  cores/esp32/esp32-hal-i2c-ng.c
  cores/esp32/esp32-hal-i2c.c
  libraries/Wire/src/Wire.cpp
  libraries/Wire/src/Wire.h
  variants/esp32c6/pins_arduino.h
Labels: Area: Peripherals API, Status: Pending Merge

#10768 feat(esp32): Added a new device(xiao esp32s3 plus)
  boards.txt
  variants/XIAO_ESP32S3_Plus/bootloader-tinyuf2.bin
  variants/XIAO_ESP32S3_Plus/partitions-8MB.csv
  variants/XIAO_ESP32S3_Plus/pins_arduino.h
  variants/XIAO_ESP32S3_Plus/tinyuf2.bin
Labels: Status: Pending Merge, Type: 3rd party Boards

#10821 Add IAS Zone Notification Message service to ZigbeeHandlers and ZigbeeEP.h
  libraries/Zigbee/src/ZigbeeEP.h
  libraries/Zigbee/src/ZigbeeHandlers.cpp
Labels: Status: Pending Merge, Area: Zigbee

#10863 feat(zigbee): Add Time cluster support + fix of duplicate indentify cluster
  libraries/Zigbee/examples/Zigbee_Temperature_Sensor/Zigbee_Temperature_Sensor.ino
  libraries/Zigbee/examples/Zigbee_Thermostat/Zigbee_Thermostat.ino
  libraries/Zigbee/src/ZigbeeEP.cpp
  libraries/Zigbee/src/ZigbeeEP.h
  libraries/Zigbee/src/ZigbeeHandlers.cpp
  libraries/Zigbee/src/ep/ZigbeeCarbonDioxideSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeFlowSensor.cpp
  libraries/Zigbee/src/ep/ZigbeeOccupancySensor.cpp
  libraries/Zigbee/src/ep/ZigbeePressureSensor.cpp
Labels: Status: Pending Merge, Area: Zigbee

#10911 fix: Update the root certificate for the BasicHttpsClient example
  libraries/HTTPClient/examples/BasicHttpsClient/BasicHttpsClient.ino
Labels: Status: Pending Merge

#10921 fix(logging): incorrect FPS logging
  libraries/ESP32/examples/Camera/CameraWebServer/app_httpd.cpp
Labels: Status: Pending Merge
